### ISSUE TITLE
Unexpected invocation of exception handler after catching exception

### ISSUE THREAD

**Issue by marcoferrer** [Kotlin/kotlinx.coroutines#1018]
- Coroutines: 1.1.1
- Kotlin: 1.3.21

While working with the reactor integration for coroutines I noticed some unexpected behavior. When catching and suppressing an exception, the `CoroutinesExceptionHandler` is still being invoked. I think I might have a flawed understanding of how the handler is meant to work.

I've included a simplified example in hopes of getting a little more clarity on what my issue could be.

There are three methods here that each produce different behavior.
* `doWork1` behaves as expected
* `doWork2` Never executes
  * Always results in `JobCancellationException: Parent job is Completed`
  * Is most likely flawed usage due to `coroutineScope` builder requiring its children to complete before returning
* `doWork3` Executes normally but invokes the exception handler

```kotlin
class Test {

    // Behaves as expected
    suspend fun doWork1(arg: String): String =
        coroutineScope {
            mono { error("random") }.awaitFirst()
        }

    // Never executes
    // Results in JobCancellationException: Parent job is Completed
    suspend fun doWork2(arg: String): String =
        notWorkingMonoScope { "ok" }.awaitFirst()

    suspend fun <T> notWorkingMonoScope(block: suspend CoroutineScope.() -> T): Mono<T> =
        coroutineScope { mono { block() } }


    // Behaves as expected
    // But also causes the CoroutineExceptionHandler to be called even after catching.
    suspend fun doWork3(arg: String): String =
        workingMonoScope { error("random") }.awaitFirst()

    suspend fun <T> workingMonoScope(block: suspend CoroutineScope.() -> T): Mono<T> =
        suspendCoroutineUninterceptedOrReturn { uCont ->
            CoroutineScope(uCont.context).mono { block() }
        }

    @Test
    fun testExceptionHandler() {

        val handler = CoroutineExceptionHandler { _, e ->
            println("This shouldnt be getting called. $e")
        }

        val job = GlobalScope.launch(handler) {
            try {
                println("Result: " + doWork3("arg")) 
            } catch (e: Throwable) {
                println("Caught Error: $e")
            }
            println("Complete")
        }

        runBlocking { job.join() }
    }
}
```

**Comment by elizarov** [comment]
This is expected. With structured concurrency an exception in the scope cancels the parent and all the other children of the same scope. `coroutineScope { ... }` is explicitly designed to contain a number of concurrent sub-jobs, so that you can use `try/catch` around it. 

Also, please, note that `CoroutineScope(uCont.context).mono` or `.anyOtherCoroutineBuilder` is an extremely bad practice. It is not composable, since it throws exception into the "outer" scope in which the function is invoked without explicitly announcing it. As a matter of style, all such functions shall be declared as extensions on `CoroutineScope` or take it as parameter. The idiomatic signature for such a function is:

```
fun <T> CoroutineScope.workingMonoScope(block: suspend CoroutineScope.() -> T): Mono<T> =
    mono { block() }
```

This makes it impossible to use incorrectly (you'll be able to use it only inside `coroutineScope`) and that is exactly how `mono()` coroutine builder is designed, so you should not need yet another function for that purpose.

Does it help?

**Comment by marcoferrer** [comment]
Thanks for the clarification
> Also, please, note that `CoroutineScope(uCont.context).mono` or `.anyOtherCoroutineBuilder` is an extremely bad practice. It is not composable, since it throws exception into the "outer" scope in which the function is invoked without explicitly announcing it.

This is also good to know. So rule of thumb is `fun CoroutineScope.something()`, never `suspend fun someCustomBuilder()`



> This makes it impossible to use incorrectly (you'll be able to use it only inside `coroutineScope`) and that is exactly how `mono()` coroutine builder is designed, so you should not need yet another function for that purpose.

Correct. Considering this, its safe to say that `doWork1` is what Ill stick with. I shouldnt try to consolidate `coroutineScope{ mono{ ... } }` into another method, and in my case, I cant change `doWork` to an ext on `CoroutineScope`

Thanks for the clarification!
