### ISSUE TITLE
java.time support for Flow

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlinx.coroutines#1165]
Consider to overload `Flow` operators with milliseconds parameters using `Duration` instead.

**Comment by avently** [comment]
Why you so like java.time? Why not just Longs? Android has problems with this package

**Comment by JakeWharton** [comment]
Android doesnnot have problems with it. They're only available on certain API levels, similar to most of the APIs that are exposed.

Longs are in general terrible types for representing anything since it carries no semantic information. Nothing prevents you from adding milliseconds to seconds and interpreting it as hours.

**Comment by avently** [comment]
>They're only available on certain API levels

Equals to 

>Android has problems with this package

Coroutines should work everywhere without limiting its support to android users.
Longs looks good when they used like:
10 * 1000 for seconds
10 * 60 * 1000 for minutes
10 * 60 * 60 * 1000 for hours, etc.
No problem with a speed and understanding.

**Comment by JakeWharton** [comment]
All you've done is emphasize my criticisms.

**Comment by elizarov** [comment]
We're working on adding durations support to Kotlin stdlib and we will support Kotlin duration types in coroutines library when they become available. There is no plan to direcly support Java's durations, but eventually there will be converters.

**Comment by elizarov** [comment]
It was fixed by #1834
