### ISSUE TITLE
Flow.onEmit select clause

### ISSUE THREAD

**Issue by cyberdelia** [Kotlin/kotlinx.coroutines#1183]
I was looking to combine two flows, and found myself looking for an `Flow.onEmit` select clause. This could also to do thing like this, and potentially make easier to intertwine channels and flow:

Simple use case to illustration the idea:
```kotlin
flow {
  select {
    flow.onEmit { value -> 
      emit(value)
    }
    onTimeout(timeout) { value -> 
      emit(timeoutValue)
    }
  }
}
```

**Comment by qwwdfsad** [comment]
`onEmit` statement is indeed very useful, but it will overcomplicate flow design a lot: `Flow` will no longer be SAM interface and the default implementation of `onEmit` is unclear.

We use the following pattern is our operators:
```
fun <T> Flow<T>.operator(): Flow<T> = flow {
    coroutineScope {
        val channel = produce { collect { send(it) } }
        select {
            channel.onReceive { ... }
        }
    }
}
```

**Comment by elizarov** [comment]
Flows are _cold_. They must be explicitly started to begin emitting elements. You cannot have `onXxx` clause for a cold enity, so `onEmit` cannot conceptually exist. All select `onXxx` clauses operate on _hot_ entities that are already active and produce element that you can wait for.

So, indeed, the pattern that @qwwdfsad is what should be used with flows by design. We plan to simplify this process of "starting a flow" with a shortcut `produceIn` operator that would start a flow in a specified scope, so that the above come becomes:

```
un <T> Flow<T>.operator(): Flow<T> = flow {
    coroutineScope { // delimit a scope in which flow is running
        val channel = produceIn(this) // run flow in the scope
        select {
            channel.onReceive { ... }
            ...
        }
    }
}
```
