### ISSUE TITLE
Replacing Java Timer with Kotlin Coroutine Timer

### ISSUE THREAD

**Issue by anggrayudi** [Kotlin/kotlinx.coroutines#1186]
I often using this method to replace `java.util.Timer` in my projects:
```kotlin
inline fun startCoroutineTimer(delayMillis: Long = 0, repeatMillis: Long = 0, crossinline action: () -> Unit) = GlobalScope.launch {
    delay(delayMillis)
    if (repeatMillis > 0) {
        while (true) {
            action()
            delay(repeatMillis)
        }
    } else {
        action()
    }
}
```
`java.util.Timer` is buggy. On some Android devices, it causes the following crash, even though I re-init the object:

    java.lang.IllegalStateException: Timer was canceled

With Kotlin Coroutines, it is possible for me to prevent this terrible error. I hope you add the method I wrote above.

**Comment by JakeWharton** [comment]
You probably want this to be a factory for a Flow that emits either Unit or a counter on each tick.

**Comment by anggrayudi** [comment]
@JakeWharton, I am sure that somebody else needs it as well. I hope this will be added to Coroutine. It is simple code, but powerful.

**Comment by JakeWharton** [comment]
I would be against it as is, if that wasn't clear. Having a Flow factory which is a timer, however, makes sense.

**Comment by anggrayudi** [comment]
I am not sure whether this is related to Coroutine itself since it is an additional method to replace Java Timer. In Java Timer, I write the following code to start a repeated task every 1 second:
```kotlin
val timer = Timer()
timer.schedule(object : TimerTask() {
    override fun run() {
        // some actions
    }
}, 1, 1000) // Minimum delay is 1 millisecond. If lower, it throws IllegalArgumentException
```
The main backward from Java Timer is, we cannot start the repeated action immediately by setting the delay time to 0ms. Hence, the following approach with Coroutine is possible:

```kotlin
val timer: Job = startCoroutineTimer(delayMillis = 0, repeatMillis = 1000) {
    // some actions
}
```

Another backward from Java Timer is, it sometimes throws `java.lang.IllegalStateException: Timer was canceled` and causes app to crash. I tried to re-init the Timer and start a new one. But the error still appears. I don't know why. It affects less than 2% of my users.

I see Crashlytics reported this message. When I migrated to Coroutine timer, the error is gone. I hope you consider adding this method to Coroutine. Thanks in advance.

**Comment by napperley** [comment]
If users want a concurrency model agnostic version of this functionality then they should down vote the [comment](https://github.com/Kotlin/kotlinx.coroutines/issues/1186#issuecomment-491944885) that was made earlier.

**Comment by napperley** [comment]
What Jake is proposing is to make this functionality only available if using the RX concurrency model via the Flow implementation. Doing so would be a extremely bad design decision that promotes **tight coupling** with the functionality only being available in Flow, when this functionality isn't dependent on **any** concurrency model.

**Comment by Enrico2** [comment]
Based on the original suggestion, took a stab at a more testable variration:

```kotlin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.time.Duration
import java.util.concurrent.atomic.AtomicBoolean

class KorosTimerTask private constructor(
	delay: Duration = Duration.ZERO,
	repeat: Duration = Duration.ZERO,
	private val coroutineScope: CoroutineScope = GlobalScope,
	private val action: suspend () -> Unit
) {
	private val delayMillis = delay.toMillis()
	private val repeatMillis = repeat.toMillis()
	private val keepRunning = AtomicBoolean(true)
	private var job: Job? = null

	fun start() {
		job = coroutineScope.launch {
			delay(delayMillis)
			if (repeatMillis > 0) {
				while (keepRunning.get()) {
					action()
					delay(repeatMillis)
				}
			} else {
				action()
			}
		}
	}

	/**
	 * Initiates an orderly shutdown, where if the timer task is currently running,
	 * we will let it finish, but not run it again.
	 * Invocation has no additional effect if already shut down.
	 */
	fun shutdown() {
		keepRunning.set(false)
	}

	/**
	 * Immediately stops the timer task, even if the job is currently running,
	 * by cancelling the underlying Koros Job.
	 */
	fun cancel() {
		keepRunning.set(false)
		job?.cancel("cancel() called")
	}

	companion object {
		/**
		 * Runs the given `action` after the given `delay`,
		 * once the `action` completes, waits the `repeat` duration
		 * and runs again, until `shutdown` is called.
		 */
		fun start(
			delay: Duration = Duration.ZERO,
			repeat: Duration = Duration.ZERO,
			action: suspend () -> Unit
		): KorosTimerTask =
			KorosTimerTask(delay, repeat, action = action).also { it.start() }
	}
}
```

**Comment by elizarov** [comment]
@anggrayudi Can you, please, elaborate a bit on how you use a function like that. You write in your message this example:

```
val timer: Job = startCoroutineTimer(delayMillis = 0, repeatMillis = 1000) {
    // some actions
}
```

Do what are those "some actions" that are inside? What do use it for? What is your use-case? Can you give a larger example of a piece of code that is using `startCoroutineTimer`?

**Comment by zach-klippenstein** [comment]
> this functionality isn't dependent on any concurrency model.

Callbacks are just another concurrency model. It's trivial to convert between callbacks and Flows, but the latter already answers questions that aren't answered by the originally proposed solution.

How would you manage the lifecycle of this timer? How do you customize the dispatcher? The original proposal uses `GlobalScope` and provides no mechanism to stop/dispose of the timer, which means every timer that gets created will be leaked. It also doesn't provide a mechanism for controlling which dispatcher is used to run the timer, which can be inefficient because it forces consumers using the timer from other dispatchers to change threads just to run the delay (eg if I'm running a timer on a UI thread, I can just use the UI system's scheduling mechanism and not hop into the default pool and back). 

The advantage of exposing this functionality using Flow is that the Flow API already has answers for those questions, and doesn't require defining a whole new API surface, with its own documentation, learning curve, etc.

I don't understand your aversion to using Flow as the primitive here. Flow is a lightweight abstraction on basic coroutine concepts, so it's useable from any concurrency model. It's built-in to the coroutines library, so there's no added dependency weight.

**Comment by Enrico2** [comment]
@zach-klippenstein see my suggestion to address your (valid!) concerns.

**Comment by anggrayudi** [comment]
This is how the function works @elizarov :

```kotlin
inline fun startCoroutineTimer(delayMillis: Long = 0, repeatMillis: Long = 0, crossinline action: () -> Unit) = GlobalScope.launch {
    delay(delayMillis)
    if (repeatMillis > 0) {
        while (true) {
            action()
            delay(repeatMillis)
        }
    } else {
        action()
    }
}
```

**Comment by anggrayudi** [comment]
@elizarov I use the function to ping an IP address every 2 seconds. This app implement that function https://play.google.com/store/apps/details?id=com.anggrayudi.ping

**Comment by elizarov** [comment]
@anggrayudi Thanks. If this the only thing you are using it for in your application?

**Comment by anggrayudi** [comment]
@elizarov I am using it on another app too, https://play.google.com/store/apps/details?id=com.anggrayudi.watercat

This Coroutines timer is really helpful to report download speed to user.

**Comment by elizarov** [comment]
You are welcome to use your `startCoroutineTimer` solution, but we don't plan to a function like `startCoroutineTimer` to the core library, because it is easy to write, limited to this narrow use-case and cannot be easily composed with other operations. 

Our plan is to provide ready-to-use tick-generators (~timers) for Kotlin Flow so that your particular case would be solved with code like this (note, that names are purely tentative here):

```
tickerFlow(1000)
    .onEach { /* some actions here */ }
    .launchIn(scope)
``` 

The advantage of using the flow here is that you can easily use other flow operators to control what happens when the action takes longer than ticker period, etc, without having to provide lots of configuration options to the `tickerFlow` function itself.

Please, use #540 as an umbrella issue for that work to post your use-cases.

**Comment by gmk57** [comment]
@anggrayudi Thanks for the idea and "reference" implementation! ;)

[Here](https://gist.github.com/gmk57/67591e0c878cedc2a318c10b9d9f4c0c) is my variant, almost as simple, but slightly more configurable (dispatcher from `scope` or `context`, cancellation via `scope` or `job`).

We use it for a lot of things on Android: periodic downloading or uploading data to server, periodic calculations, on-screen timers...

And I would prefer it to a Flow-based solution, because in many cases it is more convenient to calculate delay *since previous run completion*. Especially on Android, where in Doze mode multiple "time ticks" are queued and then all fire in quick succession. We learned this a hard way with RxJava `Observable.interval()` and had to add `throttleFirst()` everywhere to prevent e.g. dozens of simultaneous network requests. Coroutine-based solution just does not have this issue.

I also prefer to keep things as simple as possible, and "loop with delay" seems easier to grasp then "stream of time ticks". Flows are nice and definitely have their uses, but I don't like "everything is a stream" mantra. From my experience with RxJava, complex stream-based logic may become an undecipherable mess.
