### ISSUE TITLE
`runBlockingTest` with `coroutineScope {}` expected behavior

### ISSUE THREAD

**Issue by mkobit** [Kotlin/kotlinx.coroutines#1240]
```kotlin
runBlockingTest {
  val job = launch {
    delay(1_000)
  }
  println(job)
  expectThat(job).not { isCompleted() }
  advanceTimeBy(1_000)
  expectThat(job).isCompleted()

  val jobWithScope = coroutineScope {
    launch {
      delay(1_000)
    }
  }
  expectThat(jobWithScope).not { isCompleted() } // fails here: Expect that "coroutine#5":StandaloneCoroutine{Completed}@4c777e7b:
  advanceTimeBy(1_000)
  expectThat(jobWithScope).isCompleted()
}
```

I'm still figuring out the semantics and right way to structure code that makes use of coroutines, especially with regards to how to write interfaces and classes that make use of `suspend` functions. 

Is the  `  expectThat(jobWithScope).not { isCompleted() }` behavior above expected?

**Comment by objcode** [comment]
Thanks for the minimal repro!

In this case, I believe the behavior is expected since coroutineScope implicitly joins the job before exiting.

```
  val jobWithScope = coroutineScope { <-- create a new coroutineScope that observes children
    launch { <-- create a new child job in the new coroutineScope
      delay(1_000)  <-- suspend here for 1_000
    }
  } <-- implicitly join the job that's created.
```

 In resumed execution the implicit join causes the delay to auto-progress because it's called from the `runBlockingTest` coroutine. Since `coroutineScope` won't ever complete until all child jobs are complete, it is known that by the next executed line `launch` must be completed.

The reason it auto progresses is because the `join` from `coroutineScope` is called from the `runBlockingTest` coroutine (if it didn't auto-progress, the test would suspend forever at this point).

After all the auto progressing is applied from a resumed dispatcher, this code is equivalent to this simpler code:

```
runBlockingTest {
    delay(1_000)
    // this will always be reached, and time has been auto progressed by 1_000 to get here
}
```

To avoid auto-progressing at the end of the `coroutineScope` lambda in this case, you will have to introduce another coroutine in your test like this:

```
  val jobWithScope = launch {
    coroutineScope {
        launch {
          delay(1_000)
        }
      }
}
```

Understandably, this behavior is somewhat surprising when you first encounter it - however the easiest way to think about it is that a resumed dispatcher in `runBlockingTest` will always auto-advance virtual time to get to the next line instead of hanging the test forever.

**Comment by objcode** [comment]
You can also use `pauseDispatcher` to test things like this too, but I'd suggest introducing another coroutine here.

**Comment by objcode** [comment]
Reading through the docs, this behavior can be better documented.

**Comment by mkobit** [comment]
Thanks @objcode , the behavior makes sense and I think the issue can be closed if desired.
