### ISSUE TITLE
bufferSize or capacity for channelFlow

### ISSUE THREAD

**Issue by jcornaz** [Kotlin/kotlinx.coroutines#1283]
`flowViaChannel` had a capacity argument (named `bufferSize`).

But since its deprecation in favor of `channelFlow` we can no longer specify the capacity of the underlying channel.

Was it on purpose?

Not being able to specify the buffer size is very limiting and sounds weird when other operators such as `flowOn` support a `bufferSize`.

**Comment by elizarov** [comment]
You still can specify capacity of the underlying channel using `buffer` operator.

**Comment by jcornaz** [comment]
Ah ok!

Thank you very much.

But wouldn't it be simpler and easier to discover if it'd be an argument of `channelFlow`?

**Comment by elizarov** [comment]
If you really need it, then you can discover it by reading `channelFlow` documentation. 
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/channel-flow.html

I don't believe it needs better discoverability, since I don't believe there is much need among the general public to control this buffer size.

**Comment by jcornaz** [comment]
Ok, thanks for your help
