### ISSUE TITLE
TestCoroutineDispatcher

### ISSUE THREAD

**Issue by BulatMukhutdinov** [Kotlin/kotlinx.coroutines#1292]
I have a method with next piece of code
```
viewModelScope.launch(exceptionHandler) {
            val rateList = withContext(Dispatchers.IO) {
                buildExchangeRateUseCase.execute(selected)
            }
            rates.onNext(rateList)
}
```
and test is 
```
 coEvery {
            buildExchangeRatesUseCaseMock.execute(selectedRate)
 } returns exchangeRates

viewModel = ExchangeRateLifecycleAwareViewModel(buildExchangeRatesUseCaseMock)

assertData(exchangeRates, viewModel.rates)
```

I have also called  ```Dispatchers.setMain(testDispatcher)```

The problem is code inside ```withContext()``` is called asynchronously after assertion happens. A code inside my ```exceptionHandler``` also is called after assertion in case I want to assert exception behavior.
I was able to solve that using runBlocking instead of withContext. However, in documentation it is said ```runBlocking should not be used from a coroutine```. Although, in coroutines basic guide you gave both these functions to jump between threads (https://kotlinlang.org/docs/reference/coroutines/coroutine-context-and-dispatchers.html#jumping-between-threads).

Could you please give an idea, how to first execute all the code inside withContext() before assertion is called?

P.S. I have tried runBlockingTest() but it also has no effect

**Comment by streetsofboston** [comment]
You can change your code to use a bit of dependency injection. In this case, inject the Dispatcher (`Dispatchers.IO` or a `TestCoroutineDispatcher`) into the construction of the class (`ViewModel`?).

```
class MyViewModel(
    private ioDispatcher: CoroutineDispatcher,
    ...
) : ViewModel() {
    ...
        ...
        viewModelScope.launch(exceptionHandler) {
                    val rateList = withContext(ioDispatcher) {
                        buildExchangeRateUseCase.execute(selected)
                    }
                    rates.onNext(rateList)
        }
        ...
    ...
}
```    
In your actual code, you'll provide `Dispatchers.IO`. In your unit-test code, you'll provide your `testCoroutineDispatcher`.

**Comment by BulatMukhutdinov** [comment]
@streetsofboston thanks for your proposal but I don't really like it - it would create unneeded overhead. What if I need to run ```launch``` 3 times with 3 different Dispatchers? It means 3 additional parameters. I believe there are should be better way using ```testCoroutineDispatcher```

@qwwdfsad  Could you please give some advice?

**Comment by qwwdfsad** [comment]
DI is the only solution for now.

We have plans to focus on testability in 1.3.1 right after the flow release. It will include stabilization of test dispatcher and (probably) mockable default and IO dispatchers, similar to Main dispatched (`Dispatchers.setMain` in kotlinx-coroutines-test)

**Comment by kylegoetz** [comment]
Hi. I ran into this issue today. To make sure I understand, if I want to unit test ViewModel method that makes a RESTful API call and thus is launched via `viewModelScope.launch(Dispatchers.IO) { api.call() }`, then the only way to do this right now is rewrite my ViewModel class to take a `CoroutineDispatcher` instance and use that in the `viewModelScope.launch(myCoroutineDispatcher) { /*...*/}`, and then in my unit test I have to pass in a newSinglThreadContext or something and then do the higgledypiggledy with `Dispatchers.setMain` and `Dispatchers.resetMain` in the `@Before` and `@After` methods?

Thanks for clarification. If this is true, I will just wait for this to be supported because I am not going to rewrite my code because of testing limitations. Not a complaint, just I guess registering my thoughts on the idea of allowing tests to affect how your app objects are written. :)

**Comment by jeffzoch** [comment]
`Dispatchers.setIO` as a compliment to `Dispatchers.setMain` would be great. Currently, its really suboptimal to change every constructor that uses IO to accept a dispatcher as a parameter - it just isnt pragmatic and leads to teams writing busy loops in tests waiting for the thread pool in tests. Its hard to convince people to add this to every single constructor across dozens of classes.

**Comment by mhernand40** [comment]
The beauty of DI via constructor injection is that tests are self-contained. When global static setters are required, then they also need to be reset when each test completes. This hinders the possibility of ever running tests in parallel since one test may reset the global state while another test is executing in parallel and will have its assumed global state swept from under its feet. 🤷‍♂️ 

In my setup, I've declared an injectable `Dispatchers` type like so:
```Kotlin
interface Dispatchers {
    val default: CoroutineDispatcher
    val io: CoroutineDispatcher
    val main: CoroutineDispatcher
}
```

And then the implementation looks like so:
```Kotlin
…
import kotlinx.coroutines.Dispatchers as KotlinxDispatchers

object AndroidDispatchers : Dispatchers {
    override val default: CoroutineDispatcher = KotlinxDispatchers.Default
    override val io: CoroutineDispatcher = KotlinxDispatchers.IO
    override val main: MainCoroutineDispatcher = KotlinxDispatchers.Main
}
```

Since I use Dagger, my Module binds `AndroidDispatchers` to the `Dispatchers` type and I always make sure to pass in my own injectable `Dispatchers`. The only downside is that certain Coroutine APIs use default parameters for `CoroutineContext` which end up resulting in the real `Dispatchers.Default` being used internally. If you're not careful and forget to explicitly use the injectable `dispatchers.default`, you may run into flaky tests.

**Comment by dkhalanskyjb** [comment]
We thoroughly reworked the test module in https://github.com/Kotlin/kotlinx.coroutines/commit/2e25baeb29274853a1926f6bf7c3be761f306d72, so now it supports multithreading and waiting for external completions. It is still preferable to use DI since the delays in the tasks forked off to other dispatchers are not skipped, but at least it's now possible to write tests while using third-party code.
