### ISSUE TITLE
Fail on channel.send() with two successive forEach() calls

### ISSUE THREAD

**Issue by glebleonov** [Kotlin/kotlinx.coroutines#1329]
Consider the following code 
```
    fun ReceiveChannel<Int>.read() = GlobalScope.launch {
        consumeEach {
            println(it)
        }
    }

    @Test
    fun testChannels() = runBlocking {
        val channel = Channel<Int>(Channel.UNLIMITED)

        val job = channel.read()
        channel.send(1)
        job.cancel()

        delay(1000)

        channel.read()
        channel.send(2)
    }
```
Such test fails with `Job was cancelled` at `channel.send(2)`. 
I use 1.2.2 coroutines version.

**Comment by zach-klippenstein** [comment]
Where are you getting `ReceiveChannel.forEach` from? I don't see it in the library in version 1.2.2.

**Comment by glebleonov** [comment]
Sorry, my bad. `forEach` is my wrapper on `consumeEach` method. I've updated the code. Result is the same.

**Comment by zach-klippenstein** [comment]
That is the expected behavior of `consumeEach`. `consumeEach` uses `consume`, which will always cancel the channel after the block exits, whether successfully or by throwing.

The [documentation](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/consume-each.html) says this, which could definitely be more clear about how it handles cancellation:
> Performs the given action for each received element and cancels the channel after the execution of the block. If you need to iterate over the channel without consuming it, a regular for loop should be used instead.

**Comment by qwwdfsad** [comment]
@zach-klippenstein is right (also, confusing `forEach` and `consumeEach` is one of the reasons we are not introducing `forEach` :))

> 1.2.2

This is the version where `ClosedSendChannelException` became `IllegalStateException` instead of `CancellationException` (which is probably ignored by everyone), thus you started to observe it.
This is done deliberately as an attempt to send value to closed channel is a programmatic bug rather than regular cancellation.
