### ISSUE TITLE
Flow Suggestion Operator:  catchAndContinue

### ISSUE THREAD

**Issue by halimpuckjava** [Kotlin/kotlinx.coroutines#1339]
hi

with project reactor, when flux catch error it can continue process data (using onErrorContinue) 
so i suggest to add an operator similar allow flow to continue processing data on error (catchAndContinue)

**Comment by qwwdfsad** [comment]
If we are talking about upstream errors, then Flow has `catch` operator, that can be used for any variation of `onError*`.

**Comment by halimpuckjava** [comment]
this is a simple example:
```
flowOf(1,0,2).map { 1 / it }.onEach { .... }.carch { ..... }.launchIn(...) 
```
son in console : i see : 
1
0 / by zero
but i excepted to see one more 0 (1 / 2) in last, because this exception (/ by zero) flow not continue just handle exception and finish, so why not use an other operator to allow flow continue after handle this exception

**Comment by elizarov** [comment]
@halimpuckjava The executions in the flow are quite conceptually similar to the exception in a regular Kotlin code. You can catch them, but you cannot continue from what you were doing. There is simply no way to. See, for example:

```
try {
    println(1 / 1)
    println(1 / 0) // throws exception
    println(1 / 2 ) // not executed, you cannot continue to execute it
} catch (e: Throwable) { ... }
```

They only thing you can do is to retry which means starting from scratch. See https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/index.html

If you want to coninue on error, you'll have to protect each error-causing oprator individually, so instead of `flowOf(1,0,2).map { 1 / it }` write:

```
flowOf(1,0,2).transform { 
    try { emit(1 / it) } catch(e: Throwable) { /* do something else */ }
}
```

Does it help?

**Comment by halimpuckjava** [comment]
thanks 

so there is any fixed date for flow stable version ??
