### ISSUE TITLE
Should I close channel explicitly like dispose in Rx? 

### ISSUE THREAD

**Issue by XinyueZ** [Kotlin/kotlinx.coroutines#140]
Well, with Rx I would use CompositeDisposable and clear of it to clean up future calls or stop stream further for cases like leave from ViewModel etc.

Should I do same thing that make a collection of channels and release calling "close()" on them if I won't use them any more?

**Comment by elizarov** [comment]
You rarely have _standalone_ channels in your code. You either use _produce_ or _actor_ patterns/builders, both of with encapsulate their channels into a `Job`. Then you use parent-child relations to centrally manage all your job. `Job` _is_ a replacement for `CompositeDisposable` due to parent-child hierarchy support. See more here: https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#children-of-a-coroutine

**Comment by XinyueZ** [comment]
@elizarov yes , got it.
