### ISSUE TITLE
Flow improvement (sort and onCancel)

### ISSUE THREAD

**Issue by halimpuckjava** [Kotlin/kotlinx.coroutines#1495]
hi, 

i have some suggestion & improvement for Flow: 

1. add new operators:  sort, onCancel
2. add one parameter to onComplete (isCancel: Boolean)

**Comment by fvasco** [comment]
How `sort` should work?

Did you consider `flowOf(1, 3, 2).toList().sorted()`?

**Comment by halimpuckjava** [comment]
with buffer() operator, the flow use channel to buffering data so i think sort operator can use same channel technical

how about cancellation:
a. how flow can track this cancellation ? 
b. how distinct between complete & cancel ?

**Comment by elizarov** [comment]
@halimpuckjava Can you, please, explain the uses-case (with code example) for those new operations.

**Comment by halimpuckjava** [comment]
this is a sample code for flow cancellation
```kotlin
val scope = ....
flowOf(1, 2, 3).onEach { delay(200); println("data: $it")
                      .onComplete { println("complete $it")
                      .launchIn(scope) 
``` 
when scope is cancel, flow is complete normaly (exception = null), so how distinct between complete normaly & with cancellation, 
1. so how flow can track a cancellation of scope  ?
2. add operator onCancel:
```kotlin
Flow.onCancel(action: suspend (t: CancellationExceptionn?) -> Unit)
````

**Comment by elizarov** [comment]
Why would you need to track cancellation of scope from the flow? What is your use-case? What are you trying to achieve?

**Comment by halimpuckjava** [comment]
my use-case is when user load data from database and want to cancel (scope cancel), flow invoke onComplete but in this operator user can't distinct if this flow complete normally or cancelled

**Comment by halimpuckjava** [comment]
user load data from server (database) using flow, if user want to cancel this operation flow invoke onComplete to indicate the flow in complete but in this case is complete with cancellation
so how distinct between complete & complete with cancellation

**Comment by elizarov** [comment]
But why you need to distinguish regular completion and cancellation of the flow? What is the use-case?

**Comment by halimpuckjava** [comment]
with Project Reactor, when i use Flux i can track when is canceled (doOnCancel) so i want see this operator in Coroutines Flow for more distinction between onComplete & onCancel  
thanks

**Comment by elizarov** [comment]
@halimpuckjava But why do you use `doOnCancel` with Project reactor? What for? What are you trying to achieve with it? Can you give a sample code from your project?

**Comment by halimpuckjava** [comment]
thanks
```kotlin
val subscription = Flux.just(1, 2, 3)
                                  .doOnCancel { handleCancellation() }
                                  .doOnTerminate { handleTermination() }
subscription.dispose()
```
1. when user cancel flux (dispose subscription) cancellation handled by doOnCancel
2. ignore doOnCancel, when dispose subscription, user can't know if flux is cancel or complete until doOnTerminate is invoke (user maybe want to invoke some task when cancellation happen)

**Comment by elizarov** [comment]
@halimpuckjava Sorry, but I don't see why would you need to track this cancellation. Can you show a larger context of the problem you are trying to solve?

**Comment by halimpuckjava** [comment]
thanks 

i just want to distinct between completion normally and completion with cancellation

**Comment by allenhumphreys** [comment]
@elizarov Since you were looking for a "problem" that could be solved by this. Our use case is that we start operations against a 3rd party service in response to HTTP requests. 

If the client connection is closed, the overall request and the flow that is running the operations are cancelled. We capture the particular completion state of the operation against the 3rd party service as cancelled, which is extremely valuable when debugging real world issues in production environments.

Having an `onCancel` is not necessarily solving a problem in this case, but having access to the information can greatly improve telemetry which can vastly improve a developers ability to characterize errors or system behaviors.

Another case that we actually have is tracking when a client cancels/disconnects before a download is completed. We are tasked with having our system track when a download starts, completes successfully, is cancelled, or encounters a server side issue. To fulfill this requirement, an `onCancel` or having access to the cancellation exception duration `onComplete` would be very helpful.

As a work around, I am using the following code, the behavior of which might break when flow implementation details change:

```kotlin
.onCompletion { error ->
    val job = coroutineContext[Job]
    if (error == null && job?.isCancelled == true && job.isCompleted == false) {
        dependencyTelemetry.success = false
        dependencyTelemetry.resultCode = "499"
    }
}
```

Not sure if this will affect anything, just wanted to share our experience with flow.

**Comment by elizarov** [comment]
@allenhumphreys Thanks! We're already committed to change `onCompletion` behavior in the upcoming release. See details here #1732 

To be compatible with this change, just don't check for `error == null` in your code. Checking for `job?.isCancelled == true && job.isCompleted` should be enough and is future-proof. 

After #1732 is released it will be possible to write a simpler code for your case:

```
.onCompletion { error ->
    if (error is CancellationException) {
        // is was cancelled
    }
}
```
