### ISSUE TITLE
Add support for tvOS and watchOS-based targets

### ISSUE THREAD

**Issue by sbogolepov** [Kotlin/kotlinx.coroutines#1596]
Kotlin/Native 1.3.60 will add support for tvOS and watchOS-based targets.
Since these targets are similar to iOS-based targets, adding them to the appropriate `build.gradle` should be sufficient.
Targets:
* watchos_x86
* watchos_arm32
* watchos_arm64
* tvos_x64
* tvos_arm64

**Comment by sockeqwe** [comment]
Any update on this? We are working on a multiplarform app and would like to target tvOS too. Any roadmap when you plan to add this, or at least whats the prioritization for you guys internally?

i.e. lets say if it takes another 2-3 months just because you have other / higher priorites (would be understandable), then we have to rethink our whole project and not target tvOS at all. I would really appreciate if you could just share some rough insides how important it is for you to get tvOS support soonish.

**Comment by qwwdfsad** [comment]
@sockeqwe tvOS and watchOS are available in version `1.3.2-1.3.60-eap-76`.

You can expect non-experimental tvOS/watchOS support in the next coroutines release after Kotlin 1.3.60

**Comment by qwwdfsad** [comment]
Version 1.3.2-1.3.60 with these targets is released

**Comment by qwwdfsad** [comment]
Fixed in 1.3.3

**Comment by sockeqwe** [comment]
Thank you!
