### ISSUE TITLE
Stacktrace recovery mode which replaces exception stacktrace

### ISSUE THREAD

**Issue by bnorm** [Kotlin/kotlinx.coroutines#1608]
For the project I work on I have to deal with a lot of exceptions I don't control. Many of these exceptions also contain additional fields which effectively disables stacktrace recovery.

Would it be possible to add a mode of stacktrace recovery which directly sets the recovered stacktrace on the thrown exception instead of trying to copy the thrown exception?

**Comment by qwwdfsad** [comment]
Unfortunately, it is not possible, because exceptions can be shared.
For example:
```
val exceptional = async { throw RuntimeException() } 
async {
    exceptional.await() // Stacktrace is recovered here
}

launch {
    exceptional.await() // But in the same time it is recovered here
}
```

What we can do though is to provide some global registry where you can register lambda that knows how to copy an exception. For example, `StacktraceRecovery.register<HttpStatusCodeException>() { e -> HttpStatusCodeException(e.code, e.message) }`. Will it solve your problem?

**Comment by bnorm** [comment]
Ah, I did not consider waiting the same `Deferred` multiple times. Thanks for explaining.

While a global registry would definitely solve my problem, I worry about how multiple registers of the same exception type might conflict. What if the registration was `CoroutineContext` based? Create a new `CoroutineContext.Element` which you would register recovery lambdas with?

**Comment by qwwdfsad** [comment]
>I worry about how multiple registers of the same exception type might conflict

That's why we haven't implemented it yet :) We probably could allow overwriting items in the registry (or, optionally, fail on conflicts) as exception copying should be pretty straightforward and hard to get wrong.

`CoroutineContext`-based solution may work as well, but is more intrusive and less obvious, because the one who is re-throwing an exception is responsible for recovering it. It means that in my example, `async` could have recovered an exception, while `launch` didn't.
