### ISSUE TITLE
Test passes for 'runBlocking' but fails for 'runBlockingTest'

### ISSUE THREAD

**Issue by MiSikora** [Kotlin/kotlinx.coroutines#1626]
The test below passes when `runBlocking` is used but fails with `runBlockingTest`.

```kotlin
sealed class Event {
  data class A(val id: Long) : Event()
  data class B(val id: Long) : Event()
}

class Test {
  @Test fun blocking() = runBlocking {
    val events = flowOf(Event.A(0), Event.B(0)).broadcastIn(this).asFlow()

    val a = events.filterIsInstance<Event.A>().map { "$it" }
    val b = events.filterIsInstance<Event.B>().map { "$it" }

    val strings = flowOf(a, b).flattenMerge().toList()

    Assert.assertEquals(strings, listOf(Event.A(0), Event.B(0)).map { "$it" })
  }

  @Test fun blockingTest() = runBlockingTest {
    val events = flowOf(Event.A(0), Event.B(0)).broadcastIn(this).asFlow()

    val a = events.filterIsInstance<Event.A>().map { "$it" }
    val b = events.filterIsInstance<Event.B>().map { "$it" }

    val strings = flowOf(a, b).flattenMerge().toList()

    Assert.assertEquals(strings, listOf(Event.A(0), Event.B(0)).map { "$it" })
  }
}
```

Events are missing from the expected result.

```sh
java.lang.AssertionError: 
Expected :[A(id=0)]
Actual   :[A(id=0), B(id=0)]
```

Kotlin: `1.3.50`.
Coroutines: `1.3.2`.

**Comment by qwwdfsad** [comment]
Most of the time (except really long timeouts).
Current `runTest` is way too limited and being reworked right now

**Comment by luis-cortes** [comment]
I have a need to test that a flow is emits correctly when data in the db changes (this solution looks clumsy to me, but I've not found any suggestions anywhere for how to do this).

This version makes the most sense to me as the order of execution is what I expect:
```
 @Test
  fun `inserting new data updates flow runBlocking`() = runBlocking {
    val channel = Channel<Int>()
    val job = launch {
      dataStore.observeData(ID)
          .map { 1 }
          .scanReduce { accumulator, value -> accumulator + value }
          .onEach { channel.send(it) }
          .collect()
    }
    assertEquals(1, channel.receive())
    insertNewData(NEW_DATA)
    assertEquals(2, channel.receive())
    channel.cancel()
    job.cancel()
  }
```

This is how I've had to alter the test in order to get it to pass with `runBlockingTest`:
```
 @Test
  fun `inserting new data updates flow runBlockingTest`() = runBlockingTest {
    val channel = Channel<Int>()
    pauseDispatcher {
      val job = launch {
        dataStore.observeData(ID)
            .map { 1 }
            .scanReduce { accumulator, value -> accumulator + value }
            .onEach { channel.send(it) }
            .collect()
      }
      runCurrent()
      assertEquals(1, channel.receive())
      insertNewData(NEW_DATA)
      yield()
      launch {
        assertEquals(2, channel.receive())
      }
      runCurrent()
      channel.cancel()
      job.cancel()
    }
  }
```

I'm confused as to why the test behaves differently when using `runBlockingTest` because I have no delays anywhere.

Should I not be using `runBlockingTest` in this situation?
More generally, should we stay away from `runBlockingTest` until it's done being reworked?

**Comment by Pozzoooo** [comment]
Hey, I'm facing the same issue on maybe a simpler scenario:
```
    @Test fun test1() {
        runBlockingTest {
            launch(Dispatchers.Default) {
                println("1")
                delay(1000L)
                println("2")
            }
            println("3")
        }
    }

    @Test fun test2() {
        runBlocking {
            launch(Dispatchers.Default) {
                println("1")
                delay(1000L)
                println("2")
            }
            println("3")
        }
    }
```

`test1` fails with leaked coroutine, "3" and "1" is printed.
`test2` passes with "3", "1" and "2" printed.

**Comment by MiSikora** [comment]
Another test case that fails for `runBlockingTest` but passes for `runBlocking`.

```kotlin
@Test fun test1() = runBlockingTest {
  val list = flowOf(1).onStart { emit(0) }
      .combine(flowOf("A")) { int, str -> "$str$int" }
      .toList()

  Assert.assertEquals(list, listOf("A0", "A1"))
}
```

Interestingly when `onStart` is used on the whole stream and not on parts of `combine` the test passes.

```kotlin
@Test fun test2() = runBlockingTest {
  val list = flowOf(1)
      .combine(flowOf("A")) { int, str -> "$str$int" }
      .onStart { emit("A0") }
      .toList()

  Assert.assertEquals(list, listOf("A0", "A1"))
}
```

**Comment by RBusarow** [comment]
> Should a test that passes using runBlocking always pass using runBlockingTest?

I would say definitely not.  `runBlockingTest` is _not_ a catch-all function which can be applied to anything.

Code which uses delays will execute differently.
Code which launches but also continues code after the launch will execute differently.
Code which leaks coroutines (intentionally or not) will execute differently and fail.  This is due to `cleanupTestCoroutines()`.

**Comment by RBusarow** [comment]
I think we can more easily illustrate the disconnect here with a different look at this example:

```Kotlin
@Test fun test1() = runBlockingTest {
  val list = flowOf(1).onStart { emit(0) }
      .combine(flowOf("A")) { int, str -> "$str$int" }
      .toList()

  Assert.assertEquals(list, listOf("A0", "A1"))
}
```

Let's reconstruct this a bit.

 ```Kotlin
@Test fun test1() = runBlockingTest {

    val ints = flowOf(0, 1, 2, 3)
    val strs = flowOf("A", "B", "C")

    val list = combine(ints, strs) { int, str -> "$str$int" }
      .flowOn(TestCoroutineDispatcher())
      .toList()

    list shouldBe listOf("A0", "A1", "B1", "B2", "C2", "C3")
}
```
The result:
```
Expected :["A0", "A1", "B1", "B2", "C2", "C3"]
Actual   :["A3", "B3", "C3"]
```

When `combine` does its thing, both flows are converted into channelCoroutines and populated with `sendFair(value)`.

The order of parameters matters here.  The flow of Ints is processed completely before the flow of Strings is touched.  This is because the `TestCoroutineDispatcher` in `runBlockingTest { ... }` is an immediate dispatcher.

The same can be said for the tests using `flattenMerge()`.  `flattenMerge()` uses `launch()`, which is different for `TestCoroutineDispatcher` than with a vanilla `runBlocking { ... }` or with `Dispatchers.Unconfined`.

In both cases, `runBlockingTest` looks like it's doing what it's supposed to.

> Interestingly when `onStart` is used on the whole stream and not on parts of `combine` the test passes.
> 
> ```kotlin
> @Test fun test2() = runBlockingTest {
>   val list = flowOf(1)
>       .combine(flowOf("A")) { int, str -> "$str$int" }
>       .onStart { emit("A0") }
>       .toList()
> 
>   Assert.assertEquals(list, listOf("A0", "A1"))
> }
> ```

This is because you're now emitting `A0` to the flow before `A1` is emitted.  `onStart { ... }` is executed before the collector or combine.

Also, the order of your parameters in `assertEquals()` is backwards.  It's `expected`, then `actual`. :)

**Comment by RBusarow** [comment]
> ```Kotlin
>     @Test fun test1() {
>         runBlockingTest {
>             launch(Dispatchers.Default) {
>                 println("1")
>                 delay(1000L)
>                 println("2")
>             }
>             println("3")
>         }
>     }
> ```

You're not actually using the dispatcher from `runBlockingTest` here.  You're overriding it with `Dispatchers.Default`.  If you were using the RBT dispatcher, it would automatically skip over that delay and the test would pass.

When overriding the dispatcher, you'd need to use `.join()` on the launch's `Job` to make sure execution had finished.

**Comment by Pozzoooo** [comment]
Hmmm, but how does that work for `runBlocking`?

If I need to have the same dispatcher, then should I encapsulate all `Dispatchers` to keep them under my control?
It looks like I'm gonna need to add a lot of dependencies for every case I need to use coroutines, my fear is to couple too much our code into the way coroutines works.

**Comment by RBusarow** [comment]
> Hmmm, but how does that work for `runBlocking`?
> 
> If I need to have the same dispatcher, then should I encapsulate all `Dispatchers` to keep them under my control?
> It looks like I'm gonna need to add a lot of dependencies for every case I need to use coroutines, my fear is to couple too much our code into the way coroutines works.

Yes, that's a common complaint.  The typical solution is to wrap all references up into a single injectable object like so:
```Kotlin
interface DispatcherProvider {
  val main: CoroutineDispatcher
  val mainImmediate: CoroutineDispatcher
  ...
}
```

A different solution is in the works for #1365 , where you'll be able to use `Dispatchers.setDefault(...)` to manipulate that singleton in lieu of all the injection, but now you're manipulating a shared state in your testing.

You can do things to mitigate this issue, such as only specifying the dispatcher when it's really necessary (for instance immediately before doing I/O in a repository).  Typically, you shouldn't need to specify the dispatcher as the main thread is typically capable of much more than we give it credit for.  Also, if you're using a third party library with coroutine support for I/O, such as Room or Retrofit, they already use their own dispatchers internally, so switching before calling a suspend function in their library is just wasteful.

Not to plug, but a final option would be my not-quite-complete little library [DispatcherProvider](https://github.com/RBusarow/DispatcherProvider), which uses the `CoroutineContext` itself to hold the interface described above.  This way, the dispatchers are set upon creation of a `CoroutineScope` and are accessible from any coroutine or suspend function via the `coroutineContext` property.

**Comment by fblampe** [comment]
Are there any news or a timeline for this? Removing delays in tests via RunBlockingTest would be very helpful, but only if it works reliably without a lot of extra coding.
