### ISSUE TITLE
[Question] Actor and concurrency issues 

### ISSUE THREAD

**Issue by ssljivic** [Kotlin/kotlinx.coroutines#1653]
When looking at the example `kotlinx-coroutines-core/jvm/test/guide/example-sync-07.kt`, more specifically at the following fragment

```
// This function launches a new counter actor
fun CoroutineScope.counterActor() = actor<CounterMsg> {
    var counter = 0 // actor state
    for (msg in channel) { // iterate over incoming messages
        when (msg) {
            is IncCounter -> counter++
            is GetCounter -> msg.response.complete(counter)
        }
    }
}
```

I cannot but notice that if for example 5 other coroutines send GetCounter message to the above actor,  they will be "served" sequentially one after another, i.e. no parallelism is achieved. Even although we have a CPU with 8 physical threads, each of "client" coroutines reading the counter value will be constrained by a sequential execution of the actor coroutine.

How can we avoid this sequential processing when using actor coroutine?

Thanks

**Comment by fvasco** [comment]
Actor is sequential, you cannot avoid this, but actors work in parallel with other coroutines.
You may use a `ReadWriteMutex` for this use case, but it is unavailable, yet.

**Comment by ssljivic** [comment]
> You may use a ReadWriteMutex

Correct me if I'm wrong, but the whole idea of corourine channels is to avoid mutable shared state. 

> but actors work in parallel with other coroutines

That is true, but still all reads from the actor's state is sequential. I ama asking if anyone knows for an elegant way to paralelize the read ops and in that way be able to utilize all CPU threads. 

If there is no way to do that, that is fine as well, I'm just checking if there is. Using mutable shared state is not what I am looking for however. 

Thanks

**Comment by fvasco** [comment]
Strictly speaking, a `Channel` is mutable: each `receive` mutates the `Channel` and multiple `receive`s do not return the same value. Share a `Channel` is a good idea to share tasks: each actor spools tasks from `Channel`.
More in general, this library simplify concurrency and asynchronicity.
Regardless of this library, avoiding mutable shared state is often a good idea.

Please consider that `actor` and `Mutex` are not so different: both work with a private, mutable state and both serialize messages (with some crucial differences).
You can consider to read: https://github.com/Kotlin/kotlinx.coroutines/issues/87

I am not suggesting you a particular design, your initial example is OK.

**Comment by zach-klippenstein** [comment]
Actors are sequential _by definition_. The whole point of an actor is to make private mutable state simpler to work with because you don't need to explicitly synchronize access to it, since it's only accessed by one thread/coroutine at a time. 

This can make actors useful for managing complex state, but they're just one tool among many and may not always be the best tool. This counter example is contrived and very inefficient - in production code it would be much more efficient to just use an atomic integer for a counter (`AtomicInteger` directly on the JVM, or using atomicfu for MP common code). You could also use a RWLock but that is also less efficient for this example since atomic integers support atomic increment operations already. If you're performing some operation more complex than a simple increment it might be more appropriate.

**Comment by qwwdfsad** [comment]
>That is true, but still all reads from the actor's state is sequential. I ama asking if anyone knows for an elegant way to paralelize the read ops and in that way be able to utilize all CPU threads.

You can have a state that is mutated **only** by a single actor but can be read by anyone.
But in that case, you should ensure that readers can see only a consistent state. For that, you can use any technique you find appropriate: rw-lock, copy-on-write, left-right synchronization or even nothing (e.g. in case of trivial state such as counter).

I agree with Zach, actors is just one more tool in your toolbox. You can use it if it suits your needs, mix it with other tools or bend "rules" ("best practices", w/e) if you have to.
