### ISSUE TITLE
How to lounch on at least x amounts of threads

### ISSUE THREAD

**Issue by Humberd** [Kotlin/kotlinx.coroutines#1655]
Let's say I need to read 100k files and process every one of them.

My initial idea was that reading the files should be performed asynchronously all the time, since reading from hard drive is the slowest part. In the `loadPdfs()` function I spawn coroutines that read the pdf and emit the content to a `producer`.

```kotlin
    @ExperimentalCoroutinesApi
    suspend fun loadPdfs(paths: List<String>): ReceiveChannel<PDDocumentWrapper> = coroutineScope {
        produce(capacity = paths.size) {
            paths.forEach {
                launch(Dispatchers.IO) {
                    val result = loadPdf(it)
                    send(result)
                }
            }
        }
    }
```

Then as the results start to appear on the channel I would like to process them also asynchronously on computational threads. However not even one `processContent()` function is invoked until all the pdfs are loaded. I think it happens, because processing coroutines are places in the queue after reading pdf coroutines and no thread is able to handle them. 

Is there way to load balance the threads pool? I mean that when something appears on the Channel it should start processing along side loading pdfs and when pdfs stop loading it should apply all the available threads to the processing

```kotlin
loadPdfs(...)
   .consumeAsFlow()
   .collect {
      launch(Dispatchers.Default) {
          processContent(it.content) // this can take some time
      }
   }
```

**Comment by fvasco** [comment]
> Let's say I need to read 100k files

Reading 100k files simultaneously, really?
No "Open Files Limit"?
It should requires some memory.

I suggest you to use async NIO for `loadPdf` and avoid `Dispatchers.IO`.
Otherwise you can use a `Executors.newCachedThreadPool().asCoroutineDispatcher()` but it requires more resources.

> Is there way to load balance the threads pool?

The operating system do that.

**Comment by zach-klippenstein** [comment]
I believe your issue is that `coroutineScope` isn't returning until all child coroutines are complete, which doesn't happen until all of your file reads are done. 

It's unidiomatic and smelly for a function to both be suspending and return a type that expresses asynchrony (e.g. `ReceiveChannel` or `Deferred`), because `suspend` implies "this function will not return until its work is finished" (which is what's happening here), while returning an asynchronous type implies "this function returns immediately with a handle to the work". So in your case, I'd remove the suspend modifier and pass the `CoroutineScope` explicitly. Or better yet, return a `Flow` instead of a channel and then your function doesn't have to care about the scope at all.

**Comment by elizarov** [comment]
As a solution to the original question, I'd recommend using `Flow.flatMapMerge` that can limit the concurrency to the specified `maximumNumberOfConcurrentLoads` limit  in the following way:

```
suspend fun loadPdfs(paths: List<String>) {
    paths.asFlow()
        .flatMapMarge(maximumNumberOfConcurrentLoads) { path ->
            flow<PDDocumentWrapper> { emit(loadPdf(path)) }
        }
        .flowOn(Dispatchers.IO) // <-- do loads on IO
        .onEach { processContent(it.content) }
        .flowOn(Dispatchers.Default) // <-- do processing on Default
        .collect()
}
```

@fvasco Unfortunately, using "async NIO" would not help a lot for files, since it is internally synchronously implemented due to the lack of universal async file IO support by operating systems.
