### ISSUE TITLE
onReceiveOrNul extension convenience

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#1676]
Message from Thibault Seisel in public Slack: https://kotlinlang.slack.com/archives/C1CFAFJSK/p1574860187023800

Since `ReceiveChannel<T>.onReceiveOrNul`l has been deprecated, it is suggested to replace it with the `onReceiveOrNull` extension function.But I find that it's surprisingly hard to use that 
 function: Since there is a member property `onReceiveOrNull` it takes precedence over the extension. Since `onReceiveOrNull` is a function, the block passed as select clause is incorrectly interpreted as an extra lambda parameter. While the following workaround code works:
```
import kotlinx.coroutines.channels.onReceiveOrNull as onReceiveOrNullExt
select {
    channel.onReceiveOrNullExt().invoke { foo ->
        [...]
    }
    anotherChannel.onReceive { bar ->
        [...]
    }
}
```
It is not as convenient as the original Select API. Wouldn't it be better to convert that extension function to an extension property with a different name ?

**Comment by DeedleFake** [comment]
Thank goodness for this issue. I was running around in circles trying to figure out how the heck I was supposed to check if a receive was from a closed channel. All of the docs just use `onReceiveOrNull`, but I can't actually use it because it's marked deprecated. So I tried `onReceiveOrClosed`, since the docs said that that was O.K., too, but that one's marked as only being for internal use in `kotlinx.coroutines`. So I tried the extension function, which was a bit of a pain to find as well, and then that one simply didn't seem to work at all. The compiler kept giving me issues about it not taking any arguments.

At the very least the docs need fixing, and badly. The fact that the most prominent documentation for how to actually handle this is an unanswered, open issue that's been sitting here for just under a year is rather disappointing.
