### ISSUE TITLE
AsynchronousSocketChannel hangs during amplification stress test

### ISSUE THREAD

**Issue by revintec** [Kotlin/kotlinx.coroutines#168]
Hi, I'm not sure whether it's a BUG in kotlinx.coroutines, kotlinx.coroutines-nio, Java AIO, or my OS
kotlinx-coroutines-core 0.19.3; kotlinx-coroutines-nio 0.19.3; Oracle Java 1.8.0_121; Mac OSX 10.10.5

minimal code to reproduce the problem:
```
fun main(args:Array<String>){
    AsynchronousServerSocketChannel.open().use{
        it.bind(InetSocketAddress(6666));while(true)launch(Unconfined){
            val m=ByteBuffer.allocateDirect(4096);it.accept().get().use{
                while(it.aRead(m.clear()as ByteBuffer)>0){
                    m.flip();it.aWrite(m,8,TimeUnit.SECONDS) // ①
                    m.position(0);it.aWrite(m,8,TimeUnit.SECONDS) // ②
                }
            }
        }
    }
}
```
as you can see it's very straightforward, read data from the wire and duplicate it before sending back
I've used this command to stress test it: `yes 11111111111111111111111111111111|nc localhost 6666`
at the beginning it works well and produces output fluently, but very soon it hangs. after some debugging I've identified that this program hangs at either ① or ②, so I added a timeout, and confirmed my thoughts: `Exception in thread "Thread-10" java.nio.channels.InterruptedByTimeoutException`

if I remove ②(i.e. just echo back the data without duplicating them), it works fine. so my questions are:
1) I can reproduce this problem reliably, does anyone else having this problem?
2) is there something wrong with my code, or is there a way around this?

thx in advance

**Comment by revintec** [comment]
![image](https://user-images.githubusercontent.com/8952734/33242652-78b903a0-d313-11e7-99e4-680f05b22567.png)
![image](https://user-images.githubusercontent.com/8952734/33242660-8771cc9c-d313-11e7-835f-4d80fa84fd06.png)

**Comment by elizarov** [comment]
I confirm. It reproduces on my machine (Mac OS, JDK 1.8.0_131), too. From what I can gather, it is a problem somewhere in the bowels on JDK's `sun.nio.ch.UnixAsynchronousSocketChannelImpl`. I've added some debug info and I can see that as soon as the TCP output buffer gets overfull (first write return with < 4096 bytes written), then the second `AsynchronousByteChannel.write` just hangs foreever and never invokes its `CompletionHandler` as explained in its documentation.

**Comment by elizarov** [comment]
Ok. This has nothing to do with async sockets. They are 100% fine. You can reproduce this problem with the following fully synchronous code:

```
fun main(args: Array<String>) {
    ServerSocket(6666).use {
        it.accept().use {
            val ins = it.getInputStream()
            val ous = it.getOutputStream()
            val b = ByteArray(4096)
            while (true) {
                val read = ins.read(b)
                if (read < 0) break
                ous.write(b, 0, read)
                ous.write(b, 0, read)
            }
        }
    }
}
```

and with the same command: `yes 11111111111111111111111111111111|nc localhost 6666`

The problem is that both sender (netcat `nc`) and receiver (your asynchronous or the above synchronous code) are single-threaded. They loop between sending to socket and receiving from socket and they ultimately deadlock. When TPC buffer between them become full in both directions, `nc` just waits on trying to write to the socket, without reading from it, while your stress code also waits on trying to write to the socket, without reading from it.

Instead of netcat you should use an application with separate reader and writer threads for your stress-testing needs. For example, the following code can be used as a drop-in replacement for your command line of `yes 11111111111111111111111111111111|nc localhost 6666`:

```
fun main(args: Array<String>) {
    val socket = Socket("localhost", 6666)
    thread(name = "socket-to-stdout") {
        socket.getInputStream().use { it.copyTo(System.out) }
    }
    thread(name = "data-to-socket") {
        val data = "11111111111111111111111111111111\n".toByteArray()
        socket.getOutputStream().use {
            while (true) {
                it.write(data)
            }
        }
    }
}
```

**Comment by revintec** [comment]
sorry for the false alarm, I thought it may have something to do with nc, because I couldn't believe such a huge BUG can reside in JDK. I've used nc before, didn't recall such problem so I went the other direction. I didn't know how to monitor TCP buffer usage before, I'll try to confirm it.

apologies, thx for your time

**Comment by elizarov** [comment]
No problem.
