### ISSUE TITLE
Reentrant lock

### ISSUE THREAD

**Issue by ilyawaisman** [Kotlin/kotlinx.coroutines#1686]
Is reentrant lock for coroutines on the roadmap? 

I've seen a discussion of it where a problem of coroutine identity was raised (https://github.com/Kotlin/kotlinx.coroutines/issues/965). But couldn't a `Job` in the coroutine context be that identity?

**Comment by ilyawaisman** [comment]
Sample implementation could be like this:
```
import kotlinx.coroutines.Job
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlin.coroutines.coroutineContext

class CoroutineReentrantLock {
    private val mutex = Mutex()
    @Volatile
    private var myJob: Job? = null

    val isLocked
        get() = myJob != null

    suspend fun <R> withLock(action: suspend () -> R): R {
        val currentJob = checkNotNull(coroutineContext[Job]) {
            "Not found Job in current coroutine context, this is not supported"
        }
        if (myJob === currentJob) {
            // myJob is not null only under mutex
            return action()
        } else {
            // if myJob is null take mutex immediately otherwise wait until it becomes free
            mutex.withLock {
                check(myJob == null) { "myJob = $myJob, currentJob = $currentJob" }
                myJob = currentJob
                try {
                    return action()
                } finally {
                    myJob = null
                }
            }
        }
    }
}
```

**Comment by elizarov** [comment]
Coroutines don't have a stable identity and using `Job` as one is not correct since many innocent primitives like `withContext` and `coroutineScope` do introduce a new job without conceptually launching a new coroutine. There are some possible workarounds, but, conceptually, coroutines (unlike threads) are too ephemeral. Any attempt to build a reentrant lock is bound to be fragile in practice. So no --- reentrant lock is not on a roadmap.

**Comment by danielesegato** [comment]
@elizarov I think a reentrant mutex would be possible by allowing entering the lock if a parent scope/context (ancestor) is holding the lock.

Isn't this feasible?

**Comment by fvasco** [comment]
> I think a reentrant mutex would be possible by allowing entering the lock if a parent scope/context (ancestor) is holding the lock

How many child scopes should enter in the same reentrant mutex?

**Comment by danielesegato** [comment]
I don't think it makes sense to have such a a limit.
It's either a child scope or isn't.

The developer is in control of that scope and can write code accordingly.

or maybe I misunderstood your question?

Structured concurrency should allow to release the lock only when all is completed I believe.

**Comment by fvasco** [comment]
I cannot figure a common use case for it that cannot be solved with:

```kotlin
mutex.withLock {
  coroutineScope {
    // launch child coroutines
  }
}
```

**Comment by danielesegato** [comment]
The use case is this:

```kotlin
suspend fun doSomeOperation() {
  mutex.withLock {
    // do stuff
    // call another function
    doSomeOtherOperation()
    // do some other stuff
  }
}

suspend fun doSomeOtherOperation() {
  mutex.withLock {
    // do something
  }
}
```

I know the content of `doSomeOtherOperation()` can be exported as an internal function without the lock and reused but this is possible with `synchronize` keyword without using coroutines because it's a reentrant lock and sometimes you don't wanna split the logic like that for readability.

**Comment by fvasco** [comment]
Hi, @danielesegato,
you should consider that `synchronize` isn't a good basis for comparison because `synchronized` is not re-entrant with *children* threads.
With `synchronized` you should use a Fork+Join tool with an external synchronization, as I [previously](https://github.com/Kotlin/kotlinx.coroutines/issues/1686#issuecomment-700771742) suggested.

Instead, your last example look similar to #1382 where you need to encapsulate functions that access to a resource (inside a `Mutex`).

**Comment by vklidu** [comment]
There is already a nice example of solution from Roman Elizarov here https://elizarov.medium.com/phantom-of-the-coroutine-afc63b03a131

**Comment by ZakTaccardi** [comment]
@elizarov is this still not feasible given your example linked here:

https://github.com/Kotlin/kotlinx.coroutines/issues/1686#issuecomment-777357672

If it's still not feasible, what makes the mutex example you provided unreliable?

**Comment by elizarov** [comment]
It just has too much hassle. Given the rare need it is hard to substantiate adding it.

**Comment by pacher** [comment]
@elizarov I would like to second the question from @ZakTaccardi 
I came across the need of Reentrant lock and trying to solve it on my own ended up with the solution very close to your solution posted here, which is quite reassuring. Except of the order, I did `withLock { withContext(ReentrantMutexContextElement(key)) {...` and I don't know which one is right...

We do understand that it is too much hassle to add it to the library.
But the question was what makes the mutex example you provided unreliable? If I just copy-paste it to my project and use as is, what kind of problems are there which I can not see?

Btw, something is wrong and I can't see code snippets in your blog post on medium both in Firefox and Chrome, so I have to rely on the snippet from @vklidu

**Comment by elizarov** [comment]
There are no problems with the `ReentrantLock` itself. The implementation I wrote should work like a charm. However, I would like to see your experience designing code that uses it. I do suspect that over time you'll reconsider it in favor of a different approach that does not require any kind of reentrant lock at all.

**Comment by pacher** [comment]
@elizarov Thanks for reply!


> The implementation I wrote should work like a charm.

Glad to hear, unfortunately we can not use it without breaking your copyright since there is no license for this code ;-)


> I do suspect that over time you'll reconsider it in favor of a different approach

Definitely! I suspect that too. It is just after few cycles of designing and redesigning I did not find a better way **yet** and currently happy with the one which requires reentrant lock. But it will evolve with the time.



> However, I would like to see your experience designing code that uses it.

Ok. I am trying to design a simple and convenient DSL for kotlin python interop. (until graal python becomes usable)
Like in the case of GUI libraries, all python related manipulations need to happen on the same Thread.
This is where coroutines and `newSingleThreadContext` comes in.

Currently it looks like this:
```kotlin
    val python = Python() //instantiate embedded python interpreter
    python { //DSL entry
        + "import sys" // operator plus executes provided string of python code in embedded interpreter, suspending while doing so
        + "print('Using Python version:', sys.version)"

        "x" `=` 42 // we can set and get variables in python

        //we can call functions
        val greeting = "Hello from Python!" //kotlin variable
        "print"(greeting) // prints greeting in python, suspends until python is done printing
        
        //we can also do
        val print = "print"
        print(greeting) //Ha! It looks like kotlin but calling python!
    }

```
So far so good. But what about concurrent invocations? Because of suspension points python statements from different blocks will be interleaved, which is bad. We want to execute the lambda "atomically" as a whole, which is exactly the job for a `Mutex`.

The problem comes from another piece of functionality we have.
We can easily make statically typed bindings to python functions, like this:
```kotlin
        val somePythonFunction: suspend (String, Int) -> String = python.callable("somePythonFunction")
```
and then just use it anywhere in the kotlin code `val res: String = somePythonFunction("Hello", 42)`. Under the hood it will switch the context and acquire the mutex lock

But what if somebody will call `somePythonFunction` inside `python { .. }` block? 
Boom! Deadlock.

I am still in the active designing phase, but Reentrant Lock seems like a good fit and works well at the moment.

**Comment by elizarov** [comment]
@pacher 

> Glad to hear, unfortunately we can not use it without breaking your copyright since there is no license for this code ;-)

I've fixed that for you: https://gist.github.com/elizarov/9a48b9709ffd508909d34fab6786acfe

**Comment by ignoramous** [comment]
> There are no problems with the `ReentrantLock` itself. The implementation I wrote should work like a charm. However, I would like to see your experience designing code that uses it. I do suspect that over time you'll reconsider it in favor of a different approach that does not require any kind of reentrant lock at all.

Perhaps dumb move to question the wisdom of the best language designer since Anders Hejlsberg, and yet, here I am:

I feel, for same reasons `runBlocking` helps transition from java-threads over to kotlin-coroutines effortlessly, `mutex.rentrant` makes it easier to translate blocks of `synchronized` code into `suspend`ing functions. And so, imho, it may warrant first-class support from kotlin. May be with `@herebedragons` / `@youarenotdoingcoroutinesright` annotation, if required. Thoughts? Thx.

**Comment by elizarov** [comment]
IMO, not including reentrant mutex into the library so that you have to actually spend some time on copying the implementation of the reentrant mutex into your code and thinking on whether you really need it, works better than any `@herebedragons` annotation would.

**Comment by alamothe** [comment]
Sorry to jump in, but is there an coroutine implementation of `synchronized`/`wait`/`notifyAll`?

Seems like we can use `ReentrantLock` as a replacement for `synchronized`, but how to implement `wait`/`notifyAll`?

**Comment by Nashatyrev** [comment]
@alamothe I've came up with the following `wait/notify/notifyAll` draft implementation (for a simple lock). Of course there is no guarantee it's 100% correct 
 
```kt
interface KLock {

    suspend fun lock()
    fun unlock()

    suspend fun kWait()
    fun kNotify()
    fun kNotifyAll()
}

class KLockImpl : KLock {
    private val mutex = Mutex()
    private val waitMutex = Mutex(true)

    override suspend fun lock() {
        mutex.lock()
    }

    override fun unlock() {
        mutex.unlock()
    }

    override suspend fun kWait() {
        mutex.unlock()
        try {
            waitMutex.lock()
        } finally {
            mutex.lock()
        }
    }

    @Synchronized
    override fun kNotify() {
        if (waitMutex.isLocked) waitMutex.unlock()
        waitMutex.tryLock()
    }

    @Synchronized
    override fun kNotifyAll() {
        while (waitMutex.isLocked) waitMutex.unlock()
        waitMutex.tryLock()
    }
}
```

**Comment by Szczypiorek44** [comment]
> IMO, not including reentrant mutex into the library so that you have to actually spend some time on copying the implementation of the reentrant mutex into your code and thinking on whether you really need it, works better than any `@herebedragons` annotation would.

Totally agreed. I just wanted to copy the implementation, but after giving it more thought I modified my code so I don't need to use `Reentrant Lock` and simple `Mutex` satisfies my needs.
Thanks

**Comment by magicghostVu** [comment]
> There is already a nice example of solution from Roman Elizarov here https://elizarov.medium.com/phantom-of-the-coroutine-afc63b03a131
> 
> ```kotlin
> suspend fun <T> Mutex.withReentrantLock(block: suspend () -> T): T {
>   val key = ReentrantMutexContextKey(this)
>   // call block directly when this mutex is already locked in the context
>   if (coroutineContext[key] != null) return block()
>   // otherwise add it to the context and lock the mutex
>   return withContext(ReentrantMutexContextElement(key)) {
>     withLock { block() }
>   }
> }
> 
> class ReentrantMutexContextElement(
>   override val key: ReentrantMutexContextKey
> ) : CoroutineContext.Element
> 
> data class ReentrantMutexContextKey(
>   val mutex: Mutex
> ) : CoroutineContext.Key<ReentrantMutexContextElement>
> ```

This solution will work for normal case but if I run coroutineScope inside block and launch some child coroutine, these coroutines will run concurrently, the mutex does not protect critical section any more, be careful with this case
