### ISSUE TITLE
asyncGenerate + extensions

### ISSUE THREAD

**Issue by soywiz** [Kotlin/kotlinx.coroutines#18]
Is there an implementation of asyncGenerate from here? https://github.com/Kotlin/kotlin-coroutines/blob/master/examples/asyncGenerate.kt

Also I would propose adding some extension methods to functionally handle it:

```
inline suspend fun <T, T2> AsyncSequence<T>.map(crossinline transform: (T) -> T2) = asyncGenerate<T2> {
	for (e in this@map) {
		yield(transform(e))
	}
}

inline  suspend fun <T> AsyncSequence<T>.filter(crossinline filter: (T) -> Boolean) = asyncGenerate<T> {
	for (e in this@filter) {
		if (filter(e)) yield(e)
	}
}

suspend fun <T> AsyncSequence<T>.chunks(count: Int) = asyncGenerate<List<T>> {
	val chunk = arrayListOf<T>()

	for (e in this@chunks) {
		chunk += e
		if (chunk.size > count) {
			yield(chunk.toList())
			chunk.clear()
		}
	}

	if (chunk.size > 0) {
		yield(chunk.toList())
	}
}

suspend fun <T> AsyncSequence<T>.toList(): List<T> = await(async {
	val out = arrayListOf<T>()
	for (e in this@toList) out += e
	out
})
```

**Comment by elizarov** [comment]
There is now. Use `buildChannel` instead of `asyncGenerate` with `send` instead of `yield`. More details here: https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#channels
It is better that the prototype `asyncGenerate` from design document, as it supports sending values from multiple coroutines and supports atomic cancellation on both sending and receiving sides.
