### ISSUE TITLE
Integration with Firebase for Android PR was lost?

### ISSUE THREAD

**Issue by dzastinas** [Kotlin/kotlinx.coroutines#1802]
@qwwdfsad I can see Integration with Firebase for Android #426 PR was accepted

![image](https://user-images.githubusercontent.com/13061345/74423268-a5902f80-4e58-11ea-8a51-2bc83df2af90.png)

But it was not added to develop ?

FirebaseFirestore [integration](https://firebase.google.com/docs/firestore/quickstart) was added, but FirebaseDatabase [integration](https://firebase.google.com/docs/database/android/read-and-write)  was left out?

[kotlinx-coroutines-firebase-android](https://github.com/Kotlin/kotlinx.coroutines/tree/867abb3741d2aa716a10bf22c13c7052915b3fb2/integration)

**Comment by qwwdfsad** [comment]
As it was explained by @SUPERCILEX, there wasn't any "stream of values" primitive in coroutines at that moment and that Tasks API is used for all new Firebase/Play Services APIs that don't continuously update values, thus only part related to tasks was merged.

Currently, with the `Flow`, it is possible to integrate with Firebase even better, though maybe it's worth to ask Firebase folks to do so

**Comment by SUPERCILEX** [comment]
Correct, and I don't believe JetBrains should be the one to maintain integrations with specific libraries. The `play-tasks` API makes sense because it's a general purpose async API used across dozens of libraries.

PS: Firestore flow APIs are already gaining momentum from the community and I would assume the RTDB will follow: https://github.com/firebase/firebase-android-sdk/issues/1251, https://github.com/firebase/firebase-android-sdk/pull/1252.
