### ISSUE TITLE
withContext isn't cancelled

### ISSUE THREAD

**Issue by BulatMukhutdin** [Kotlin/kotlinx.coroutines#1823]
In next snippet of code
```
fun main() = runBlocking {
    val job = launch {
        println("Start")

        withContext(Job()) {
            println("Inside with context")
            delay(1000)
            println("Should or shouldn't be called?")
        }
    }

    delay(200)

    job.cancelAndJoin()

    println("Done")
}
```
Is it desired behavior that withContext isn't cancelled or is it a bug?

**Comment by RBusarow** [comment]
You're creating a new `Job` here.  That isn't tied to the structured concurrency of it outer `Job`.

This is specifically recommended against.  Its behavior is expected but probably not desired.

**Comment by BulatMukhutdin** [comment]
1) In documentation it is said that since coroutines are supporting cooperative concurrency all child coroutines would be cancelled as soon as their parent is cancelled. The only exception is GlobalScope. So it seems that in the case above it should be cancelled.
2) If replace withContext with launch then child coroutine would be cancelled. Seems inconsistent

**Comment by BobBenBan** [comment]
When you specify `Job()` explicitly in `withContext`, it creates a new job with _no parent_; as opposed to inheriting the job from the outer `launch`; so cancelling the `launch` job no longer cancels the `withContext` job; this is expected behavior. Change the context argument given to `withContext` with something else and it will cancel normally.
