### ISSUE TITLE
Emissions from onCompleted ignored on cancellation

### ISSUE THREAD

**Issue by kyiv-pride-code** [Kotlin/kotlinx.coroutines#1990]
Consider the following code:
```Kotlin
runBlocking {
    val flow = flow {
        for (i in 1..100) {
            delay(10)
            emit(i.toString())
        }
    }
    val job = launch {
        flow.onCompletion { emit("completed") }
                .collect { println(it) }
    }
    delay(500)
    job.cancelAndJoin()
}
```
In this case "completed" is never printed.
According to documentation, the `onCompletion` block should be equivalent to a `finally` block.
But if I change the code in `launch` to the following:
```Kotlin
flow {
    try {
        emitAll(flow)
    } finally {
        emit("completed")
    }
}.collect { println(it) }
```
"completed" is printed.
How can one emit an additional value on cancellation in a declarative manner?

**Comment by elizarov** [comment]
In general, once the flow is cancelled it cannot and should not emit anything. There is no way to emit after cancellation. Cancellation means that all the operations should be terminating promptly. 

However, cancellation is cooperative and cancellation status is not being checked all the time (mostly for performance reasons), so the example with emission from `finally` is a curious corner-case here. It should not be allowed and it will not work if, for example, you put something like `flowOn` between the `flow  {...}` and `collect` (try it!). We'll see if we can somehow reliably plug this hole so that emission from the `finally` does not work consistently just like it does not work from `onCompletion`.

**Comment by qwwdfsad** [comment]
Please update to kotlinx.coroutines `1.3.5`.

After 1.3.5, we've started to enforce exception transparency, so e.g. the following example:
```
 flow {
    try {
        emitAll((1..100).asFlow())
    } finally {
        emit("completed")
    }
}.flowOn(Dispatchers.IO).take(5).collect { println(it) }
```

will fail with 
`Flow exception transparency is violated:
    Previous 'emit' call has thrown exception kotlinx.coroutines.flow.internal.AbortFlowException: Flow was aborted, no more elements needed, but then emission attempt of value 'completed' has been detected.
    Emissions from 'catch' blocks are prohibited in order to avoid unspecified behaviour, 'Flow.catch' operator can be used instead.
    For a more detailed explanation, please refer to Flow documentation.`
