### ISSUE TITLE
How can I forward a send channel of one type to another?

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#1991]
I’m wrapping an `actor` of one type with another, but struggling to forward the `SendChannel#selectClause` effectively.

Ultimately my goal is to create a enhanced API around an `actor` for building state and exposing its `Flow<State>`.  Something like:

```
val actor: SendChannel<Intention> = stateActor(..)
```
How can I implement the following?

```kotlin
private val _onSend: SelectClause2<StateActorIntention<S, I>, SendChannel<StateActorIntention<S, I>>> = actor.onSend
 // how do I forward onSend to `_onSend` without using `@InternalCoroutinesApi`?
override val onSend: SelectClause2<I, SendChannel<I>> get() = TODO("??")
```

The other functions on `SendChannel<T>` were easy to forward.

See a [full gist](https://gist.github.com/ZakTaccardi/64e7e70fb75ea5cba48a3797d75e6fe4)

**Comment by elizarov** [comment]
You cannot. You have to opt-in into `@InternalCoroutinesApi`. The reason is that channels are not stable for extension in 3rd party code (but are stable for use in 3rd party code). The reason for that, in turn, is that we plan to tweak this part of their internal API in the future.

Instead of trying to forward them, you can just expose `channel: SendChannel` property from your actor. It will be a bit more verbose to use, but avoids having to rely on internal APIs.

Does it help?

**Comment by ZakTaccardi** [comment]
I’ll probably just expose `suspend fun send(..)` and `fun offer(..)` functions, as I don’t use the rest of the functionality of a `SendChannel<T>`.

Thanks!
