### ISSUE TITLE
should close a channel for infinite sequence of elements?

### ISSUE THREAD

**Issue by ryukato** [Kotlin/kotlinx.coroutines#2105]
Hi 
I appreciate if you let me know that proper way to handle a channel.

We're using a channel to receive mesages from kafka by using reactor-kafka, and I think the channel is for `infinite sequence of elements` that the message from the kafka like below.

```
private val channel = kafkaReceiver.receive().asFlow().produceIn(GlobalScope)
...

GlobalScope.launch {
  for (record in channel) {
    ...
  }
}
```
Should the channel be closed before the application whose the receiver is shutdown? or it will be disposed automatically?

**Comment by zach-klippenstein** [comment]
If by "shutdown" you mean the process is about to die, then there's no need to close the channel - channels exist entirely in userspace.

**Comment by elizarov** [comment]
Channel will be disposed by the garbage collector when there are remaining references to it. However, because you run a new coroutine in the `GlobalScope`, this coroutine will be running forever (while JVM is active) and will keep a reference to this channel. There are two primary ways to cancel it:

1. Call `channel.cancel()` when you don't need it anymore. This will cancel the producing coroutine.
2. Use a scope that is tied to the lifecycle of the corresponding app component:

```
val scope = CoroutineScope(Dispatchers.Default)
val channel = ....produceIn(scope)
// whenr you data-producing component closes
scope.cancel()
```

Does it help?

**Comment by ryukato** [comment]
I appreciate for your detail comments, it helps me a lot.
