### ISSUE TITLE
Blocking calls wait indefinitely when preceded by non blocking call

### ISSUE THREAD

**Issue by jnels124** [Kotlin/kotlinx.coroutines#2110]
It seems that you can't execute a webclient call in a runBlocking scope after you have executed a suspendable webclient call.

I have provided a minimal example below.

kotlinx-coroutines-reactive:1.3.6

```
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.runBlocking
import org.springframework.http.MediaType
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.reactive.function.client.WebClient
import org.springframework.web.reactive.function.client.awaitBody

@RestController
@RequestMapping("/bug")
class CoRoutineBug(webClientBuilder: WebClient.Builder) {
  val webClient = webClientBuilder.baseUrl("https://httpbin.org/get").build()

  @GetMapping("neverreturns")
  suspend fun testbroken(): String {
    val asyncResponse = getAsync()
    print("The async response is $asyncResponse")

    val blocking = getBlocking()
    print("The blocking response is $blocking")

    return blocking;
  }
  
  @GetMapping("works")
  suspend fun testworks(): String {
    val blocking = getBlocking()
    print("The blocking response is $blocking")

    val asyncResponse = getAsync()
    print("The async response is $asyncResponse")

    return blocking;
  }

  suspend fun getAsync(): String {
    return webClient.get().accept(MediaType.APPLICATION_JSON).exchange().awaitSingle().awaitBody()
  }

  fun getBlocking(): String {
    return runBlocking {
      getAsync()
    }
  }
}
```

**Comment by elizarov** [comment]
In general you cannot _block_ you request threads in a Spring WebFlux application. The reason it works in one case and does not work in the other is purely accidental. In "neverreturns" case you first perform an async call to "httpbin.org" and thus the coroutine resumes in the corresponding netty engine thread that handles this particular connection to "httpbin.org". Now, calling `runBlocking` after than you've blocked this thread and thus you cannot perform any more requests this server, since the corresponding thread is blocked. 

The general solution is to never block your request threads. If you really need to perform any kind of blocking operation, then do it from inside of `withContext(Dispatchers.IO) { ... }`. If you wrap your `getBlocking()` call into `withContext(Dispatchers.IO) { ... }` then it works in both cases.

Does it help?

**Comment by jnels124** [comment]
`withContext(Dispatchers.IO) { ... }` resolved the issue. thanks @elizarov
