### ISSUE TITLE
why this scene need wait?

### ISSUE THREAD

**Issue by Palardin3** [Kotlin/kotlinx.coroutines#2143]
```
 @JvmStatic
    fun main(args: Array<String>) = runBlocking {
        val result = listOf(1, 2, 3, 4).map {
            flow {
                emit(deal(it, System.currentTimeMillis()).also {
                    println("emit " + "  time coast " + (System.currentTimeMillis() - it))
                })
            }.flowOn(Dispatchers.IO)
        }.merge().buffer(4)

        result.first().also {
            println("collect result" + "   " + (System.currentTimeMillis() - it))
        }
        println("end")
    }

    fun deal(value: Int, time: Long): Long {
        println("FLOW " + Thread.currentThread().name)
        sleep(value * 1000L)
        return time
    }
```
why received result need all flows emit finished?

**Comment by elizarov** [comment]
What you were trying to achieve? What were you expecting to get? What is `merge()` doing?

**Comment by Palardin3** [comment]
The merge() is extension func in v1.3.6 :
```
public fun <T> Iterable<Flow<T>>.merge(): Flow<T> {
     return ChannelLimitedFlowMerge(this)
}
```
these flows means net or local data request, I want get first return result . but I got result until all flows emit finished. 

logs：
```
FLOW DefaultDispatcher-worker-3
FLOW DefaultDispatcher-worker-2
FLOW DefaultDispatcher-worker-4
FLOW DefaultDispatcher-worker-1
emit 1594979057185   time coast 1001
emit 1594979057185   time coast 2004
emit 1594979057185   time coast 3001
emit 1594979057185   time coast 4001
collect result   4002
end
```
i think is should be:
```
FLOW DefaultDispatcher-worker-3
FLOW DefaultDispatcher-worker-2
FLOW DefaultDispatcher-worker-4
FLOW DefaultDispatcher-worker-1
emit 1594979057185   time coast 1001
collect result   1002
end
```

**Comment by elizarov** [comment]
Thanks. You are using `Thread.sleep` here, which is non-cancellable. The `Flow.first()` terminal operator waits for all merged coroutines to complete, but `sleep` cannot be canceled, so it has to be wanted for. There are two possible solutions:
1. Replace `sleep` with `delay`
2. Wrap `sleep` into `runInterruptible { ... }`

Does it help?

**Comment by Palardin3** [comment]
Yeah ,it works. but `Thread.sleep` is to simulate IO operations. it should be a common scenario.
How can I use flow.first in concurrent scenarios?

**Comment by yihuaqi** [comment]
> Thanks. You are using `Thread.sleep` here, which is non-cancellable. The `Flow.first()` terminal operator waits for all merged coroutines to complete, but `sleep` cannot be canceled, so it has to be wanted for. There are two possible solutions:
> 
> 1. Replace `sleep` with `delay`
> 2. Wrap `sleep` into `runInterruptible { ... }`
> 
> Does it help?

I have a similar use case where I start several network requests simultaneously, and take the first successful request and then proceed.

My first attempt is to create a list of `async`, and apply `select/onAwait` clause. However `select` cannot return the first **successful** result, it returns regardless of whether it's successful or not.

Then I try to wrap network requests into multiple `Flow`s, and call `merge().first()` on the `Flow`s. I understand that for most Flow terminal operator it's necessary to wait for all merged coroutines to complete, otherwise the flow would be incomplete. But for `first()` I think it's an exception. Since no matter what happens to the other unfinished coroutines, the result is determined and won't change once any `emit()` is invoked, and thus there's no need to wait.

Do you have any suggestion for this use case?

**Comment by elizarov** [comment]
You need to make sure that your IO is concealable. You can just take the result of your first IO operation and leave the others working behind. That creates resource leaks in your application.
