### ISSUE TITLE
1.3.9 core-native and core-common missing from Maven Central/Bintray

### ISSUE THREAD

**Issue by JakeWharton** [Kotlin/kotlinx.coroutines#2198]
I know 1.3.9 hasn't been announced, but based on @qwwdfsad's comment on Slack:

> 1.3.9 will be compatible with Kotlin 1.4.0, ETA is Monday. For now it’s just cooling off in maven central :)

It seems that despite no announcement the bits are meant to be correct but unfortunately are not.

**Comment by qwwdfsad** [comment]
It would be nice if you could elaborate on what exactly is wrong.

Indeed, `-common` and `-native` artifacts are missing, but this is expected: in Kotlin 1.4 we've transitioned to a new HMPP scheme. Now we have a single `kotlinx-corotines-core` artifact and corresponding metadata to resolve all platform-specific variants.

Meaning that now, instead of:
```
sourceSets {
  commonMain {
    dependencies {
      api "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:..."
    }
  }

  jvmMain {
   // ... same but no suffix
  }
  
   nativeMain {
     // same but -native suffix
   }
}
```

You can write
```
sourceSets {
  commonMain {
    dependencies {
      api "org.jetbrains.kotlinx:kotlinx-coroutines-core:..."
    }
}
```

and that's it! Also, you can use `-core` artifact in JVM only or native-only project and everything will be resolved properly as well.

**Comment by JakeWharton** [comment]
Ah, I see. Thanks!

I merely bumped the version and had projects fail to find those artifacts. The search makes it seem like them missing is the problem. With no tag or release notes I didn't have anywhere to turn to know of this change (which is very welcome!).

Hopefully others experiencing this failure will find either this issue or the release notes when they land.

**Comment by qwwdfsad** [comment]
>With no tag or release notes I didn't have anywhere to turn to know of this change (which is very welcome!)

Yeah, that's why there is no announce yet. We'll ship everything along with Kotlin 1.4
