### ISSUE TITLE
Upgraded Kotlin version behind a patch bump

### ISSUE THREAD

**Issue by Nycto** [Kotlin/kotlinx.coroutines#2219]
It looks like version 1.3.9 upgrades to Kotlin 1.4 behind a patch version bump. This seems like a large enough change that it at least warrants a minor version bump change. Was this intentional?

**Comment by elizarov** [comment]
Yes. It was intentional, since Kotlin stdlib 1.4.0 is backwards binary compatible with kotlin stdlin 1.3.x and there is no good reason to bump to the version of the coroutines library, since it does not contain any major changes by itself to warrant. However, we do unrestand the concern in that respect and are looking at what we can do in this situation.

**Comment by Marc1510** [comment]
I'm currently using 1.3.8 for both Android & iOS (as the common module hasn't been updated to 1.3.9) however as it is a pre-1.4 library I'm getting this error:
`w: Skipping "/Users/{}/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-iosx64/1.3.8/ae0fe1eadbb7ba9fcc427209376a4a2f1e019f29/kotlinx-coroutines-core.klib" as it is a pre 1.4 library
e: Could not find "/Users/{}/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-iosx64/1.3.8/ae0fe1eadbb7ba9fcc427209376a4a2f1e019f29/kotlinx-coroutines-core.klib" in [/Users/{}/Documents/Triple/Projects/iOS/Brabant/Pods, /Users/{}/.konan/klib, /Users/{}/.konan/kotlin-native-prebuilt-macos-1.4/klib/common, /Users/{}/.konan/kotlin-native-prebuilt-macos-1.4/klib/platform/ios_x64].
`

Before I got this also with some other libraries which have updated their core kotlin version to 1.4.0. Would there be a possibility to do this as well?
