### ISSUE TITLE
Wrong / Incomplete Stacktrace

### ISSUE THREAD

**Issue by andreimesina** [Kotlin/kotlinx.coroutines#2228]
Hello, having the example below:

```
fun launchOnScope(block: suspend CoroutineScope.() -> Unit): Job = 
    myScope.launch {
        block.invoke(this)
    }

class MyViewModel : ViewModel() {

    fun throwFromCoroutine() {
        launchOnScope {
            throw RuntimeException()
        }
    }

    fun throwFromFlow() {
        launchOnScope {
            myFlow.collect {
                throw RuntimeException()
            }
        }
    }
}
```

Where `launchOnScope` is a utility method to launch a suspending block of code in a custom `CoroutineScope`;
`throwFromCoroutine` and `throwFromFlow` are 2 methods of the ViewModel that could be called at some point.

The problem arises when these 2 methods are throwing an exception, because:

- When `throwFromCoroutine` throws, the most relevant stacktrace I get is to `MyViewModel`'s last line (which is a brace `}`)
- When `throwFromFlow` throws, the most relevant stacktrace I get is `at MyViewModel$throwFromFlow$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:137)` (which is part of `kotlinx.coroutines.flow` library)

Could you explain why we cannot see the calling site where the exception has been thrown in these 2 cases and how could we improve that? 
Thanks!

`kotlinVersion = 1.3.71`
`coroutinesVersion = 1.3.5`

**Comment by qwwdfsad** [comment]
Hi, this is due to how coroutines are implemented in the compiler and the fact that `throwFromCoroutine` throws an exception immediately, while `MyViewModel$throwFromCoroutine$1` is still part of the real stracktrace.

`throwFromFlow` does not throw an exception immediately, but first suspends in flow collecting, temporary "erasing" its caller from the stacktrace.

The simplest workaround I can suggest is to use [stracktrace recovery](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md#debug-mode) and slightly change flow call:
```
fun throwFromFlow() {
    launchOnScope {
        coroutineScope {
            myFlow.collect {
                throw RuntimeException()
            }
        }
    }
}
```

Now exception will cross coroutine boundary (`coroutineScope` builder) and kotlinx.coroutines machinery will enhance stracktrace with additional stackframes

**Comment by andreimesina** [comment]
Hey, thanks for the suggestion, I came around that sort of solution while debugging.

Maybe a bit off-topic on this issue, but one more thing my team and I were curious about was how costly is it creating that extra scope through the `coroutineScope` builder? 
Also, in some other situation we were working around the case where we would have to create a couple (2-3) of new scopes through `CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)` during a `ViewModel`'s lifetime. We were wondering as well about the performance hit our app would take by creating those scopes and then cancelling them later at some point. 
What would be your opinion on this topic?

**Comment by qwwdfsad** [comment]
I'd say it's pretty cheap (actually, allocation of two small objects) and can be used freely.

In general, it's unlikely that in any real-world application creation of `CoroutineScope` would be a real bottleneck that significantly contributes to application performance. Even in Ktor we've never stumbled on coroutine scope allocations.
