### ISSUE TITLE
Exception swallowed by async/await in test

### ISSUE THREAD

**Issue by edenman** [Kotlin/kotlinx.coroutines#2282]
I'm using the following function to kick work to a background thread in my production app:
```
// Adapted from https://github.com/Kotlin/kotlinx.coroutines/issues/1147#issuecomment-639397185
fun <T, R> Flow<T>.mapOnThread(thread: CoroutineScope, transform: suspend (T) -> R): Flow<R> {
  return this
    .map { input -> thread.async { transform(input) } }
    .map { deferred -> deferred.await() }
}
```
It works great.  I'm using it like this:
```
class FooProvider {
  private val fooFlow = MutableStateFlow<List<Foo>>(listOf())

  fun onClick() {
    val existing = fooFlow.value
    fooFlow.value = existing.toMutableList().plus(Foo("omg${existing.size}"))
  }

  fun observe(coroutineScope: CoroutineScope): Flow<String> {
    return fooFlow.mapOnThread(coroutineScope) { list ->
      try {
        return@mapOnThread list[-1].toString()
      } catch (e: Throwable) {
        throw e
      }
    }
  }
}
```
But wait, there's a bug in my `observe` method: I'm accessing an invalid index, so that `mapOnThread` transform block throws an exception.  I tried to write a test:
```
class FooProviderTest {
  @Test
  fun foo() {
    val fooProvider = FooProvider()
    runBlockingTest {
      val states = mutableListOf<String>()
      val stateSubscription = launch {
        val scope = CoroutineScope(Dispatchers.Unconfined)
        fooProvider.observe(scope)
          .collect { state ->
            states.add(state)
          }
      }
      assertEquals(1, states.size)
      assertEquals("", states[0])
      stateSubscription.cancel()
    }
  }
}
```
Rather than throwing the exception, the test just fails when I try to assert that `states` has size == 1.  

Am I doing something wrong here?  Maybe something between runBlockingTest and Dispatchers.Unconfined is causing this to get dropped?

Full test project: https://github.com/edenman/kmpPlayground/tree/72f487d56ae498d94bca6cd0c3bc4143d3f8f23c

**Comment by gildor** [comment]
It's expected, it's an exception on background thread, not on thread where you run you test, it's the same with threads:

```
@Test
fun failedThread() {
    var a = 0
    thread {
        error("Failed!")
        a++
    }
    Thread.sleep(100)
    assertEquals(1, 0)
}
```

To properly write test for this case, you should propagate exception from the background. And now your code doesn't follow structured concurrency so doesn't propagate exceptions

**Comment by dkhalanskyjb** [comment]
@gildor is right: if you remove the assertions, the test will still fail, but with this:
```
    java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index -1.                                                                                                       
```
So, the code does fail as needed, the problem is, the assertions take priority here.

Also note that `runBlockingTest` has some additional properties of its own. If you replace `runBlockingTest` with `runBlocking`, the behavior will be slightly different: then, it will be enough to insert a large enough delay before the assertions, and you will observe the exception due to incorrect indexing before the assertions are run. So, the exception is not being swallowed here.

Also, your code would not pass this test even if there was no bug in the `observe` method, as, as @gildor correctly identified, sometimes (very often) `assertEquals(1, states.size)` will execute before `states.add(state)` would execute, so this assertion will crash even with a correct `observe` and a suitable `fooFlow`.
