### ISSUE TITLE
Get rid of backspace symbol in artificial stackframe for stacktrace recovery

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#2291]
For the sake of IDE-friendliness, we are using backspace symbol `\b` in our [stacktrace recovery](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md#stacktrace-recovery) machinery.

This trick is helpful to render a `StackTraceElement` as a raw string without line-numbers and parentheses that are obligatory for `StackTraceElement.toString` implementation.

While initially it was an acceptable solution, time moves on and debug mode is now frequently used in production environments, even by IntelliJ IDEA and its derivatives. 
For that, `\b` solution is no longer desirable: it clutters log files, obfuscates programmatic exception handling and even triggers crashes of third-party tools that do not escape special symbols (that have to be escaped) in exception frames.

### Solution

The solution is to get rid of `\b`, introduce properly documented artificial function to `kotlinx.coroutines` and make intermediate stackframe reference this function instead.
While it may be inconvenient for first-time users, it should be okay to once navigate to it in IDEA or to read its documentation to get used to it.

### Known issues

https://github.com/Flank/flank/issues/764
https://youtrack.jetbrains.com/issue/RIDER-52026

**Comment by dkhalanskyjb** [comment]
It turns out that the coroutine debugger in IDEA would be slightly broken were we to release this change: https://github.com/Kotlin/kotlinx.coroutines/pull/2694#issuecomment-838341384. Because of this, we will revert https://github.com/Kotlin/kotlinx.coroutines/pull/2695 for the 1.5 release.

After the coroutine debugger is modified to accommodate such a change, we will need to wait for long enough to ensure that the supported versions of the Kotlin plugin are not affected by this. Then, we will be able to safely introduce the change.

**Comment by qwwdfsad** [comment]
Here are the commits:

https://github.com/JetBrains/intellij-community/commit/fd29488cce387808d564d1e3c2ed830c7724c22f
https://jetbrains.team/p/ij/repositories/intellij/revision/657936acb69fbbc59a88e1b7e799f49e81d9f162

They cover all supported IDEA versions, so it's good to go.
