### ISSUE TITLE
ObservableSource.asFlow() extension should at least surround sendBlocking() call with try/catch block

### ISSUE THREAD

**Issue by mhernand40** [Kotlin/kotlinx.coroutines#2299]
I work out of an Android code base that is mostly Rx-based. However, we have started writing new code using Coroutines. The `kotlinx-coroutines-rx2` library is crucial for interfacing between the two libraries. However, `ObservableSource.asFlow()` has proven to be dangerous and has introduced crashes for us in production.

Please see https://github.com/Kotlin/kotlinx.coroutines/issues/2104. I have shared several stack traces in that issue we have been seeing. The root cause seems to correspond with https://github.com/Kotlin/kotlinx.coroutines/issues/974. However, it seems that effort is going to take some careful redesign. In the meantime, can we consider wrapping the call to `sendBlocking()` with a `try/catch` block? I'm thinking the `catch` block can specifically catch `CancellationException` or the appropriate subtypes, e.g., `JobCancellationException` and `ChildCancelledException` to avoid catching all `Exceptions`.

**Comment by drinkthestars** [comment]
This issue would also exist in `kotlinx-coroutines-rx3/RxConvert` because of the same `callbackFlow` + `sendBlocking` structure:
https://github.com/Kotlin/kotlinx.coroutines/blob/1b34e1c7dd6207d7683c307bae0b934a3dc18d09/reactive/kotlinx-coroutines-rx3/src/RxConvert.kt#L78-L90

These implementations don't adhere to the `callbackFlow` documentation example that surrounds `try/catch` w/ `sendBlocking`:
https://github.com/Kotlin/kotlinx.coroutines/blob/1b34e1c7dd6207d7683c307bae0b934a3dc18d09/kotlinx-coroutines-core/common/src/flow/Builders.kt#L302-L310

If only to avoid repeating code with `try/catch` in both places, we might even need something like this ([insp.](https://github.com/Kotlin/kotlinx.coroutines/issues/974#issue-407591087)):
``` Kotlin
fun <E> SendChannel<E>.safeSendBlocking/sendBlockingCatching(value: E) {
    return runCatching { sendBlocking(value) }
}

// OR
fun <E> SendChannel<E>.safeSendBlocking/sendBlockingCatching(value: E) {
    return try {
        sendBlocking(value)
    } catch (ex: ClosedSendChannelException) { // or other exceptions
        // ...
    }
}
```
