### ISSUE TITLE
Flow<Int>.first() 40x slower than Flow<Int>.single()

### ISSUE THREAD

**Issue by bpeterson3134** [Kotlin/kotlinx.coroutines#2328]
Hi,

I was testing out Flows using fibonacci sequence and came across some code that performed significantly slower than I would have suspected.

```
class ReactiveTest {

    fun fibonacci(n: Int): Flow<Int> =
            flow {
                when {
                    n <= 1 -> emit(n)
                    else -> emit(fibonacci(n - 1).first() + fibonacci(n - 2).first())
                }
            }

    fun fibonacciReactive(numbers: List<Int>): Flow<Int> = flow {
        numbers.forEach {
            when {
                it <= 1 -> emit(it)
                else -> emit(fibonacci(it - 1).first() + fibonacci(it - 2).first())
            }
        }
    }

    @Test
    fun reactive() {
        val test1 = measureTimeMillis {
            runBlocking {


                val result = fibonacciReactive(listOf(10, 15, 30))
                result.collect { value -> println(value) }
            }
        }
        print("reactive=$test1")
    }

}
```

If you replace `.first()` with `.single()` the implementation is significantly faster.  Looking at the descriptions of each, I'm wondering if the cancellation of the flow's collection is what takes so long?

**Comment by qwwdfsad** [comment]
Hi, your hand-rolled benchmark has a few crucial flaws that affect result significantly.

 - Instead of using [dedicated tool](https://github.com/openjdk/jmh), you are using JUnit test. Apart from potential benchmarking pitfalls, in JUnit tests, we (coroutines) automatically enable debug mode that enhances all cancellation exceptions with stacktraces. And stracktrace retrieval is an indeed costly operation.

 - Also, your fibonacci code invokes terminal operator (`first` or `single`) `O(2^n)` times. It means that any relative slowdown between two operators will be multiplied by a significant factor and incorrect conclusions can be drawn.

- Your code performance is _dominated_ by calls to `first` and `single`. While it is okay to measure a relative performance, it doesn't translate well to real code, because real code is mostly dominated by business logic and code withing flow body and/or its operators. Meaning that if `single` is 10% faster than `first`, it doesn't mean that in your real application code, flow processing using `single` will be 10% faster than using `first`

Here is the result of comparison without debug mode for `flowOf(1)`:
```
Benchmark                     Mode  Cnt     Score     Error   Units
FirstSingleBenchmark.first   thrpt    5  3417.552 ± 228.599  ops/ms
FirstSingleBenchmark.single  thrpt    5  3744.305 ± 168.835  ops/ms
```
