### ISSUE TITLE
Should MutableStateFlow.onEach return a MutableStateFlow instead of Flow?

### ISSUE THREAD

**Issue by kevincianfarini** [Kotlin/kotlinx.coroutines#2343]
On Android, handling process death can be done with something called a `SavedStateHandle`. This class allows you to acquire a LiveData from a key which automatically saves new value emissions into the `SavedStateHandle`. 

I want to emulate this functionality with `MuableStateFlow`, and I think the solution could look like this. 

```kotlin
fun <T> SavedStateHandle.getStateFlow(key: String, default: T): MutableStateFlow<T> {
    return MutableStateFlow(this[key] ?: default).onEach {
        this[key] = it
    }
}
``` 

The problem with this approach is that `onEach` returns a regular instance of Flow. After having a discussion of this, I was pointed to #2081 which outlines the complications of offering transformation functions on a StateFlow.

I'm wondering if the same limitations apply when not using a transformation function, and instead using a side effect function like `onEach`.

**Comment by elizarov** [comment]
This approach has the same problem as well as so many other problems that I don't even know which one to start with. 

The most straightforward problem here is that it would call `onEach` as many times as there are subscribers and older values that are being consumers by slow subscribers could easily overwrite newer values. Instead of doing something like that you should follow the principle of "single source of truth". Encapsulate all your `MutableStateFlow` instances in a class and don't expose them outside. Expose only functions that perform modifications to the state, so that those functions update the corresponding flows and also save the data to wherever else you need to. Hope it helps.
