### ISSUE TITLE
Lazily shareIn + RxJava results in Dispatcher oddity

### ISSUE THREAD

**Issue by dlew** [Kotlin/kotlinx.coroutines#2361]
I'm not sure if this is an issue, but an odd behavior thing I noticed that I can't figure out.

If you're using `asObservable()` to convert a `Flow` to an RxJava `Observable`, it typically uses the unconfined Dispatcher, which results in just using the current thread (unless you're applying any dispatcher/scheduler operators).

However, with `shareIn()` + `SharingStarted.Lazily`, it results in using a different thread:

```
flowOf(1)
    .shareIn(
        scope = scope,
        started = SharingStarted.Lazily,
        replay = 1
    )
    .asObservable()
    .subscribe {
      println(Thread.currentThread().name)
      // Prints: DefaultDispatcher-worker-1 @coroutine#2
    }
```

If you use a `SharingStarted.Eagerly` then it goes back to using `main` in subscribe. That seems vaguely reasonable given that `Lazily` needs to wait before subscribing, but what's confusing to me is that if you explicitly call `flowOn(Dispatchers.Unconfined)` before `shareIn()`, then the behavior goes back to what I would expect: using the `main` thread in the subscribe:

```
flowOf(1)
    .flowOn(Dispatchers.Unconfined)
    .shareIn(
        scope = scope,
        started = SharingStarted.Lazily,
        replay = 1
    )
    .asObservable()
    .subscribe {
      println(Thread.currentThread().name)
      // Prints: main @coroutine#2
    }

Is this dispatcher behavior expected or unintended?

**Comment by elizarov** [comment]
That's pretty expected behavior:

*  `shareIn` has a scope (with a dispatcher) that you pass as it first parameter and, by defeault, this scope is applied to all the preceding operators. I assume that in your example `scope` has `Dispatcher.Default` which is used.
* `asObserable()` operator, by default, is unconfined. So it simply works in the same context as upstream. You can override this by passible a context parameter to `asObservable` if you want.

That explains the behavior of the first example.

In the second example, you apply `flowOn(Dispatchers.Unconfined)` operator between `flowOf` and `shareIn`. The makes all the emissions to be unconfined. However, even though the `shareIn` operator has a context, the `SharedFlow` itself does not have a context per se, so the emission context "leaks" though shared flow to the downstream. You never notice this with flow, since Flow-collecting operators guarantee the context preservation, but with `asObservable()` (which is Unfonfined!) you actually get affected by the emission context (you see it in the name of the thread). 

P.S. You can always confine your observable to a specific context by passing it as a parameter to `asObservable()`.

Does it help?

**Comment by dlew** [comment]
Ah, what I was missing was that the `scope` was using the default dispatcher. If I specify that `scope` use `Dispatchers.Unconfined` then it works as I expected (without `flowOn()`). Thanks!
