### ISSUE TITLE
Non-daemon threads in Dispatchers.Default/IO

### ISSUE THREAD

**Issue by agcom** [Kotlin/kotlinx.coroutines#2535]
**`Dispatchers.Default`** is just at-hand and I guess it's more efficient than using Java executors (?). And I feel guilty when I block the `main` thread to avoid **termination** of JVM.

So, can we have **non-daemon threads** spawned in `Dispatchers.Default`? Maybe through a configuration system property (like `kotlinx.coroutines.scheduler.daemon`)?

**Comment by elizarov** [comment]
Having such a critical dependence in behavior on a system problem is quite inappropriate. Can you, please, elaborate on what's wrong with blocking the main thread to prevent termination? What kind of application you are writing when you run in such a problem?

**Comment by agcom** [comment]
I was expecting that "just block the main thread and be happy" :smile:.

I write and maintain services (micro-services) for a startup. They all use `Dispatchers.Default` for CPU bound tasks, as the **main pool**. Events (http, nats, ...) come in and are served.

There is nothing wrong with blocking the main thread, but I suppose that it's against **best practices**. The `main` thread is just hanging there, doing nothing but occupying 1MB of memory. And I didn't run into any problem till now (no out of memory exception nor termination problem).

Maybe I shouldn't use `Dispatchers.Default` as the main pool (?); Otherwise, my probably-not-too-much-over-engineering-senses suggest that they should be non-daemon.

**Comment by qwwdfsad** [comment]
Thanks for the report, saving 2MB of memory in small containers is actually an interesting use-case!

Unfortunately, we cannot make our threads non-daemons, because it has way too many implications for a large user base: increased memory pressure, problems with repackaged libraries, inability to terminate the program "normally" without calling `System.exit` and so on. Also, it's non-deterministic: if a third-party library accidentally or conditionally touches our dispatchers (e.g. via `GlobalScope`), the application suddenly starts behaving differently!

All default executors in popular libraries (`ForkJoinPool.commonPool()`, Rx and Reactor schedulers) also follow this guideline. So we are definitely not going to change that behaviour.

For the advanced use-cases like yours, we'll give it a thought via settable thread factory (similar to  `java.util.concurrent.ForkJoinPool.common.threadFactory`), but it's definitely out of our focus right now.

I'd suggest you stick with a blocked main thread instead
