### ISSUE TITLE
get data from room db not work

### ISSUE THREAD

**Issue by Hend123** [Kotlin/kotlinx.coroutines#2536]
package com.example.weatherforecast.Repository

import android.content.Context
import android.util.Log
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import com.example.retrofitandcoroutine.data.remote.Constant
import com.example.retrofitandcoroutine.data.remote.RetrofitClient
import com.example.weatherforecast.data.local.WeatherDatabase
import com.example.weatherforecast.pojo.WeatherModel
import com.example.weatherforecast.pojo.WeatherTable
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class Repo : IRepo {
    private var weatherMutableLiveDataApi: MutableLiveData<WeatherModel>
    private var weatherMutableLiveDataBD: LiveData<List<WeatherTable>>

  //  private lateinit var database: WeatherDatabase

    init {

        this.weatherMutableLiveDataApi = MutableLiveData()
        this.weatherMutableLiveDataBD = MutableLiveData()
    }

    override fun fetchWeather(): MutableLiveData<WeatherModel> {

        GlobalScope.launch {
            Dispatchers.IO
            try {
                val response = RetrofitClient.getApiService()
                    .getWeather(
                        "33.441792", "-94.037689", "minutely",
                        Constant.APP_ID
                    ).execute()
                // Check if response was successful.
                withContext(Dispatchers.Main) {

                    if (response.isSuccessful) {
                        Log.i("test1", " " + weatherMutableLiveDataApi.value)
                        weatherMutableLiveDataApi.value = response.body()
                        Log.i("test2", " " + weatherMutableLiveDataApi.value)
                    }
                }
            } catch (e: Exception) {
                Log.i("testError", " " + e.message)
            }
        }
        Log.i("test3", " " + weatherMutableLiveDataApi.value)
        return weatherMutableLiveDataApi

    }

    override suspend fun addweatherInDB(weatherTable: WeatherTable, context: Context) {
       val database = WeatherDatabase.getInstance(context)
        GlobalScope.launch {
            database.WeatherDao().insertCurrentWeather(weatherTable)
//            withContext(Dispatchers.Main) {
////                Toast.makeText(requireActivity(), "Current Weather  Saved", Toast.LENGTH_LONG)
////                    .show()
//            }

        }

    }

    override suspend fun getweatherFromDB(context: Context): LiveData<List<WeatherTable>> {

        GlobalScope.launch {
           val database = WeatherDatabase.getInstance(context)
            weatherMutableLiveDataBD = database.WeatherDao().getCurrentWeather()

        }
      //  Log.v("fff",weatherMutableLiveDataBD.value!!.get(0).desc)
        return weatherMutableLiveDataBD
    }
}

**Comment by dragossusi** [comment]
you need to show DAO code as well

**Comment by aids61517** [comment]
In general case, `GlobalScope.launch { }` do **Not** execute immediately.

So `return weatherMutableLiveDataApi` is executed before `GlobalScope.launch`, and `weatherMutableLiveDataApi` is updated when api success.

If you insert a weather data into db and call `getweatherFromDB`, you would get a **old** LiveData because `return weatherMutableLiveDataApi` is executed before `GlobalScope.launch`.

After you get **old** LiveData, weatherMutableLiveDataBD's instance is changed because 
`weatherMutableLiveDataBD = database.WeatherDao().getCurrentWeather()`

So you don't get weather you insert.

**Comment by aids61517** [comment]
In general case, ```GlobalScope.launch { }``` do **Not** execute immediately.

So ```return weatherMutableLiveDataApi``` is executed before ```GlobalScope.launch```, and weatherMutableLiveDataApi is updated when api success.

If you insert a weather data into db and call ```getweatherFromDB()```, you would get a **old** LiveData because ```return weatherMutableLiveDataBD``` is executed ```before GlobalScope.launch```.

After you get old LiveData, weatherMutableLiveDataBD's instance is changed because
```weatherMutableLiveDataBD = database.WeatherDao().getCurrentWeather()```

So you don't get weather in DB because **old** weatherMutableLiveDataBD's value is empty.

**Comment by qwwdfsad** [comment]
It seems to be the general question, not directly related to `kotlinx.coroutines`. I'd suggest seeking help in a corresponding Slack channel or stackoverflow
