### ISSUE TITLE
Return value of sharIn&stateIn don't hold a strong reference to the sharing coroutine, letting them be garbage collected

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#2557]
Hello,

The `shareIn` and `stateIn` operators for `Flow` are unfortunately victims of that problem: https://youtrack.jetbrains.com/issue/KT-30588

Here's a self-contained commented snippet that you can run to see the issue:
```kotlin
@file:OptIn(ExperimentalTime::class, ExperimentalCoroutinesApi::class)

import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.channels.*
import java.lang.ref.WeakReference
import kotlin.coroutines.EmptyCoroutineContext
import kotlin.time.Duration
import kotlin.time.ExperimentalTime
import kotlin.time.milliseconds
import kotlin.time.seconds

fun main(): Unit = runBlocking {
    println("Hello World!")
    val jobToCancel = launch {
        someFlow.collect()
    }
    delay(100.milliseconds) // Ensure the flow has a chance to be activated before GC happens.
    repeat(5) {
        System.gc() // Keep only strong references
        System.gc() // Really GC!
        delay(1.seconds)
    }
    jobToCancel.cancel()
}

// Strongly references a Job holding scope that will keep child coroutines strongly referenced as well.
val theScope = CoroutineScope(EmptyCoroutineContext)

val someFlow = flow<Int> {
    iterationsFlow(1.seconds).collect {
        println("Got $it")
        currentCoroutineContext().ensureActive()
    }
}.stateIn(
    scope = CoroutineScope(EmptyCoroutineContext), // Replace it with `theScope` and the issue goes away
    started = SharingStarted.Eagerly, // Or use `WhileSubscribed()` and the issue somehow goes away too.
    initialValue = 0
)

fun iterationsFlow(interval: Duration): Flow<Int> = callbackFlow {
    val listener = Listener {
        runCatching { offer(it) } // runCatching because of https://github.com/Kotlin/kotlinx.coroutines/issues/974
    }
    val cb = CallbackRepeatCaller(interval, listener)
    awaitClose {
        cb.forget()
        listener.call(-1)
    }
}


fun interface Listener {
    fun call(iterations: Int)
}

class CallbackRepeatCaller(interval: Duration, listener: Listener) {
    private val ref = WeakReference(listener) // Mimics actual APIs like Android's MediaPlayer or SharedPreferences.

    //private val l = listener // Uncommenting this code would "fix" the issue,
    // but it only works if you control the code.

    private val caller = CoroutineScope(EmptyCoroutineContext).launch {
        var iterations = 0
        while (true) {
            ensureActive()
            ref.get()?.call(++iterations)
            delay(interval)
        }
    }

    fun forget() {
        caller.cancel()
        ref.clear()
    }
}

```

### Actual output:
```
Hello World!
Got 1
```

### Expected output:
```
Hello World!
Got 1
Got 2
Got 3
Got 4
Got 5
Got 6
```

You can see this is what we get when we use a scope holding a `Job` and keep a top level strong reference to it.

## What happens

The coroutine is suspended and nothing holds a strong reference to it because the returned `StateFlow`/`SharedFlow` doesn't have any internal reference to the parent `Job` of the coroutine collecting the flow to share, and the suspended call uses a `WeakReference` to the listener, which is the last holder of a strong reference to the continuation.

## Why it's a problem

It affected customers of my company as something was stuck, but didn't reproduce if GC hadn't triggered.
It was quite hard to find the root cause, and the solution needed some research.

A bunch of JVM APIs use `WeakReference` to help Java callers avoid memory leaks, so kotlinx.coroutines relying on every suspend function to keep a strong reference to the continuation while suspended is problematic and will lead to further occurrences until it's changed.

## Possible solutions I know

There's two problems:

### Problem 1

It's possible and very easy to get or instantiate a `CoroutineScope` that has no `Job()`.
These scopes (like `GlobalScope`) will not keep a strong reference to running coroutines and allow this issue to happen.

To prevent this problem from happening, the `coroutineContext` property of `CoroutineScope` could start requiring opt-in with `@InternalCoroutinesApi`, so users must either use implementations provided by kotlinx.coroutines, or acknowledge the risks and opt-in.
Then, the `GlobalScope` object implementation could be changed so its `coroutineContext` has a `SupervisorJob` that doesn't respond to `cancel()`, so it keeps references to the child coroutines.
The same could be done for `NonCancellable` so it doesn't leave the continuation unreferenced.

Introducing these changes would also prevent future recurrence of issues like the one that led to this same report: https://youtrack.jetbrains.com/issue/KT-30588

### Problem 2

The returned `SharedFlow`/`StateFlow` doesn't hold any reference to the coroutine if you're using `Eagerly` or `Lazily` for `started`, allowing this issue to happen as well.

To prevent this issue, the instance of `SharedFlow`/`StateFlow` returned by `shareIn` and `stateIn` should have a private field that keeps a reference to the result of the `launch` call done in the `launchSharing` internal function.
That way, regardless of the `SharingStarted` "strategy", this bug can't happen anymore.

**Comment by LouisCAD** [comment]
BTW, I can send a PR for that. Should I?

**Comment by LouisCAD** [comment]
@qwwdfsad Shouldn't that be also labelled as a bug?
Can it be resolved in 1.5?
And asking again: Should I send a PR?

**Comment by elizarov** [comment]
Frankly, I see it as yet another testament to the dangers of `GlobalScope` and that it should not be ever really used in industrial apps. The more I see it, the more I think we should require an explicit opt-in to use `GlobalScope`.

**Comment by LouisCAD** [comment]
I recall asking you to make GlobalScope requiring opt-in in tbe the past, glad you're coming to the same conclusion.

That said, the same dangers would happen with any custom `CoroutineScope` implementation that doesn't contain a `Job` on which a strong reference is held, so that issue I reported should still be addressed to avoid future pain and bugs.

**Comment by elizarov** [comment]
Ideally, we should deprecate non-Job coroutine scopes, too. We have started onto this path already, making sure that `CoroutineScope` constructor always creates a `Job`. It is not clear how to enforce it even more. However, please note that there is no goal to make it really impossible. There are still legitimate use-cases even for a `GlobalScope`. All we need is to give a stronger warning that by opting out of structured concurrency you could run into all sorts of problems.

**Comment by LouisCAD** [comment]
I agree with you.

That said, regarding the issue reported here, If I recall correctly about the tests/experiments I did, you could have it even using a `CoroutineScope` that has a `Job` inside because the current implementation of these `Flow` sharing operators implicitly rely on the scope passed to it being strongly referenced from the outside.

If the `Job` keeps a strong reference to child coroutines, but is itself referenced by a `CoroutineScope` that has no strong reference, that's what happens, right?

As you know well, Kotlin strives to be explicit rather than implicit.

**Comment by elizarov** [comment]
Coroutines are not threads and the coroutines library does not add any implicit strong references. There's simply no way we can do otherwise and start storing coroutines in some global strongly referenced list. If an app needs a coroutine to be strongly referenced, then it is up to this app to ensure there is a strong reference. The only problem from this issue we can fix, is to make a stronger warning to people trying to use `GlobalScope` that should likely consider doing something else.

**Comment by LouisCAD** [comment]
The request here is NOT to keep a global list of all the running coroutines.

The request is to have the returned `SharedFlow` or `StateFlow` hold a strong reference to the coroutine it relies on, and I'm offering to send a PR for that scope limited change.

**Comment by lukas1** [comment]
I believe I may have been affected by this bug as well. I don't have such a nice small reproducible example as @LouisCAD , I'm working on an Android project and the setup to reproduce the issue in my case is complex and would require also knowledge of some Android APIs, but basically I'm creating my own CoroutineScope:

```kotlin
@Suppress("FunctionName")
fun DefaultCoroutineScope(): CoroutineScope =
    CoroutineScope(SupervisorJob() + Dispatchers.Default)
```

(so it does have a Job associated with it)

Then I call this method to create an instance of Coroutine scope and pass it to constructor, something like this:
```kotlin
val myClass = MyClass(DefaultCoroutineScope())
```

And then, my class:

```kotlin
class MyClass(coroutineScope: CoroutineScope) {
  val myFlow: Flow<Int> = someAlreadyExistingFlow
     .stateIn(coroutineScope, SharingStarted.Eagerly, 0)
}
```

When `someAlreadyExistingFlow` should be emitting items, I don't get them when subscribed to `myFlow`.

However, changing to `SharingStarted.WhileSubscribed()` does fix the issue. Alternatively, I can keep `SharingStarted.Eagerly` and just change signature of the constructor, so that `coroutineScope` becomes a property and then it works.

Basically it seems it is important to keep holding reference to the `coroutineScope`, because `stateIn` operator will not hold it.

I certainly did not expect that behaviour and there was nothing warning me in compile time or otherwise that I need to be careful and hold the reference outside of just passing it to `stateIn`.

What puzzled me even more when I first encountered the issue was, that a unit test ran correctly. Now, reading through this discussion here, I understand that it's just a matter of Garbage collection not being ran. 

So I seem to have arrived at the same conclusion as @LouisCAD that this issue is not related to `GlobalScope` at all, in fact, not even to the fact whether `Job` is bound to the `CoroutineScope` or not, but at least from my observation, there's simply a need to hold strong reference to the sharing `CoroutineScope`.

**Comment by lukas1** [comment]
> and I'm offering to send a PR for that scope limited change.

I'd say just do it regardless ;o) Worst case scenario it won't get accepted. At least it can spark some higher quality discussion and maybe at least some partial solution will come out of it.

**Comment by LouisCAD** [comment]
@elizarov I just replaced the only `GlobalScope` usage from my reproducer with `CoroutineScope(EmptyCoroutineContext)` to prove that the bug is not related to `GlobalScope` in any way, and that it needs to be addressed.

I think I'm gonna listen to @lukas1 and send a PR anyway, which will include a test inspired by the reproducer I posted.

**Comment by elizarov** [comment]
> @LouisCAD I just replaced the only `GlobalScope` usage from my reproducer with `CoroutineScope(EmptyCoroutineContext)` to prove that the bug is not related to `GlobalScope` in any way, and that it needs to be addressed.

The `CoroutineScope(EmptyCoroutineContext)` expression works just like `GlobalScope` and is unstructured. Actually, the new docs on `GlobalScope` now mention it:  https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/CoroutineScope.kt#L192-L196. 

You must store a reference to your coroutine scope for structured concurrency. Changing it to `theScope` fixes the problem because you now have a strong reference to your running coroutine and is following the practice of structured concurrency.

**Comment by lukas1** [comment]
> You must store a reference to your coroutine scope for structured concurrency.

@elizarov Does it at least make sense to say so in the documentation for `shareIn` and `stateIn` ? It surprised me personally, because as mentioned, unit tests passed and just changing the `SharingStarted` parameter value also makes the scope remembered and one does not need to hold the reference on their own.

It's a non-trivial gotcha. Especially when one makes a small change of just changing `SharingStarted.WhileSubscribed()` to `SharingStarted.Eagerly`, one does not expect it will produce this kind of bug.

I don't like such a fragile design in general, but maybe it can't be helped, anyway it should at least be documented IMHO.

**Comment by elizarov** [comment]
I've looked closer at it. Indeed, the whole situation is tricky, hard to debug, and depends on many different factors, so it does make sense for `stateIn` and `shareIn` operators to return the resulting `Flow` that keeps a strong reference to the original flow that is given as an input to those operators, just like all the other operators do. Here it is -> #2701
