### ISSUE TITLE
Provide an API to check that the current coroutine is created via runBlocking

### ISSUE THREAD

**Issue by khovanskiy** [Kotlin/kotlinx.coroutines#2582]
This is a useful option for optimizing blocking calls. For example, we have a large external thread pool (like Jetty) and want to run coroutines in it, so we can spend only these threads and save threads of Dispatchers. I understand that the best way is to use reactive libraries like Netty and Reactor, but in the real enterprise code, this migration is not fast, so there is a need to have some wrappers.

## Example
We have a common function. This function can be run from a lot of places: Reactor/Netty/Jetty/Ktor. If we don't know about the context, the proper way is to run blocking code on `Dispatcher.IO`:
```
suspend fun someMethod() {
   runInterruptible(context = Dispatchers.IO) {
      someBlockingMethod()
   }
}
```
So we can invoke this method in the following cases:
```
GlobalScope.launch {
    someMethod()
}
```
or
```
runBlocking {
    someMethod()
}
```
In the second case, we spent one thread from `Dispatcher.IO` having the already blocked current thread. Also, we switched the context.

Meanwhile, if we could check that the current context is running on the blocking event loop, we could run blocking code without using `Dispatcher.IO`:

```
suspend fun someMethod() {
   val isBlocking = ... // call the API
   if (isBlocking) {
      runInterruptible(context = EmptyCoroutineContext) {
         someBlockingMethod()
      }
   } else {
      runInterruptible(context = Dispatchers.IO) {
         someBlockingMethod()
      }
   }
}
```

It will be nice if the API can provide the method to check it or support this internal optimization in  `runInterruptible`.

**Comment by qwwdfsad** [comment]
Thanks for the report with a detailed use-case!

>support this internal optimization in runInterruptible

It cannot be the case for multiple reasons:

First, the code would ignore the explicitly requested dispatcher and would behave in a completely unexpected way. E.g. `runInterruptible(Dispatchers.IO)` for some reason does not switch the thread (all thread locals are accessible), while `runUnterruprible(MyApplicationIoDispatcher)` does.

Second, it breaks code that previously could've worked:
```
runBlocking {
    launch {
        someMethod()
    }
    launch {
        someMethod()
    }
}
``` 

After such optimization, it becomes sequential (potentially dead-locked) instead of parallel.

Manual optimizations using the proposed API also prone to a second pitfall. Also, carrying this information can be somewhat costly and have vague semantics. 

E.g. consider the following:
```
runBlocking {
    // isBlocking: true
    launch(Dispatchers.Default, start = UNDISPATCHED) {
         // isBlocking: true
         yield()
         // isBlocking: false
    }
 
    launch(Dispatchers.Unconfined) {
        // isBlocking may be both true and false here depending on the execution context
    }

    withContext(CoroutineName("foo") {
        // isBlocking: true
    }
}
```

This example shows that this API cannot be implemented as a coroutine-related extension, but it is rather current thread property (-> is top-level property/function). 

Detecting whether it is allowed to block the current thread is somewhat out of the scope of `kotlinx.coroutines`, not actually related to `runBlocking` and rather an application-specific detail. Taking this into account, we are unlikely to introduce such API.

As a project-specific solution, it's okay to carry a `ThreadLocal` around, set it either on threads instantiation or prior to `runBlocking` calls and check it in your `isBlocking` implementation

**Comment by elizarov** [comment]
It would be interesting to know more about the context of the outer `runBlocking { ... }` call -- why it is there and on what threadpool is it happening. 

If you have some degree of control on the thread pool that is used for that code, then you could have arranged it so that it is working inside `Dispatchers.IO` threads in the first place. When a provision is in place, you will not need any special API at all. All your `runBlocking { runInterruptible(Dispatchers.IO) { ... } }` will automatically avoid an extra context-switch when you are already running in an IO thread.

**Comment by khovanskiy** [comment]
@qwwdfsad, I think breaking of backward compatibility can be avoided using an additional option for ```runBlocking```. For, example:
```
runBlocking(useBlockedThread = true)
```
In such mode the option ```start = UNDISPATCHED``` is ignored and ```launch``` always executes on ```Dispatchers.Default```. But this flag doesn't inherit, so another inner ```launch``` with ```start = UNDISPATCHED``` works as usual. It helps to support correct parallel execution without deadlocks. Also, it works similarly for ```launch(Dispatchers.Unconfined)```.

Thus, ```isBlocking``` will be ```true``` only in the "parent" blocking scope:
```
runBlocking {
    // isBlocking: true
    launch(Dispatchers.Default, start = UNDISPATCHED) {
         // isBlocking: false
         yield()
         // isBlocking: false
    }
 
    launch(Dispatchers.Unconfined) {
        // isBlocking: false
    }

    withContext(CoroutineName("foo")) {
        // isBlocking: true
    }
}
```

@elizarov, I have multiple cases of thread pools cause the solution is used in new non-blocking code and legacy blocking code:
**1. Spring Servlets.** It is based on a thread pool in Jetty that consumes 200 threads for blocking operations. In Spring Controller it looks like:
```
@RestMapping("/api/endpoint")
fun legacyEndpoint(): Unit = runBlocking {
    service.callNewNonBlockingApi()
}
```
**2. Java/Koltin API.** For example, I had an API method with complex business-logic:
```
blockingMethod -> logic1 -> logic2 -> logic3 -> innerBlockingMethod
``` 
and then I want to support nonblocking variant of this method like this:
```
nonBlockingMethod -> logic1 -> logic2 -> logic3 -> innerNonBlockingMethod
```
To solve this issue I have two approaches:
1. I can copy my three methods (logic1, logic2, logic3) as-is with ```suspend``` modifier. It is just a copy-paste so it should be clear why is a bad approach;
2. I can only write ```nonBlockingMethod``` and call it in ```blockingMethod``` with ```runBlocking``` wrapper. It is bad because an external pool can be larger than the inner coroutines Dispatcher so we get a bottleneck.

**Comment by elizarov** [comment]
> It is based on a thread pool in Jetty that consumes 200 threads for blocking operations
In this case, it seems that it is no a property of the `runBlocking` call itself. It looks like it is a property of the thread. Essentially, you are looking for an API to tag some thread, that you know as being a part of "blocking thread pool" so that `Dispatchers.IO` is aware of this thread and does not try to switch out of it, but reuses the current "blocking thread" for doing whatever blocking work it is scheduled to do in it.

**Comment by khovanskiy** [comment]
> This API can be tied to `runBlocking` for convenience, but what you are looking for is not really a signal to `runBlocking` itself. It is a signal to `Dispatchers.IO` and should be clearly named as such.

You probably are right. It would be even better if we had a tag to mark some thread to prevent the switch dispatcher in `runBlocking` call. It can be `ThreadLocal` or `CoroutineContext.Element ` published as an API. Thus, any external library (including ours) can use it in their thread pools.
