### ISSUE TITLE
Missing 1.4.2-native-mt branch

### ISSUE THREAD

**Issue by vanniktech** [Kotlin/kotlinx.coroutines#2585]
I seem to find the branch for 1.4.1 - https://github.com/Kotlin/kotlinx.coroutines/blob/native-mt-1.4.1/LICENSE.txt - but not for 1.4.2 - where can I find it? A git tag would also suffice.

**Comment by qwwdfsad** [comment]
We don't have one, for `-native-mt` versions we do releases from `native-mt` branch and squash all `native-mt` changes on a regular basis in order to simplify the maintenance of this "fork".

`native-mt-1.4.1` and others are intermediate branches to snapshot a state before rebasing in all to `develop`.

Basically, we only have `native-mt` that corresponds to the state of the latest `-native-mt` release

**Comment by vanniktech** [comment]
Alright. So `native-mt` currently corresponds to 1.4.2-native-mt?

**Comment by qwwdfsad** [comment]
Indeed

**Comment by vanniktech** [comment]
Thanks for answering so quickly!
