### ISSUE TITLE
Add runningFold function to Flow

### ISSUE THREAD

**Issue by jakobulbrich** [Kotlin/kotlinx.coroutines#2641]
Kotlin supports the following functions on Collections
- `reduce` and `runningReduce`
- `fold` and `runningFold`

whereas Flows only support
- `reduce` and `runningReduce`
- `fold` and **???**

Turns out the function is called `scan`, which is not consistent with the known naming scheme and hard to find. The `scan` function also exists for Collections but only acts as an alias for `runningFold` there.

It would be helpful to also add the `runningFold` function to Flows.

**Comment by pacher** [comment]
Well, just to be fair, coming from RxJava it is much easier to find `scan` than `runningFold`, also for Collections :)

**Comment by qwwdfsad** [comment]
Thanks for pointing it out!

>Well, just to be fair, coming from RxJava it is much easier to find scan than runningFold

Indeed! This alias exists for better discoverability for people who came from reactive frameworks.
But we weren't really happy with the name `scan`. It doesn't have any reasonable rationale now, the name came from [APL](https://en.wikipedia.org/wiki/APL_(programming_language)) where `\` operator with the same semantics was called `scan` , probably due to similarity to "scanning line".

**Comment by pacher** [comment]
True, the name `scan` was puzzling at first in rx, but it is nice and short and we are quite used to it now.
What I mean is please keep it as an alias to `runningFold`, I would prefer keep using scan despite the lack of reasonable rationale ;-)

**Comment by sebastianharder** [comment]
@qwwdfsad the KDoc of `runningFold` refers to the `scan` function.
