### ISSUE TITLE
Different dispatcher used when using flatMapLatest()

### ISSUE THREAD

**Issue by hrach** [Kotlin/kotlinx.coroutines#2648]
Hi, in our unit tests we discovered unexpected behavior of flatMapLatest's dispatcher:

If you have this code, everything works as expected.

```kotlin
  private val testDispatcher: TestCoroutineDispatcher = TestCoroutineDispatcher()

  @Test
  fun test() = runBlockingTest {
    val flow = MutableStateFlow(0)

    val derived = flow
      .map { it }
      .flowOn(testDispatcher)
      .stateIn(GlobalScope, SharingStarted.Eagerly, -1)

    flow.value = 1
    assertThat(derived.value, `is`(1)) // ok
  }
```

Switching to `flatMapLatest` gets it broken, since its body is run on different than testDispatcher.

```kotlin
  @Test
  fun test() = runBlockingTest {
    val flow = MutableStateFlow(0)

    val derived = flow
      .flatMapLatest { flowOf(it) }
      .flowOn(testDispatcher)
      .stateIn(GlobalScope, SharingStarted.Eagerly, -1)

    flow.value = 1
    assertThat(derived.value, `is`(1)) // fails
  }
```

We have fixed it this way:
```kotlin
  @Test
  fun test() = runBlockingTest {
    val flow = MutableStateFlow(0)

    val derived = flow
      .flatMapLatest { flowOf(it) }
      .flowOn(testDispatcher)
      .stateIn(CoroutineScope(SupervisorJob() + testDispatcher), SharingStarted.Eagerly, -1)

    flow.value = 1
    assertThat(derived.value, `is`(1)) // ok
  }
```

Is it expected bahavior?

**Comment by NinoDLC** [comment]
An instance of SharedFlow does not have an execution context by itself, so applying `flowOn` to a `SharedFlow` has no effect. `MutableStateFlow` inherits from `SharedFlow`

**Comment by hrach** [comment]
@NinoDLC after the "flatMapLatest" it is no longer a SharedFlow, but just a flow.

**Comment by hrach** [comment]
Any change this get fixed in 1.6? Thank you.

**Comment by dkhalanskyjb** [comment]
Hi @hrach! In short, this seems to work as intended.

Initially, we dismissed the issue, because it looked like it was related to `TestCoroutineDispatcher`, which in this case behaves the same way as `Unconfined`, which explains the dispatcher-switching behavior. However, experimenting with a non-unconfined `TestCoroutineDispatcher` showed that the problem is not related to that. @qwwdfsad took a look, and here are his findings, which I relay.

The root cause of the problem is that `GlobalScope` doesn't have a dispatcher attached to it. So, when using `stateIn(GlobalScope, _, _)`, `Dispatchers.Default` is the dispatcher that is used to subscribe to the flow. `Dispatchers.Default` uses one of its own threads for this, and therefore, there is a race between `stateIn` and the code below it: it's possible that the code below executes completely even before the sharing of the state is started.

`map { it }` and `flatMapLatest { flowOf(it) }` are actually identical in this case, and it's possible to consistently observe your issue with `map { it }` as well by artificially hindering the part of `stateIn(GlobalScope, _, _)` that happens in `GlobalScope`. You observe a difference between `map` and `flatMapLatest` only because `flatMapLatest { flowOf(it) }` is more complex than `map { it }` and more things have time to happen while it initializes. The bottom line is, with enough luck, `flatMapLatest { flowOf(it) }` will also work sometimes, and `map { it }` will also not work sometimes. Inserting `Thread.sleep(100)` before `flow.value = 1` makes `flatMapLatest { flowOf(it) }` work consistently (`delay(100)` wouldn't help here though, as the test dispatcher skips the delays).

The reason why `testDispatcher` in `stateIn` fixes the problem is that `testDispatcher` uses the same thread to run its coroutines, so `stateIn(SupervisorJob() + testDispatcher, _, _)` will finish subscribing before continuing.

Does this clarify things?

**Comment by hrach** [comment]
> Does this clarify things?

Yes, thank you very much!
