### ISSUE TITLE
Does it support Flow sorting?

### ISSUE THREAD

**Issue by RinOrz** [Kotlin/kotlinx.coroutines#2672]
In a `JAVA8-Stream`, we can use the `sorted` operator to sort the content of the `Stream`. Is there an equivalent for `Flow`? I need to sort a files flow.

**Comment by JakeWharton** [comment]
Since you cannot sort until you have all of the elements, this can be accomplished with `toList()` and then sort.

**Comment by RinOrz** [comment]
> Since you cannot sort until you have all of the elements, this can be accomplished with `toList()` and then sort.

Thank you for your answers, digression, but I am very curious why **Java Stream** can be sorted before collect. Isn't it a cold **Stream** like **Flow**?

**Comment by fvasco** [comment]
Java Collection lacks of many operators.

**Comment by pablobaxter** [comment]
So reading on the Java Steam API, the `sorted` operators are listed as a stateful intermediate operation (https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#sorted--). If you go further into the documentation, it states:

> Stateful operations may need to process the entire input before producing a result. For example, one cannot produce any results from sorting a stream until one has seen all elements of the stream. As a result, under parallel computation, some pipelines containing stateful intermediate operations may require multiple passes on the data or may need to buffer significant data. Pipelines containing exclusively stateless intermediate operations can be processed in a single pass, whether sequential or parallel, with minimal data buffering. 

Source: https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html#StreamOps

Essentially, using `toList()` then sorting on a Flow would be equivalent to to calling `stream().sort()` for Java Stream.

**Comment by RinOrz** [comment]
> Essentially, using `toList()` then sorting on a Flow would be equivalent to to calling `stream().sort()` for Java Stream.

Thanks, can I understand it as the following code?
```kotlin
val list = this
flow {
  emitAll(this.sorted().asFlow())
}
```

**Comment by pablobaxter** [comment]
It would be more like this:

```
fun <T> Flow<T>.sorted() = flow {
  emitAll(it.toList().sortedWith(/* .. comparator ..*/).asFlow())
}
```

You would need to await for the given flow to complete in order to sort it, then emit all the values again into a new flow. The above is for demonstration based on what you provided, but I would just do the following instead:

```
flow.toList()..sortedWith(/* .. comparator ..*/).asFlow()
```

It accomplishes the same thing, and easier to follow (IMO). Keep in mind that this will not work with sharedflows, as they never complete.

**Comment by RinOrz** [comment]
> It would be more like this:
> 
> ```
> fun <T> Flow<T>.sorted() = flow {
>   emitAll(it.toList().sortedWith(/* .. comparator ..*/).asFlow())
> }
> ```
> 
> You would need to await for the given flow to complete in order to sort it, then emit all the values again into a new flow. The above is for demonstration based on what you provided, but I would just do the following instead:
> 
> ```
> flow.toList()..sortedWith(/* .. comparator ..*/).asFlow()
> ```
> 
> It accomplishes the same thing, and easier to follow (IMO). Keep in mind that this will not work with sharedflows, as they never complete.

Thank you for your detailed answer, great!

**Comment by elizarov** [comment]
A difference between Java `Stream` and Kotlin `Flow`, is that the latter is an _asynchronous_ stream, while the former is a _synchronous_ stream. So, while they are similar, it does not make sense to define a sorting operator on a flow, because it will kill all the synchrony. Moreover, it is a bad style to define one. The combination of `.toList().sorted()` is much more explicit and gives a clear indication to the reading of the code what is happening there.
