### ISSUE TITLE
Flow not collected if a job is started

### ISSUE THREAD

**Issue by dellisd** [Kotlin/kotlinx.coroutines#2681]
I ran into an issue where I had a function that would launch a job that emits value to a shared flow, and then would return that flow so it could be collected elsewhere.

The issue is that the flow is not collected if the job is launched either in an `onStart` operator on that flow, or if the function is a `suspend` function.

I've reproduced the issue with a few examples here:
https://github.com/dellisd/coroutines-bug

Note: I ran into this issue with coroutines 1.4.3 and Kotlin 1.4.32, but the issue is still present in Kotlin 1.5 and coroutines 1.5.

**Comment by dkhalanskyjb** [comment]
Hi! This doesn't look like a bug. Shared flows are hot, meaning that their elements are emitted regardless of whether there is a collector. In the two cases that you presented, all the emissions are performed before `collect` happens, so when `collect` actually starts, everything interesting had already happened.

With `Broken2Main`, the problem is that `coroutineScope` does not return until all of its children do, so `exampleUseCase()` only returns after `doLoop()` has finished completely, with `Finish` being emitted before `collect` has a chance to run.

In case of `BrokenMain`, likewise, the problem is that the code inside `onStart` does not finish until there are no more emissions, and `collect` doesn't start until `onStart` has finished, so there are no emissions for the collector to observe.

**Comment by dellisd** [comment]
I was unaware of that behaviour for `coroutineScope`, thank you for explaining!
