### ISSUE TITLE
Channel was still closed after the exception was caught

### ISSUE THREAD

**Issue by Vixb1122** [Kotlin/kotlinx.coroutines#2697]
```Kotlin
fun View.clicksFlow(
    scope: CoroutineScope,
    error: Throwable.() -> Unit = {},
    block: (view: View) -> Unit,
) =
    callbackFlow {
        setOnClickListener(this::offer)
        awaitClose {
            setOnClickListener(null)
        }
    }
        .throttleFirst(1000)
        .onEach { block(it) }
        .catch { error(it) }
        .launchIn(scope)


test.clicksFlow(lifecycleScope){
  ...
}
```
1. `catch` block has caught the exception, but channel is still closed, and `awaitClose` block is executed.
2. `lifecycleScope` consist of 'SupervisorJob()'
How to avoid closing channel when catching the exception.

**Comment by qwwdfsad** [comment]
>catch block has caught the exception, but the channel is still closed, and awaitClose block is executed.

This is expected behaviour. `catch` does not propagate an exception to the downstream (`launchIn`), but upstream is already has thrown an exception and cannot be resumed normally.

Similarly to how you can write `use` with `catch` in a regular Kotlin:
```
try {
    file.use {
        // read from file
    }
} catch (e: IOException) {
   // Catch IO error
}
```
Even tho the exception is handled, the file is closed anyway and you cannot normally continue to execute the very same `try` block. 

>How to avoid closing channel when catching the exception.

Then you have top handle it in the particular method that is throwing it, most likely it is `block` in your case:
```
flow.onEach { 
    runCatching { block(it) }
    .onFailure {
        // handle the exception in your application-specific way
    }
}
```

**Comment by Vixb1122** [comment]
@qwwdfsad 3Q
