### ISSUE TITLE
Flow zip shareIn block indefinitely

### ISSUE THREAD

**Issue by pabloparada** [Kotlin/kotlinx.coroutines#2725]
Zipping two flows where one is `sharedIn` or `SharedFlow` then `collect` and `main` block hangs indefinitely. 

Is this what is supposed to happen?

```
fun main() {
    runBlocking() {
            val f1 = flowOf("A").shareIn(CoroutineScope(Dispatchers.Default), SharingStarted.Lazily, Int.MAX_VALUE)
            val f2 = flowOf(1, 2, 3, 4, 5)

            f1.zip(f2) { a, b -> a + b }.collect {
                println(it)
            }
    }
}
```

Expected output: 

```
A1
A2
A3
A4
A5
```

**Comment by dkhalanskyjb** [comment]
Doing `f1.collect` even without any `zip` already hangs indefinitely. This is expected, as the [documentation on `SharedFlow`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-shared-flow/) highlights.

`zip` waits until both flows emit a value, and then combines their results. Since `f1` only ever emits a single value, only one value is being emitted by the `zip`. Consider using `combine`, which repeats and drops values acquired from upsteam; with `combine`, the output looks like the one you expect, though some values of `f2` can be dropped.
