### ISSUE TITLE
callbackFlow does not execute body immediately on collect

### ISSUE THREAD

**Issue by jingibus** [Kotlin/kotlinx.coroutines#2767]
When calling `collect` on a `callbackFlow`, a suspend point will be hit prior to execution of the flow's body.

```kotlin
  @Test fun callbackFlowSuspend() : Unit = runBlockingTest {
    var eventReceiver : ((Int) -> Unit)? = null
    val events = callbackFlow {
      eventReceiver = { event ->
        @Suppress("BlockingMethodInNonBlockingContext")
        trySendBlocking(event)
      }
    }

    pauseDispatcher()
    launch (start = UNDISPATCHED) {
      events.collect { event ->
      }
    }

    assertThat(eventReceiver).isNotNull()
  }
```

As a result, it is not possible to ensure that e.g. event handlers are wired up promptly when the flow starts.

**Comment by jingibus** [comment]
This is not a testing issue: the given code exercises a behavior observed in production code.

**Comment by dkhalanskyjb** [comment]
This is intentional. Consider, for example, the following code, which is part of our codebase:
```kotlin
public fun <T> ObservableValue<T>.asFlow(): Flow<T> = callbackFlow<T> {
    val listener = ChangeListener<T> { _, _, newValue ->
        trySend(newValue)
    }
    addListener(listener)
    send(value)
    awaitClose {
        removeListener(listener)
    }
}.flowOn(Dispatchers.JavaFx).conflate()
```
It's not necessary to know about JavaFX here. The two details that are important here are:
* `addListener` and `removeListener` are only allowed to be called from the `Dispatchers.JavaFx` dispatcher;
* The first suspension in the block passed to `callbackFlow` happens in `awaitClose`.

Suppose we were to change `callbackFlow` so that it starts executing the block passed to it from `collect` without suspensions. Then the code before `awaitClose` would have to execute in the same execution context as the `collect`, which is not guaranteed to be `Dispatchers.JavaFx`, so `addListener` would potentially execute on the wrong thread!

In general, when `flowOn` is present, it would be unexpected if the code in that flow was *not* dispatched before being run, and the case where there is no `flowOn` doesn't feel distinct enough to warrant special suspending behavior.
