### ISSUE TITLE
Dispatchers.IO does not clear interrupt flag

### ISSUE THREAD

**Issue by aasitnikov** [Kotlin/kotlinx.coroutines#2771]
I didn't find any documentation stating that `Executor` or `ExecutorService` should clear thread's interrupt flag before starting next job, but it's what most of java.util.councurrent.* Executors do. [`CoroutineDispatcher.asExecutor()`](https://github.com/Kotlin/kotlinx.coroutines/blob/1.5.0/kotlinx-coroutines-core/jvm/src/Executors.kt#L70-L71) just adapts `CoroutineDispatcher` to `Executor` interface, and [`LimitingDispatcher`](https://github.com/Kotlin/kotlinx.coroutines/blob/1.5.0/kotlinx-coroutines-core/jvm/src/scheduling/Dispatcher.kt#L143), used by [`Dispatchers.IO`](https://github.com/Kotlin/kotlinx.coroutines/blob/5eca49cfcb25acefaf10ec9b997de537c653b47e/kotlinx-coroutines-core/jvm/src/Dispatchers.kt#L117), doesn't seem to clear interrupt status between invocations on the same thread. This dispatcher was designed to call blocking code, and blocking code can use thread interrupts quite extensively. 

```
fun test(executor: Executor): Int {
    val counter = AtomicInteger()
    val latch = CountDownLatch(2000)
    repeat(1000) {
        executor.execute {
            Thread.currentThread().interrupt()
            latch.countDown()
        }

        executor.execute {
            if (Thread.interrupted()) {
                counter.incrementAndGet()
            }
            latch.countDown()
        }
    }
    latch.await()
    return counter.get()
}

println("Executors.newCachedThreadPool(): " + test(Executors.newCachedThreadPool()))
println("Dispatchers.IO.asExecutor(): " + test(Dispatchers.IO.asExecutor()))
println("Dispatchers.IO.asExecutor().withClearingInterrupt(): " + test(Dispatchers.IO.asExecutor().withClearingInterrupt()))
System.exit(0)
```

```
Executors.newCachedThreadPool(): 0
Dispatchers.IO.asExecutor(): 329
Dispatchers.IO.asExecutor().withClearingInterrupt(): 0
```

It's easy to fix it in client code like this:

```
fun Executor.withClearingInterrupt(): Executor {
    return Executor { command ->
        execute {
            try {
                command.run()
            } finally {
                Thread.interrupted()
            }
        }
    }
}
```

But perhaps `LimitingDispatcher` should clear interrupt flag inside?

**Comment by qwwdfsad** [comment]
Thanks for the report. 

The example with `newCachedThreadPool` works by accident due to its implementation detail -- it uses a blocking queue under the hood. Blocking queues handle interruption by clearing its status and throwing `InterruptedException` that is rightfully ignored by pool implementation. If you replace it with, e.g., `ForkJoinPool`, you'll see that the interruption status is not cleared.

The code in your example. in fact, violates the standard interruption policy. Quoting "Java Concurrency In Practive" 7.1.2 here:

>Tasks do not execute in threads they own; they borrow threads owned by a service such as a thread pool. Code that doesn’t own the thread (for a thread pool, any code outside of the thread pool implementation) should be careful to preserve the interrupted status so that the owning code can eventually act on it, even if the “guest” code acts on the interruption as well.
>...
>A task should not assume anything about the interruption policy of its exe- cuting thread unless it is explicitly designed to run within a service that has a specific interruption policy.

`Dispatchers.Default` is a general-purpose dispatcher that can be used by _any_ library in your application's classpath, so it's not possible to rely on a consistent interruption policy here.
