### ISSUE TITLE
Why is the asFlow() unsafe flow?

### ISSUE THREAD

**Issue by enciyo** [Kotlin/kotlinx.coroutines#2788]
Why do asFlow() methods use unsafeFlow()? 

```
@Test
fun flowCancelattionChecks() = runBlocking<Unit>() {
        (1..5).asFlow() // Unsafe
            .collect { value ->
                if (value == 3) cancel()
                println(value)
            }
}
Output:

1
2
3
4
5
kotlinx.coroutines.JobCancellationException: BlockingCoroutine was cancelled

```

Other Case

```

class FlowCatchUnitTest {

    @Test
    fun flowCancelattionChecks() = runBlocking<Unit>() {
        (1..5).asFlowCustomExt()
            .collect { value ->
                if (value == 3) cancel()
                println(value)
            }
    }

}

@OptIn(InternalCoroutinesApi::class)
fun IntRange.asFlowCustomExt(): Flow<Int> = flow { 
    forEach { value ->
        emit(value)
    }
}

Output:
1
2
3
kotlinx.coroutines.JobCancellationException: BlockingCoroutine was cancelled

```

**Comment by qwwdfsad** [comment]
Hi, good catch!

This is actually an implementation detail that we do not yet decide on how to expose in the documentation.
Cancellation is, by definition, cooperative, but yet for the sake of performance, some safe ("scalar") flow operators do not check cancellation status and we do not really want to give up on this extra-performance on primitive scalar flows.

If you need a deterministic cancellation on each element, please use [`.cancellable()`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/cancellable.html) operator.
Alternatively, instead of `if` in the `collect` body, `takeWhile` can be used

**Comment by enciyo** [comment]
```
import kotlinx.coroutines.flow.internal.unsafeFlow as flow

/**
 * Creates a flow that produces values from the range.
 */
public fun IntRange.asFlow(): Flow<Int> = flow {
    forEach { value ->
        emit(value)
    }
}
```
Thanks for answer. Now, I understand why this approach was used. Maybe a warning can be added to the documentation. Or the  "as flow" can be named differently.

**Comment by qwwdfsad** [comment]
We will definitely attempt to systematically address this issue, but I'm not sure it's worth "fixing" specific primitives or standalone methods right now.
Thanks for the input and an additional data point!
