### ISSUE TITLE
Failed resolution of: Lkotlinx/coroutines/CoroutineExceptionHandler with 1.5.0

### ISSUE THREAD

**Issue by AlanChienYL** [Kotlin/kotlinx.coroutines#2792]
I got error:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/CoroutineExceptionHandler;
```
 
How I implement CoroutineExceptionHandler extension as below:
```kotlin
private val handler = CoroutineExceptionHandler { _, exception ->
}
```

which extension I use: 
![image](https://user-images.githubusercontent.com/14312578/123731043-fe375f80-d8c9-11eb-9ffb-1aedc008ee93.png)

coroutine version : 1.5.0

How can I fix this issue? Thanks..

**Comment by dkhalanskyjb** [comment]
There's too little information to infer what caused this in your case, but this issue means that the Android runtime couldn't find the `CoroutineExceptionHandler` class. This could be a problem with your build scripts, or with the Android tooling, or with a Proguard config, or with a specific device you're testing this on, or something on our side.

Could you show us a project where this problem reproduces? Then we could look at it and tell you what the issue is.

**Comment by AlanChienYL** [comment]
@dkhalanskyjb Thanks for the reply also apologize for the little information. This project is a module. and build with debug mode. means it's not caused by proguard.
It looks fine when I create a test android project. I will try to figure out the problem. Many thanks for reply.

**Comment by dkhalanskyjb** [comment]
Some questions that could help with the investigation:
* Does anything related to coroutines work in this project, or does every use of `kotlinx-coroutines` throw? If it's the latter, it's probably a build script error causing the library not to be included in the runtime classpath.
* Does this reproduce on a device, in the emulator, or both?
* Does this happen with some other versions of coroutines?

**Comment by AlanChienYL** [comment]
Hi @dkhalanskyjb 

> Does anything related to coroutines work in this project, or does every use of kotlinx-coroutines throw? If it's the latter, it's probably a build script error causing the library not to be included in the runtime classpath.

Yes, I have used kotlinx-coroutines throw. I put this line in my `dependency` block -> `implementation Dependencies.Kotlin.coroutines`

> Does this reproduce on a device, in the emulator, or both?

no, it's happened on any devices.

> Does this happen with some other versions of coroutines?

yes.. only 1.5.0, If I rollback to 1.4.3 or 1.4.2, everything is fine.

**Comment by dkhalanskyjb** [comment]
I see, thanks! Another question then: which version of Kotlin (the compiler) do you use? Coroutines 1.5.0 could behave in strange ways when used with a compiler older than 1.5.0.

**Comment by AlanChienYL** [comment]
@dkhalanskyjb my kotlin version is 1.5.20

**Comment by AlanChienYL** [comment]
but if I create a clean project 
kotlin version: 1.5.20
coroutine version: 1.5.0

everything is fine... it's wired.

**Comment by dkhalanskyjb** [comment]
Hmm. It's difficult for me to say more unless you can show us a project where this reproduces. A common approach in such cases is to remove parts of the project that are irrelevant to the problem. What's left is usually a small number of simple files where the problem is still present. If you give us that, the job of finding the issue will be much more simple.

**Comment by AlanChienYL** [comment]
I think the problem is not `CoroutineExceptionHandler`. It's the whole coroutine not include in the module at runtime. I'll keep investigating.

**Comment by AlanChienYL** [comment]
@ddolovov I found the whole project can't use coroutine with 1.5.0. But 1.4.3 is fine. What info can I provide to help investigate this situation? 😢

**Comment by AlanChienYL** [comment]
Hi @ddolovov. The root cause is because our dependency includes `org.aspectj:aspectjrt`. after we exclude `kotlinx.coroutines` everything is working as well. Many thanks for your help. 😄
