### ISSUE TITLE
Multiple consumeEach calls in the same coroutine?

### ISSUE THREAD

**Issue by nickcapurso** [Kotlin/kotlinx.coroutines#281]
Or alternatively, what is the "correct" way to use the same coroutine / coroutine context to consume items from, ex. a `BroadcastChannel`.

For example, with this set up:
```
    val channel1 = ConflatedBroadcastChannel<String>()
    val channel2 = ConflatedBroadcastChannel<String>()

    val sub1 = channel1.openSubscription()
    val sub2 = channel2.openSubscription()
```

My first try was:
```
    private fun doesntWork() {
        launch {
            sub1.consumeEach { Log.d(TAG, it) }
            sub2.consumeEach { Log.d(TAG, it) }
        }
    }
```
but the `sub2.consumeEach` never gets called. I would have thought that while `sub1` was suspended waiting for an item to be sent, that the next line would get to run? What's wrong with my understanding here?

I'm able to get it to work by two separate launches:
```
    private fun works() {
        val job = launch {
            sub1.consumeEach { Log.d(TAG, it) }
        }

        launch(job) {
            sub2.consumeEach { Log.d(TAG, it) }
        }
    }
```
(and/or nesting one `launch` within another, passing `coroutineContext`)

or by using `select`:
```
    private fun works2() {
        launch {
            while(isActive) {
                select<Unit> {
                    sub1.onReceive { Log.d(TAG, it) }
                    sub2.onReceive { Log.d(TAG, it) }
                }
            }
        }
    }
```

What's the "recommended" way to do this? And what am I missing about `consumeEach`?

**Comment by elizarov** [comment]
`consumeEach` behaves so by design. It suspends until all items are received. 

The recommended approach depends on you use-case. 

When actions you need to do on each channel are totally independend (no shared state between them), then using `launch` multiple times is recommended.

When actions you need to do on each channel are dependent and share some state, then the recommended way is to use `select`. That is specifically use-case it was designed for. This way you can listen to multiple channels simultaneously, while keeping your logic and state sequential and easy to reason about.

**Comment by nickcapurso** [comment]
Thanks @elizarov for your answer and suggestions! Makes sense to me now:
> It suspends until all items are received.

Meaning the coroutine will not continue executing (i.e. calling the second `consumeEach`) until all items are received. Using a second launch (or select) allows them to both to run and wait for items.
