### ISSUE TITLE
Dispatchers.Main.immediate

### ISSUE THREAD

**Issue by zhanglixiang779** [Kotlin/kotlinx.coroutines#2816]
Hello Kotlin Coroutine team,

Wonder if this is a bug or due to my misunderstanding of Dispatchers.Main.immediate

In Android, I use lifecycleScope (SupervisorJob() + Dispatchers.Main.immediate) to launch a few coroutines. 

```
val job1 = lifecycleScope.launch { 
            val job2 = launch { 
                Log.d(TAG, "A")
            }

            launch(Dispatchers.Default) { 
                Log.d(TAG, "B")
            }

            Log.d(TAG, "C")
 }
```
Since job1's context inherits from the parent lifecycleScope's context, and then job2's context inherits from job1's context and the code never changed the Dispatcher for job1's and job2's context. I would expect "A" would always gets printed before "B" and "C" based on the following facts: 

1: The context of the scope that launches job2 is Dispatchers.Main.immediate
2: also job2 is executed under Main thread

Even if I explicitly do the following, "A" is still not first printed. 
```
lifecycleScope.launch { 
            launch(Dispatchers.Main.immediate) { 
                Log.d(TAG, "A")
            }

            launch(Dispatchers.Default) { // job3
                Log.d(TAG, "B")
            }

            Log.d(TAG, "C")
 }
```
Fortunately, if do the following, it works ("A" is always the first printed)
```
lifecycleScope.launch(Dispatchers.Main) {
            launch(Dispatchers.Main.immediate) {
                Log.d(TAG, "A")
            }

            launch(Dispatchers.Default) {
                Log.d(TAG, "B")
            }

            Log.d(TAG, "C")
}
```

**Comment by qwwdfsad** [comment]
This question seems to be too general (e.g. because it is questioning the behaviour of `lifecycleScope` as well), please ask it in the corresponding slack channel (`#coroutines` in Kotlin slack).

The answer can be found in the KDoc:

`MainCoroutineDispatcher.immediate`:
>Immediate dispatcher is safe from stack overflows and in case of nested invocations forms event-loop similar to [Dispatchers.Unconfined].
The event loop is an advanced topic and its implications can be found in [Dispatchers.Unconfined] documentation.

`Dispatchers.Unconfined`:
>Event loop semantics is a purely internal concept and have no guarantees on the order of execution
except that all queued coroutines will be executed on the current thread in the lexical scope of the outermost
unconfined coroutine.
> ... example code very similar to yours ...
>Can print both "1 2 3" and "1 3 2", this is an implementation detail that can be changed.
