### ISSUE TITLE
Loop blocks execution.

### ISSUE THREAD

**Issue by Josef-Vonasek** [Kotlin/kotlinx.coroutines#2819]
The following code prints `A`, `B`:
```kotlin
coroutineScope {
    println("A")
    launch {
        while (true) {}
    }
    println("B")
}
```
However, this code will print only `A`:
```kotlin
coroutineScope {
    println("A")
    launch {
        while (true) {}
    }
    launch { println("B") }
}
```

------

Kotlin/Native Windows.

**Comment by qwwdfsad** [comment]
The former code first executes both `println` statements and only then executes `launch` body and hangs.
The latter executes `println`, then goes to the first coroutine that hangs.

The default native dispatcher is single-threaded, so this is expected behaviour.

In the future, for the common questions please consider using stackoverflow of `#kotlin` slack channel.
