### ISSUE TITLE
line numbers in coroutine dump mismatch

### ISSUE THREAD

**Issue by peterfigure** [Kotlin/kotlinx.coroutines#2821]
referring to a dump obtained by sending the process a signal 5. 

the line numbers do not correspond with the kotlin source, I assume it refers to desugared code or maybe something else entirely, is there a way to correlate with actual kotlin source line numbers?

**Comment by qwwdfsad** [comment]
https://discuss.kotlinlang.org/t/stacktrace-points-to-line-after-end-of-file/4129

Kotlin line numbers do not match the source line-numbers due to various factors: generated suspend-functions state machines, inline functions, lambdas and so on.

The easiest way to match them is to use `Analyze stacktrace` function in IDEA
