### ISSUE TITLE
TestCoroutineDispatcher - Unable to use MockK verify with launch

### ISSUE THREAD

**Issue by Teja-Konjeti** [Kotlin/kotlinx.coroutines#2823]
```
val testCoroutineDispatcher = TestCoroutineDispatcher()
val testCoroutineScope = TestCoroutineScope(testCoroutineDispatcher)

class A { fun b() { } }
val mock = mockk<A>()

testCoroutineScope.launch {
    delay(1000)
    mock.b()
}

verify(timeout = 1100) { mock.b() }
```

This fails with `Verification failed: call 1 of 1: A(#3).b()) was not called (timeout = 1100 ms)`

**Comment by dkhalanskyjb** [comment]
Yes, this is expected.
* `TestCoroutineDispatcher` doesn't have its own thread. Instead, its tasks are executed inside calls to `runCurrent`, `advanceUntilIdle`, and such. So, there is no parallelism here.
* `verify` blocks the current thread until the condition is fulfilled or the timeout happens. Therefore, nothing else can happen in the meantime even in theory.
* `TestCoroutineDispatcher` is special in that it uses virtual time, not real time, to process delays. This is done so that, in tests, calls to `delay()` are immediately skipped. So, waiting for `1100` ms doesn't do anything to advance the test dispatcher: the virtual time is still at `0`.

**Comment by Teja-Konjeti** [comment]
@dkhalanskyjb I understand that the behaviour is as expected, my follow-up question is how do you handle such tests? I strongly believe that this dispatcher won't be useful at all in such cases and won't go out of experimental without having this key issue addressed..

**Comment by dkhalanskyjb** [comment]
I agree that this dispatcher isn't useful here, as it's meant to be used for testing coroutines, while `verify` doesn't suspend and is instead a plain blocking call. Could you clarify why you need to use `TestCoroutineDispatcher` in this case and not, say, `Dispatchers.Default`?

**Comment by Teja-Konjeti** [comment]
In some of my use cases, there is a socket connection (which I'm mocking and answering with a delay in scope.launch). In these use cases, I wanted to use this dispatcher to speed my test cases up..

I'm wondering is there a way to calculate the delays in all the statements and execute them in order to fix this specific issue?

**Comment by dkhalanskyjb** [comment]
I'm not familiar with MockK, but `verify` can be used to check that something has already happened:
```kotlin
        val testCoroutineDispatcher = TestCoroutineDispatcher()
        val testCoroutineScope = TestCoroutineScope(testCoroutineDispatcher)

        class A { fun b() { } }
        val mock = mockk<A>()

        testCoroutineScope.launch {
            delay(1000)
            mock.b()
        }

        testCoroutineScope.advanceUntilIdle() // finish the call to `launch`

        verify { mock.b() }
```
So, MockK can be used in single-threaded scenarios too, even without any timeouts, by ensuring a specific order of events. Otherwise, you could use multiple threads (by creating a new thread-based dispatcher, or by running the code in a separate dispatcher, like `Dispatchers.Default`) and run these checks in parallel, if this is what your use case requires.

> I'm wondering is there a way to calculate the delays in all the statements and execute them in order to fix this specific issue?

Nope, not possible.
```kotlin
if (getUserResponse()) {
  delay(100)
} else {
  delay(1000)
}
```
Unless we can completely predict how all the code executes, calculating delays is impossible, and I don't even know how it could help here.

**Comment by Teja-Konjeti** [comment]
I feel that the best way is to pause the dispatcher and make a utility function to call the verify and implement timeout by advanceTimeBy(). This will solve all the multi threading issues.

Can you share your thoughts and any corner cases I'm missing on this?

**Comment by dkhalanskyjb** [comment]
It looks to me like there is only a single thread used in the solution you're proposing, so which multi-threading issues are you referring to?

Other than that, it does look like it can work.

**Comment by Teja-Konjeti** [comment]
I mean the issues with launch, but this doesn't seem to work as well..

```
val testCoroutineDispatcher = TestCoroutineDispatcher()
val testCoroutineScope = TestCoroutineScope(testCoroutineDispatcher)

fun teVerify(
            ordering: Ordering = Ordering.UNORDERED,
            inverse: Boolean = false,
            atLeast: Int = 1,
            atMost: Int = Int.MAX_VALUE,
            exactly: Int = -1,
            timeout: Long = 0,
            verifyBlock: MockKVerificationScope.() -> Unit
    ) {
        testCoroutineDispatcher.advanceTimeBy(timeout)
        verify(ordering, inverse, atLeast, atMost, exactly, timeout, verifyBlock)
    }

class A { fun b() { } }
        val mock = mockk<A>()

        testCoroutineScope.launch {
            delay(1000)
            mock.b()
        }

        teVerify(timeout = 1100) { mock.b() }
```

**Comment by dkhalanskyjb** [comment]
For me, the test passes, and if I change the timeout to `900`, the test fails. Is this not the intended behavior?

**Comment by Teja-Konjeti** [comment]
Yes, that is the intended behaviour..

**Comment by Teja-Konjeti** [comment]
Something with my other code was conflicting, this works when I run it independently 😄 .

Do you see any corner cases with this implementation?

**Comment by dkhalanskyjb** [comment]
Well, if you launch more than one task, `advanceTimeBy` will affect them all, which will seem extremely weird: why does a verification function cause some unrelated code to start executing? Also, I'm not sure what the purpose is of passing `timeout` to `verify` as well, instead of just to `advanceTimeBy`.

**Comment by Teja-Konjeti** [comment]
If you're using only MockK in the test cases to verify a certain test case's validity, in that case, this makes sense to execute all the code blocks that are to be executed before the timeout, but the only problem I see with this is

1. A function that actually does some huge processing and takes time (say more than 1000 ms)
2. the verify with a timeout of 1000 ms should ideally fail, but it passes in this scenario because it is being executed and on the same thread first.

This will also cause issues if the test cases are larger as the delays will not be easy to track. Generally, my test spec parent class resets all mocks and CoroutineScopes before running another test, so this should not be a problem for me.

**Comment by dkhalanskyjb** [comment]
It is possible to use `withTimeout` to verify that a task executes in time.
```kotlin
class A { fun b() { } }
val mock = mockk<A>()

@Test
fun test() = runTest {
    withTimeout(1100) {
        delay(1000)
        mock.b()
    }
    verify { mock.b() }
}
```
The test will fail if the delay is changed to 1100, but will still execute immediately.

`withTimeout`, when run inside `runTest`, will use the virtual time, not the actual time.

If you have any questions, feel free to reopen this issue or file a new one.
