### ISSUE TITLE
Add `Flow<T>?.orEmpty(): Flow<T>` operator

### ISSUE THREAD

**Issue by RinOrz** [Kotlin/kotlinx.coroutines#2905]
This helps protect the continuity of API calls:
`list?.asFlow().orEmpty()`

```kotlin
public inline fun <T> Flow<T>?.orEmpty(): Flow<T> = this ?: emptyFlow()
```

Reference `List.orEmpty`

**Comment by qwwdfsad** [comment]
Could you please elaborate on how often do you encounter such a pattern?

It is not our goal to replicate stdlib Colllection API here and `?: emptyFlow()` seems quite consice

**Comment by RinOrz** [comment]
```kotlin
(list?.asFlow() ?: emptyFlow())
  .onEach {}
  .collect()
```

vs

```kotlin
list?.asFlow()
  .orEmpty()
  .onEach {}
  .collect()
```

The first undoubtedly disrupted the coherence when entering the code

**Comment by dkhalanskyjb** [comment]
Couldn't you just use
```kotlin
list?.orEmpty()
  .asFlow()
  .onEach {}
  .collect()
```
here instead of introducing a new operator?

**Comment by RinOrz** [comment]
> Couldn't you just use
> 
> ```kotlin
> list?.orEmpty().asFlow()
> ```
> 
> here instead of introducing a new operator?

Sometimes it may not be a List, maybe the nullable Flow returned elsewhere, or something.

**Comment by dkhalanskyjb** [comment]
In the case of `value?.let(::flowOf)`, why would a flow even be needed?

The reason we're asking this is that adding new methods is not at all free. Mostly because it clutters auto-completion, but also because it requires people to remember more definitions when reading the code, etc. Because of this, we only add new functionality when we believe that either
1. it's commonly needed, or
2. it isn't easy to implement correctly in the client code.

Case 2 clearly doesn't apply here. In order to decide whether case 1 applies, we need to know of specific, real-world cases where this function would be useful and conclude that, yes, `Flow<T>?` really must be a common thing. If it's needed rarely, then it's not a problem if some codebase has a `?:` instead of `?.`: it's still nicely readable. Could it be more nicely readable? Sure. Is adding a new method to improve readability worth it? This is what we want to discuss.

**Comment by fvasco** [comment]
`flow?.onEach { }?.collect()` looks OK for this use case.
