### ISSUE TITLE
Consider changing default capacity of actor's mailbox

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#293]
Currently actors have no mailbox by default (`capacity = 0`) which effectively transforms them to rendezvous. Though ability to have such actors may be useful, this default is unexpected and probably will lead to less efficient/expected behaviour.
As an example, specifying capacity to `1` in `PingPongActorBenchmark` significantly improves score in every setup (fjp, blocking, single thread executor).

It makes sense to either increase this limit to any reasonable constant or make mailbox unlimited by default (as it's done in Akka). Note that this change **may** break existing code and/or change its behaviour

**Comment by venkatperi** [comment]
A few thoughts:

* Making channel capacity unlimited invites memory issues. e.g. channels upstream from a blocking channel may continue to allocate buffers while there is incoming data and eventually run out of memory.
* A large but bounded number of buffers may be inefficient both in terms of memory and also latency, since data may sit in numerous unneeded queues before being consumed.
* `capacity=1` - is like the `ping` in a `ping-pong` scheme. 
* `capacity22` - ping/pong scheme isn't ideal for real world cases where it takes a small but finite amount of time to fill a buffer
* `capacity=3` - e.g. an video camera where one buffer is filled while a previously filled buffer is processed. `ping, pong plus one` works better otherwise either of the previous processes may be starved and result in reduce throughput.
* `NodeJS` uses a default capacity of `16` for `object` types. 

**So 4?**

**Comment by elizarov** [comment]
I would not hard-code a default capacity, but, at least, make it configurable via some kind of system property. For me, personally, a default values from 4 to 16 all seem reasonable. 

Also, I would not record it separately, but it seems prudent to set actor's default value of `start` parameter to `CoroutineStart.LAZY`. See #87

**Comment by qwwdfsad** [comment]
Will be fixed in new actors, current ones are going to be deprecated
