### ISSUE TITLE
Hash/Event channel

### ISSUE THREAD

**Issue by plokko** [Kotlin/kotlinx.coroutines#301]
Hi, and thank to everyone that is working on this marvelous new language!

I want to know if there is a way to make an hash based channel where N coroutines waits for an event and are all are waken-up when that event is fired by another background process/coroutine.
I would like also to enqueue and process the request only one time by the backgroud process if possible.

I tried to simulate this with a channel that wakes up the background process and an hashmap of array of continuations that needs to be waked up after the process is complete (don't mind the naming).
```kotlin
import kotlinx.coroutines.experimental.channels.Channel
import kotlinx.coroutines.experimental.delay
import kotlinx.coroutines.experimental.launch
import kotlin.coroutines.experimental.Continuation
import kotlin.coroutines.experimental.suspendCoroutine

class DownloadQueue {

    internal val queue = HashMap<String,ArrayList<Continuation<Unit>>>()

    val channel = Channel<String>(Channel.UNLIMITED)

    val process = launch{
            for(name in channel){
                println("Start processing $name!")

                val listeners = queue.get(name);

                try{
                    //Simulated processing
                    delay(1000L)

                    println("End processing $name, notifying...")

                    listeners?.forEach { cont ->
                        cont.resume(Unit)
                    }
                } catch(e:Exception){
                    listeners?.forEach { cont ->
                        cont.resumeWithException(e)
                    }
                }
                println("End processing $name!")
                //

            }
    }

    @Synchronized
    fun add(name:String, onComplete: Continuation<Unit>?=null){

        val orig = queue.get(name);
        val list = orig ?:ArrayList<Continuation<Unit>>()

        if(onComplete!=null){
            list.add(onComplete)
        }
        queue.set(name,list)
        //Wakeup actor
        if(orig==null) {
            println("newlist for $name")
            channel.offer(name)
        }
    }

    suspend fun enqueue(name:String):Unit = suspendCoroutine { cont ->
        add(string, cont)
    }

    fun inQueue(name:String):Boolean = queue.get(name)!=null
}
```
If we do for example:
```kotlin
        val q = DownloadQueue()
        val j1 = launch{
            for(i in 1..3){
                async{
                    val x = "$i"
                    println("A>>$x")
                    q.enqueue(x)
                    println("A<<$x")
                }
            }
        }
        val j2 = launch{
            for(i in 2..5){
                async {
                    val x = "$i"
                    println("B>>$x")
                    q.enqueue(x)
                    println("B<<$x")
                }
            }
        }
```
the background service will process 1,2,3,4,and 5 (in a first-added first served manner, it's not always linear) only one time per number;
for 2 and 3 two processes will be waiting for the same result.

I don't want to re-invent the wheel but i could not find anything that would do what i wanted for now.

**Comment by elizarov** [comment]
There is nothing "out-of-the-box" that solves the problem, but it can be readily solved with primitives from `kotllinx.coroutines`. In order to arrive at a solution that is easy to reason about, you should not have any shared mutable state in your code. Attempts to throws in `@Synchronized` and other things like that make solution overly complicated and buggy (in your code there is a data race -- you don't synchronize when reading from `queue` in `process` method).

I would have solved this particular problem with two interacting actors. One actor to perform the actual downloads. We are using `Channel.UNLIMITED` capacity here so that it acts as our FIFO download queue:

```
private val processor: SendChannel<String> = actor(capacity = Channel.UNLIMITED) {
        for (name in channel) {
            println("Start processing $name!")
            ...
            println("End processing $name!")
        }
    }
```

And another  actor to manage a queue of listeners:

```
   private val manager: SendChannel<Msg> = actor {
        val requests = HashMap<String, ArrayList<Msg.Request>>()
        for (msg in channel) {
            ...
        }
    }
```

This `manager` actor will support two operations: to add a download request and to report a dowload result to all the requestors:

```
    private sealed class Op {
        class Request(val name: String) : Op() {
            val answer = CompletableDeferred<Unit>()
        }
        class Result(val name: String, val error: Throwable? = null) : Op()
    }
```

We use `CompletableDeferred` class instead of working with continuations directly. In this way, our main `enqueue` function is a simple wrapper on that interacts with `manager` actor:

```
    suspend fun enqueue(name: String) {
        val req = Msg.Request(name)
        manager.send(req)
        req.answer.await()
    }
```

The manager, actor, in turn, maintains a map of lists of requests and  interacts with `processor`:

```
            when (msg) {
                is Msg.Request -> {
                    requests.getOrPut(msg.name) {
                        // send to processor when the first request comes in
                        processor.offer(msg.name) // would always succeed
                        ArrayList()
                    } += msg // add to the list
                }
                is Msg.Result -> {
                    for (resp in requests.remove(msg.name)!!) {
                        if (msg.error != null)
                            resp.answer.completeExceptionally(msg.error)
                        else
                            resp.answer.complete(Unit)
                    }
                }
            }
```

And `processor` simulates the actual processing and reports result to `manager`:

```
            try {
                //Simulated processing
                delay(1000L)
                println("End processing $name, notifying...")
                manager.send(Msg.Result(name))
            } catch (e: Throwable) {
                manager.send(Msg.Result(name, e))
            }
```

The full code with a test is here: https://gist.github.com/elizarov/34de14377c6a1caf50d560b35a47adc0

**Comment by plokko** [comment]
Thanks a lot @elizarov !
I was sure `Synchronized` was not the right approach and i expected a correction:
i will re-implement using your example. 👍 

Why isn't there a coroutine implementation for waiting for an event like `EventChannel.awaitForEvent('event-name')` ?
I see a lot of possible application for it.

I looked at `BroadcastChannel` but i think it does the opposite (send a message to multiple waiting coroutines) 

**Side note:** when i was testing actors and channel i had unexpected results because i was expecting the capacity to be set to unlimited if not specified, it should be better pointed out in the docs in my opinion.

**Comment by elizarov** [comment]
There are too many things you can do with coroutines and channels. We cannot provide all of them in a way that people are able to discover. We plan to concentrate on core primitives. However, the is a request for a similar request-like abstraction. I wonder if that would help you somehow, too: #145 

As for default capacity, `UNLIMITED` is too risky as a default for may channel-using applications. Without special precautions it will easily result in out-of-memory error. See, in my code I use `UNLIMITED`, because I know I'm never going to put too many requests there -- I store them all into the map first. The default that we chose is safer.

**Comment by plokko** [comment]
I do perfecly undestand why `UNLIMITED` is not the default value, the only thing i'm questioning is that [in the docs](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#channels) it's not clearly pointed out and it could be misleading for a newcomer.

Thanks again for the help!
