### ISSUE TITLE
Making Test(Coroutine)Scope `sealed` breaks my entire test suite

### ISSUE THREAD

**Issue by fluidsonic** [Kotlin/kotlinx.coroutines#3070]
I have the following "scope" interface for all my integration tests (and similar in other kinds of tests):

```kt
interface IntegrationTestScope : TestCoroutineScope {
	val client: IntegrationTestClient
	val server: IntegrationTestServer
}

class IntegrationTestScopeImpl(
	override val client: IntegrationTestClient,
	coroutineScope: TestCoroutineScope,
	override val server: IntegrationTestServer,
) : IntegrationTestScope, TestCoroutineScope by coroutineScope
```

That is to keep `TestCoroutineScope` functionality in scope while also adding custom functionality.

In 1.6.0-RC that doesn't compile anymore.
> Inheritance of sealed classes or interfaces from different module is prohibited

Same with the new `TestScope`.
What's the reason to make the old one suddenly `sealed`?
That's a source-breaking change. And it's not listed as a breaking change in the release notes.

The code of `TestCoroutineScope` has this `@Deprecated` comment:
> Since 1.6.0, ERROR in 1.7.0 and removed as experimental in 1.8.0

Unfortunately it's already an error in 1.6.0 due to `sealed`.

What's the suggested path forward?

**Comment by dkhalanskyjb** [comment]
> What's the reason to make the old one suddenly `sealed`?

The reason is that `TestScope` and `TestCoroutineScope` have very brittle behavior that could easily be broken by inheriting from them. For example, even before this, doing `testScope.runBlockingTest` would run the passed block not in the `testScope` but in a new scope with the same context. This significantly obscures the intent and the behavior of the code.

> What's the suggested path forward?

We couldn't think of any use cases for someone inheriting from `TestCoroutineScope`. However, given that it causes breakage after all, maybe we should un-seal it in the next RC, given how it's deprecated anyway.

As for what can be done on your side, please see the migration guide: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md#testcoroutinescope In essence, if you use `testScope.runBlockingTest`, replace it with `runBlockingTest(testScope.coroutineContext)`. Then, nothing in our API will accept the `TestCoroutineScope` as an argument, and you can just not implement `TestCoroutineScope`.

Does this work for you?
