### ISSUE TITLE
FlowCollector fun interface errors due to collect being InternalCoroutinesApi

### ISSUE THREAD

**Issue by Tolriq** [Kotlin/kotlinx.coroutines#3078]
As per the title the change in 1.6 RC2 breaks code that are copy pasted from Compose for example:

```
@Composable
fun <T : R, R> Flow<T>.collectAsState(
    initial: R,
    context: CoroutineContext = EmptyCoroutineContext
): State<R> = produceState(initial, this, context) {
    if (context == EmptyCoroutineContext) {
        collect { value = it }
    } else withContext(context) {
        collect { value = it }
    }
}
```

Will produce `This is an internal kotlinx.coroutines API that should not be used from outside of kotlinx.coroutines. No compatibility guarantees are provided. It is recommended to report your use-case of internal API to kotlinx.coroutines issue tracker, so stable API could be provided instead`

**Comment by ZacSweers** [comment]
#3082 removes it from some implementation classes, but I don't see how that resolves this since those implementation classes are usually opaque to users. Most code is solely collecting from a `Flow` itself, which still only has an `@InternalCoroutinesApi`-annotated collect() function. Am I missing something? It seems like the extension function was the _only_ way to collect in the public API.

**Comment by ZacSweers** [comment]
Scratch that, I see it's merged into `develop` and not `master`. Apologies for the noise!

**Comment by bubenheimer** [comment]
Seems odd that this did not get caught by automated testing or even just building the tests, pre-release. Maybe add or change something to capture this kind of scenario?

**Comment by LouisCAD** [comment]
I think the tests run with opt-in for the `@InternalCoroutinesApi`.
