### ISSUE TITLE
R8 has built-in support for ServiceLoader, Proguard rules need update

### ISSUE THREAD

**Issue by vvb2060** [Kotlin/kotlinx.coroutines#3111]
https://r8.googlesource.com/r8/+/c93796dcf5f2f74d7c3817926cbfbf3122096a74

```java
    private final ProguardPathFilter.Builder adaptResourceFilenames =
        ProguardPathFilter.builder()
            .addPattern(ProguardPathList.builder().addFileName("META-INF/services/*").build());
    private final ProguardPathFilter.Builder adaptResourceFileContents =
        ProguardPathFilter.builder()
            .addPattern(ProguardPathList.builder().addFileName("META-INF/services/*").build());
```
R8 use `-adaptresourcefilenames` and `-adaptresourcefilecontents` to handle `META-INF/services/*`,  which I think is better than `-keep` or `-keepnames`: https://www.guardsquare.com/manual/configuration/examples#resourcefiles

The following rules can be removed:
```
-keep class kotlinx.coroutines.android.AndroidDispatcherFactory {*;}
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
```
https://github.com/Kotlin/kotlinx.coroutines/blob/722cf5fd4359374dbbedfadf62af76e970f767bc/ui/kotlinx-coroutines-android/src/AndroidExceptionPreHandler.kt#L13-L15

**Comment by agrieve** [comment]
I was just looking at this as well, and it turns out that:
a) There is still a -keep rule in [kotlinx-coroutines-android](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/kotlinx-coroutines-android/resources/META-INF/com.android.tools/r8-from-1.6.0/coroutines.pro#L12) that should be removed, and
b) R8 [natively supports](https://b.corp.google.com/issues/120436373#comment8) `META-INF/services` / `ServiceLoader.load` since `1.5`, so there's also no need for `-adaptresourcefilecontents` / `-adaptresourcefilenames`
