### ISSUE TITLE
callbackFlow.last() never answer

### ISSUE THREAD

**Issue by eliascoelho911** [Kotlin/kotlinx.coroutines#3125]
Hi! 

I'm trying to use `callbackFlow.last()`, but it always hangs the thread and never responds at all. When I call `flow.last()`, responds normally to the call. Another interesting detail is that if I run `callbackFlow.take(2).last()` it works normally. And if I run `callbackFlow.collect {}`, it blocks a thread until the callbackFlow ends. Below is sample code, along with the output I get on the console, plus other relevant information.

**Code:**
```
fun main(args: Array<String>) {
    val callbackFlow = callbackFlow {
        with(StringRepository()) {
            object : Callback<String> {
                override suspend fun onSuccess(item: String) {
                    send(item)
                }

                override suspend fun onFailure(throwable: Throwable) {
                    cancel(throwable.message.toString(), throwable)
                }
            }.let { callback ->
                addCallback(callback)
                awaitClose { removeCallback(callback) }
            }
        }
    }

    val flow = flowOf("Teste 1", "Teste 2", "Teste 3")

    runBlocking {
        println("flow first - ${flow.first()}")
        println("flow last - ${flow.last()}")
        println("callbackFlow take last - ${callbackFlow.take(2).last()}")
        println("callbackFlow first - ${callbackFlow.first()}")
        println("callbackFlow last - ${callbackFlow.last()}")
    }
}

class StringRepository {
    suspend fun addCallback(callback: Callback<String>) {
        callback.onSuccess("Teste 1")
        callback.onSuccess("Teste 2")
        callback.onSuccess("Teste 3")
    }

    fun removeCallback(callback: Callback<String>) {
        //do nothing
    }
}

interface Callback<T> {
    suspend fun onSuccess(item: T)

    suspend fun onFailure(throwable: Throwable)
}
```

**Console:**
```
flow first - Teste 1
flow last - Teste 3
callbackFlow take last - Teste 2
callbackFlow first - Teste 1
```

**Versions:**

- kotlin: 1.5.31
- coroutines-core: 1.6.0

**Comment by mhernand40** [comment]
In order for `Flow.last()` to return a result, the `Flow` has to terminate. Without a termination, it is still waiting for the signal to receive the "last" item. The reason why it works when you use `take(2).last()` is because `take(2)` transforms it into a `Flow` that emits two values and then terminates.

If you want your `callbackFlow` to terminate, you need to call `close()` after sending the item. This essentially turns the `callbackFlow` into a one-shot `Flow` that emits a single value and then terminates. Once termination is introduced, `last()` will return a value.

Side note: If all you need is to wrap a one-shot callback (success or failure), it is probably better to use either [suspendCancellableCoroutine](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/suspend-cancellable-coroutine.html) if the API supports cancellation or [suspendCoroutine](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines/suspend-coroutine.html) this way it becomes a regular `suspend` function.

**Comment by eliascoelho911** [comment]
I understand what was said about the connection. I already imagine that was it. the reason I use `callbackFlow `is not as simple as I showed above. I just tried to do something more didactic up there. Contextualizing my real problem: I have a `Firebase Firestore` (which is a live database) that I convert to a `flow`. That's why I use `callbackFlow`. At any given time, i need to perform an action that should only be performed once, and depends solely on the last item sent in the `callbackFlow`. how do you recommend that i break this connection?

obs: I don't have fluent English, so I used google translator. Forgive me if something is unclear

**Comment by mhernand40** [comment]
Understood. And thank you for providing your specific use case. If at a specific moment you need to collect just a single value from a `Flow` and then move forward, it may actually make more sense to use `Flow.first()`. `Flow.first()` will simply return whatever value gets emitted at that very point in time when the call is made.

Let me try and show with an example:
```Kotlin
val db = MyDatabase()
val dbFlow = callbackFlow {
    // Register callbacks here and emit
    // db values as they arrive.
}
db.setValue("A")
db.setValue("B")
db.setValue("C")

// By this point, dbFlow has NOT done any work yet because no one has started collecting from it.
// The db, however should have its current state set to value="C".

val currentDbValue = dbFlow.first()

// Collection of the flow begins at dbFlow.first(). At that point, it should emit the current value "C"
// from the database.
assert(currentDbValue == "C")
```

**Comment by eliascoelho911** [comment]
I understand what you said. The problem with this is that I really need to work with the most up-to-date data. Is there any way to fetch the last data emitted by the `last()` call in a `callbackFlow`?

**Comment by eliascoelho911** [comment]
Thanks
