### ISSUE TITLE
Multiplatform tests does not like calling `suspend` from `launch`

### ISSUE THREAD

**Issue by dcvz** [Kotlin/kotlinx.coroutines#3230]
While working on testing some multiplatform code that does networking, we ran into some weird bugs - using new memory model:

1. We could not test code that uses `scope.launch` to run a network call via ktor.
It seemed somehow the async code was not executing and going straight to the assert:

```kotlin
@Test
fun `this test fails`() = runTest {
    // tested is a view model
    tested.makeNetworkRequest() // non-suspending, makes ktor suspending call via scope.launch

    val expected = ResultModel(state: "some")

    // yield() nor advanceUntilIdle() help
    assertEquals(expected, tested.result.value)
}
```

2. We realized that it works fine, if the async function being tested is a suspend method

```kotlin
@Test
fun `this test passes`() = runTest {
    // tested is a view model
    tested.makeNetworkRequest() // SUSPENDING, makes ktor suspending call directly

    val expected = ResultModel(state: "some")

    assertEquals(expected, tested.result.value)
}
```

3. We made a small test calling a suspend function to see if that is the issue
and it fails with yield() but passes with advanceUntilIdle()

```kotlin
private suspend fun getResult(): String {
    delay(1)
    return "success"
}

@OptIn(ExperimentalCoroutinesApi::class)
@Test
fun scopeTest() = runTest {
    var result = ""

    testScope.launch {
        result = getResult()
    }

    yield() // fails, but advanceUntilIdle() passes
    assertEquals(result, "success")
}
```
4. But we could not get it to work with calling a ktor suspending function no matter `yield` or `advanceUntilIdle`

```kotlin
@OptIn(ExperimentalCoroutinesApi::class)
@Test
fun scopeKtorTest() = runTest {
    var result: List<Data> = emptyList()

    testScope.launch {
        result = api.getData().data // suspending function, works if you call it without the testScope.launch
    }

    yield() // fails, advanceUntilIdle() too
    assertNotEquals(result, emptyList())
}
```

Definition of testScope:
```
private val testDispatcher = StandardTestDispatcher()
private val testScope = TestScope(testDispatcher)
```

**Comment by dkhalanskyjb** [comment]
Please use the public Slack channel for general questions.

I think the reason for this behavior is that `tested.makeNetworkRequest()` doesn't know about the test framework. In order to test entities that make `launch` calls, one should mock the coroutine dispatchers that they use. Otherwise, `yield` (which yields the thread to other coroutines on the same dispatcher) or `advanceUntilIdle` (which runs all pending tasks on dispatchers linked to `runTest`) won't do anything.

For example,
```kotlin
class EntityUnderTest(private val ioDispatcher = Dispatchers.IO) {
  val scope = CoroutineScope(ioDispatcher)
  fun doSomething() {
    scope.launch {
      // X
    }
  }
}

@Test
fun testEntity() = runTest {
  val entity = EntityUnderTest(StandardTestDispatcher(testScheduler))
  entity.doSomething()
  advanceUntilIdle() // will run X
}
```

Didn't check the code in the IDE, there may be typos.

Regarding point 3, it is expected that `yield` doesn't work, as
* It only ensures that the coroutine runs until the next suspension. In this case, until the call to `delay`. So, even if the delay was 0, you would still need at least two `yield` calls.
* The current virtual time at the moment of `yield` is 0, and after `yield`, it's still 0, but the call to `delay` only resumes from sleep at the virtual time 1. `advanceUntilIdle` advances the virtual time until there are no pending tasks.
