### ISSUE TITLE
Migration guide is just awful

### ISSUE THREAD

**Issue by NinoDLC** [Kotlin/kotlinx.coroutines#3237]
Section `Replace advanceTimeBy(n) with advanceTimeBy(n); runCurrent()` makes no sense. It doesn't explain if it's "the new normal" that `advanceTimeBy` won't execute the tasks scheduled **at** the time. To this point, I still have no idea if this is intended or a regression, my test code is now full of `advanceTimeBy(n); runCurrent()`. The migration guide implies that I won't have to use this inelegant code at the end of migration, but I still have to. 

Sections `Replace runBlockingTest with runTest(UnconfinedTestDispatcher())` and `Replace runBlockingTest with runBlockingTestOnTestScope` want me to replace the same code (`runBlockingTest `) by 2 different things. What should I use ? `runBlockingTestOnTestScope` is deprecated so I guess it's the former, but it has the `advanceTimeBy(n); runCurrent()` regression, so in the end I'm confused. 

Section `Replace TestCoroutineDispatcher with UnconfinedTestDispatcher and StandardTestDispatcher` doesn't explain which TestDispatcher or the differences between the 2. 

Overall, it feels way too complicated with way too much "intermediate but still deprecated" steps. 

I'd gladly do a PR to improve this guide with a "1.5 code vs 1.6 code comparison" to help, but I can't manage to finish the migration myself. :(

**Comment by qwwdfsad** [comment]
This is a wrong place to express your frustration, especially if you would like to receive any further help and/or advice in a timely manner.
You can also seek for advice in coroutines Slack channel or StackVverflow as there are plenty of people who succeeded in their migration.

>Overall, it feels way too complicated with way too much "intermediate but still deprecated" steps.

These steps are intentional, so people can migrate any piece of code **gradually** without having to rewrite everything (`runTest`, scopes, captors, controllers, etc.) at once and can have their code runnable and working after each step.
This reasoning is written **at the very beginning** of the document:
> This is a guide for gradually adapting the existing test code to the new API. This guide is written step-by-step; the idea is to separate the migration into several sets of small changes.



>want me to replace the same code (runBlockingTest ) by 2 different things

**`A version of [runBlockingTest] that works with [TestScope]`**  is also written in the docs.

If you need to have an obsolete `runBlockingTest` behaviour with new `TestScope` interface with migration, this method is for you.

> It doesn't explain if it's "the new normal" that advanceTimeBy won't execute the tasks scheduled at the time

I'm not sure why do you mean by this. Both guide and KDoc explicitly says that the new behaviour of a non-deprecated method is not to run scheduled tasks at the very end of the interval. 


>makes no sense.
> I still have no idea if this is intended or a regression

This is a wrong way to ask anyone about anything

**Comment by dkhalanskyjb** [comment]
> This is a wrong place to express your frustration, especially if you would like to receive any further help and/or advice in a timely manner.

I guess you're technically wrong, since the tone here prompted you to respond quickly!

Some additions:

> The migration guide implies that I won't have to use this inelegant code at the end of migration

It does not. It states that you won't have *deprecated* code. We can't make your code elegant for you.

> It doesn't explain if it's "the new normal"

It is, we consider the previous behavior incorrect.

> What should I use ?

There are several paths which you can take to get rid of deprecated code. The specific path depends on your code and which functionality you use the most.

> Overall, it feels way too complicated with way too much "intermediate but still deprecated" steps.

We don't see a way around this, since the API was more or less completely reworked.

**Comment by NinoDLC** [comment]
> This is a wrong place to express your frustration
Where else then ? It's not about frustration, it's about the fact I can't manage to do a migration guide. If I can't understand a guide written on Github while I have *some* skills about it, I should at least voice it and / or try to improve it. As said, I can't follow the guide to make my code work so I can't improve it by myself ; maybe you can !

> It does not. It states that you won't have deprecated code. We can't make your code elegant for you.
It... does ?! `Alternatively, you can wait until replacing TestCoroutineScope with TestScope: it's possible that you will not encounter this edge case.` : you clearly say that this "edge case" with this inelegant code won't likely be encountered if you do multiple steps at a time. This inelegant code looks like an intermediate step. This leads to :

> It is, we consider the previous behavior incorrect.
How so ? You explain *what* to do, but not *why*. It doesn't make sense to me why it was "bad". Also, I can't blindly follow a complex guide on a complex API without understand what I'm doing. There's also lots of bugs so it doesn't help ! 

The previous API was so so much better, so much more understandable. You want stuff not to run immediately ? Just `pauseDispatcher()`. Clear, concise, expressive unit test. The new API is hard to understand (you need to understand the difference between `UnconfinedTestDispatcher` and ` StandardTestDispatcher` to understand the consequences of using one or another in your test), hard to change (let's be honnest, TestDispatchers are almost always provided with @Rule or TestExtensions, so basicaly you would need 2 @Rules or 2 TestExtensions). 

As a maintainer, you feel the behavior incorrect. That's great, you are so much more knowledgeable than I am on the subject. But don't forget that there were thousands of users using the previous API with "basic needs" that were entirely fulfilled with the previous version. Introducing such breaking changes only for a minority of extreme edge cases seems like a bad idea on my side (the "basic happy user").

> There are several paths which you can take to get rid of deprecated code. The specific path depends on your code and which functionality you use the most.
This is not explained at all. `This guide is written step-by-step` means we should follow each step, one at a time, in the chronological order, like any other step-guide, doesn't it ?

> We don't see a way around this, since the API was more or less completely reworked.
Once I get this working I will propose a PR with a "if you have this code before, then you should have this code after" comparison. Helps a lot against this kind of "overwelming" guide. 

> A version of [runBlockingTest] that works with [TestScope] is also written in the docs
If I'm reading a 10 pages long migration guide, I shouldn't search for an answer in the docs, please. 

> This is a wrong way to ask anyone about anything
How so ? I can't understand "the new normal" from the doc, or from the guide, or from "experimentation" (I have bugs, check the other issues). So I'm genuinely wondering if "is it a bug or a feature" because it doesn't make sense to me. 

All I want is : 
* understand what changed, 
* *why* the previous was bad (remember, to me, simple user, it was fine !), 
* what was improved (I guess there's new edges cases that I could test now ?)
* a before / after comparison (the end of the guide is great but way too small : it doesn't show dispatcher injection, time manipulation, usage with flows, etc)

The actual documentation doesn't answer these questions *to me* (maybe I'm dumb, I get it), so I voice my concern to the maintainer. No hard feeling towards anyone, FYI. If you feel i'm not polite to you (not your "code" or "documentation", these need to be criticized), please let me know, this is not my intention.

**Comment by dkhalanskyjb** [comment]
> As said, I can't follow the guide to make my code work so I can't improve it by myself ; maybe you can !

Maybe. If you highlight some specific issues that you're having and it turns out that the guide doesn't cover them, we'll be glad to adapt it. In fact, we have done so in response to user feedback in the past.

> it clearly says that this "edge case" with this inelegant code won't likely be encountered if I do multiple steps at a time

Nope, it says what it says: this step may be skipped (for now), and the code may still keep working, because most tests that we've seen that use `advanceTimeBy(delta)` don't need to run the tasks scheduled at *exactly* `currentTime + delta`, `currentTime + delta - 1` is sufficient for them.

> How so ? It explains what to do, but not why.

As you said, this is a 10-page migration guide. We didn't want it to turn into a 30-page guide that also explained our reasoning. Instead, we wrote a to-the-point instruction for getting rid of the deprecated APIs.

> I have "bugs", check the other issues

I answered those issues and didn't see any bugs on our side. If you feel that the previous API better provided for your use cases, please feel free to report this.

> the end of the guide is great but way too small : it doesn't show dispatcher injection, time manipulation, usage with flows, etc

Maybe the general issue is that the new API is difficult to understand for you? If so, maybe
https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/README.md would provide a good entry point?
