### ISSUE TITLE
A ComparisonFailureException inside a runTest doesn't make it "fail"

### ISSUE THREAD

**Issue by NinoDLC** [Kotlin/kotlinx.coroutines#3239]
```
@ExperimentalCoroutinesApi
class WtfMigration {

    private val testCoroutineDispatcher: TestDispatcher = StandardTestDispatcher()

    @get:Rule
    val instantTaskExecutorRule = InstantTaskExecutorRule()

    @Before
    fun setUp() {
        Dispatchers.setMain(testCoroutineDispatcher)
    }

    @After
    fun teardown() {
        Dispatchers.resetMain()
    }

    @Test
    fun testDelayRegression() = runTest {
        liveDataToFlow(testCoroutineDispatcher).observeForever {
            println("new value observed : $it")
            assertEquals("foo", it)
        }
    }

    private fun liveDataToFlow(dispatcher: CoroutineDispatcher) = flow {
        emit("bar")
    }.asLiveData(dispatcher)
}
```

Running this code prints "new value observed : bar" in the console, but doesn't make the test fail. The exception is printed in the console, tho. 

Kotlin 1.6.20
Kotlinx-coroutines-test 1.6.1

**Comment by NinoDLC** [comment]
Thanks for your answer, but I'm more confused than before tbh. 

> To properly fix this, ensure that all coroutines are properly terminated at the end of the test.
How can I do that ? `testCoroutineScope.cleanupTestCoroutines()` ? 🤣

**Comment by NinoDLC** [comment]
That sound like an awfully verbose new API. I guess we'll stick to Kotlin 1.5 then.

**Comment by dkhalanskyjb** [comment]
How would this test look like in 1.5?

**Comment by NinoDLC** [comment]
In 1.5 : 
```
@ExperimentalCoroutinesApi
class BeforeDot6 {

    private val testCoroutineDispatcher = TestCoroutineDispatcher()
    private val testCoroutineScope = TestCoroutineScope(testCoroutineDispatcher)

    @get:Rule
    val instantTaskExecutorRule = InstantTaskExecutorRule()

    @Before
    fun setUp() {
        Dispatchers.setMain(testCoroutineDispatcher)
    }

    @After
    fun teardown() {
        Dispatchers.resetMain()
        testCoroutineScope.cleanupTestCoroutines()
    }

    @Test
    fun testDelayRegression() = testCoroutineScope.runBlockingTest {
        liveDataToFlow(testCoroutineDispatcher).observeForTesting {
            advanceTimeBy(300)

            println("new value observed : ${it.value}")
            assertEquals("foo", it.value)
        }
    }

    private fun liveDataToFlow(coroutineDispatcher: CoroutineDispatcher) = flow {
        delay(300)
        emit("foo")
    }.asLiveData(coroutineDispatcher)

    fun <T> LiveData<T>.observeForTesting(block: (LiveData<T>) -> Unit) {
        val observer = Observer<T> { }
        try {
            observeForever(observer)
            block(this)
        } finally {
            removeObserver(observer)
        }
    }
}
```
`advanceTimeBy(300)` is needed, else the test fails. No "false positive" this way. 

In 1.6 : 
```
@ExperimentalCoroutinesApi
class AfterDot6 {

    private val testCoroutineDispatcher: TestDispatcher = StandardTestDispatcher()

    @get:Rule
    val instantTaskExecutorRule = InstantTaskExecutorRule()

    @Before
    fun setUp() {
        Dispatchers.setMain(testCoroutineDispatcher)
    }

    @After
    fun teardown() {
        Dispatchers.resetMain()
    }

    @Test
    fun testDelayRegression() = runTest {
        val job = Job()

        liveDataToFlow(coroutineContext + job).observeForTesting {
            advanceTimeBy(301)

            println("new value observed : ${it.value}")
            assertEquals("foo", it.value)
        }

        job.cancel()
    }

    private fun liveDataToFlow(coroutineContext: CoroutineContext) = flow {
        delay(300)
        emit("foo")
    }.asLiveData(coroutineContext)

    fun <T> LiveData<T>.observeForTesting(block: (LiveData<T>) -> Unit) {
        val observer = Observer<T> { }
        try {
            observeForever(observer)
            block(this)
        } finally {
            removeObserver(observer)
        }
    }
}
```
`advanceTimeBy(301)` is needed, 300 isn't enough (it is enough combined with the use of `runCurrent`)

Pros : 
* TBD

Cons : 
* We inject a CoroutineContext instead of a CoroutineDispatcher
* We have to offset delay with +1 (or add one more line with `runCurrent`)
* +3 lines with `Job` creation, Job injection with `coroutineContext + job`, `Job` cancellation
* Injection of dispatcher in the test subject was easy (could be done in the Before phase), now we have to create the test subject in every test

**Comment by dkhalanskyjb** [comment]
> We inject a CoroutineContext instead of a CoroutineDispatcher

Don't see why this is a con.

> We have to offset delay with +1 (or add one more line with runCurrent)

This, too.

> +3 lines with Job creation

The test for 1.5 successfully completes despite the fact that a coroutine has leaked. The 1.6 version correctly identifies an error. Surely this is a "pro", not a "con". If you don't want to detect leaking coroutines, I showed you a trick that allows you to save these three lines.

> Injection of dispatcher in the test subject was easy (could be done in the Before phase), now we have to create the test subject in every test

Why can't you make a rule with the 1.6 API?

Also, with 1.6, you likely don't need an `InstantTaskExecutorRule`.

**Comment by NinoDLC** [comment]
>>We inject a CoroutineContext instead of a CoroutineDispatcher

>Don't see why this is a con.

The very basis of clean code is "pass the lowest information needed between classes / functions". `CoroutineContext` is much more than `CoroutineDispatcher`. You can buy this book on Amazon !

>>We have to offset delay with +1 (or add one more line with runCurrent)

>This, too.

Let's pretend I don't have to offset +1 every single one of my `advanceTimeBy()`, right. Or let's pretend that forcing anyone using the new time API has to add at least a `runCurrent()` to their test, either. No probl : double the lines, double the fun ! 👍 

>>+3 lines with Job creation

> The test for 1.5 successfully completes despite the fact that a coroutine has leaked. The 1.6 version correctly identifies an error. Surely this is a "pro", not a "con". If you don't want to detect leaking coroutines, I showed you a trick that allows you to save these three lines.

Who cares a coroutine leaks in a Unit Test if it saves me all this hassle ? We didn't even have performances issues despite 2000+ UT using coroutines... The coroutine doesn't leak in the source code, everything is fine! If not leaking a coroutine in a Unit Test is what the 1.6 test coroutine version is all about, that's a bad tradeoff IMO. 

>> Injection of dispatcher in the test subject was easy (could be done in the Before phase), now we have to create the test subject in every test

> Why can't you make a rule with the 1.6 API?

I'm very curious about your take here, a Rule (or Test extension for that matter) needs to be done before the test, but with 1.6 I need to wait for the `runTest` function to create my TestScope in order to get my coroutineContext in order to inject the testSubject... So the creation / injection of the test subject needs to be done in the test phase instead of the (former) before phase. Am I missing something ?

**Comment by dkhalanskyjb** [comment]
From another thread:

> If you feel i'm not polite to you (not your "code" or "documentation", these need to be criticized), please let me know, this is not my intention.

I do think you're not being polite here. 

> The very basis of clean code is "pass the lowest information needed between classes / functions".

Code cleanness can not be reduced to a few simple rules, everything is a compromise. For example, creating all-encompassing ("god") objects is not considered clean. Before, the test dispatcher was also an `UnconfinedExceptionHandler`, which is a good example of a god object. Now, it's not the case. If the coroutine dispatcher — a thing that dispatches coroutines — would still be responsible for handling exceptions, it would be a violation of responsibilities. A bad thing, as the very same books will no doubt say.

> Let's pretend I don't have to offset +1 every single one of my advanceTimeBy(), right. Or let's pretend that forcing anyone using the new time API has to add at least a runCurrent() to their test, either. No probl : double the lines, double the fun ! +1

Let's pretend that `advanceTimeBy(0)` being about the same as `runCurrent` makes sense, or that, to be able to verify the state *exactly before something happens* one doesn't have to offset with a `-1` (we discovered that `advanceTimeBy(n-1); assert; advanceTimeBy(1); assert` was fairly common and didn't reflect the intention).

See, I can play this game, too, where instead of seriously arguing the case, I'd make fun of how obvious my points are. However, it's not productive, so let's stop doing this.

> The coroutine doesn't leak in the source code, everything is fine!

How do you test that your coroutines don't leak if the tests are not reliable?

> If not leaking a coroutine in a Unit Test is what the 1.6 test coroutine version is all about

It's not, it's just a nice added bonus.

> but with 1.6 I need to wait for the runTest function to create my TestScope in order to get my coroutineContext in order to inject the testSubject

You don't, you can create a `TestScope` in advance: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/README.md#accessing-the-test-coroutine-scope I repeat my suggestion to go ahead and read the README for an overview of the API. Then, if you have some specific questions about how to test something, ask a question on the Slack channel; a lot of developers there have good understanding of the API and can offer advice.

If, after gaining some familiarity, you find a specific area that could be improved about the documentation, the API, or the migration guide, please share.

**Comment by NinoDLC** [comment]
> I do think you're not being polite here.

I'm getting frustrated yes. I'm not confortable with you saying how doubling the lines to advance time in a test is just fine. That's just awful, no one can argue about that ? All the Kotlin community learned for years that during tests, all tasks that were scheduled at X time, would be executed at X time. Plain easy. Now we have to unlearn this very "base knownledge" (among a lot of other things) just "because" and you seem fine with it. Yes, this is frustrating. 

> Code cleanness can not be reduced to a few simple rules, everything is a compromise. For example, creating all-encompassing ("god") objects is not considered clean. Before, the test dispatcher was also a CoroutineExceptionHandler, which is a good example of a god object. Now, it's not the case. If the coroutine dispatcher—a thing that dispatches coroutines—was still responsible for handling exceptions, it would be a violation of responsibilities. A bad thing, as the very same books will no doubt say.

Fine point, but I prefer god classes and other "anti pattern" (hell, Mockito is an anti-pattern by itself : everything is global) in the test package rather than source package. 

> Let's pretend that advanceTimeBy(0) being about the same as runCurrent makes sense, or that, to be able to verify the state exactly before something happens one doesn't have to offset with a -1 (we discovered that advanceTimeBy(n-1); assert; advanceTimeBy(1); assert was fairly common and didn't reflect the intention).

With a `flow { delay(300); emit("foo") }` it seems perfectly fine that if virtual time = 299, nothing happened yet ? In this case that's perfectly logical to offset by one 😅 The usecase you described is still the same (`advanceTimeBy(n); assert; runCurrent(); assert`), but everyone else has to "pay" for that weirdness. 

The turbine approach ( https://github.com/cashapp/turbine ) makes a lot more sense when you want to verify nothing happened *yet* and have full control about emissions. I don't see how the change is gonna help that. 

> How do you test that your coroutines don't leak if the tests are not reliable?

I don't see how the 1.6 is better at detecting a leak in the source code. Do you have any exemple of a better coverage or a missed usecase in <= 1.5 ?

> You don't, you can create a TestScope in advance: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/README.md#accessing-the-test-coroutine-scope

What's inside `TestSubject.resetScope()` ? Once again everything is just obscure, snippets always are "too basic" or miss the point...

**Comment by dkhalanskyjb** [comment]
> I'm not confortable with you saying how doubling the lines to advance time in a test is just fine. That's just awful, no one can argue about that ?

I can. I don't see the tragedy that you make it out to be, at all. If you're using `advanceTimeBy` in exactly the manner where this is important a lot, there's nothing stopping you from defining—only once per each project—something like
```kotlin
fun TestScope.advanceTimeAndRun(delayTimeMillis: Long) {
  advanceTimeBy(timeDelta)
  runCurrent()
}
```
You can do it in the same place where you define your JUnit rules and such.

On the contrary, if someone didn't like the earlier behavior of `advanceTimeBy`, there was no way to get the current one.

> I prefer god classes and other "anti pattern" (hell, Mockito is an anti-pattern by itself : everything is global) in the test package rather than source package.

Ok. Throwing exceptions where nothing can catch them (e.g., `GlobalScope.launch`) is an anti-pattern in the source code as well.

> With a flow { delay(300); emit("foo") } it seems perfectly fine that if virtual time = 299, nothing happened yet ? In this case that's perfectly logical to offset by one :sweat_smile:

Another way to look at this is that the virtual time 300 is the moment when `delay` wakes up and the code after it starts being ready to be run.

> The turbine approach

How would that approach generalize to the arbitrary coroutine code, not specifically to testing flows?

> I don't see how the 1.6 is better at detecting a leak in the source code. Do you have any exemple of a better coverage or a missed usecase in <= 1.5 ?

Yes, plenty of them. If you're interested in the history of the testing framework, feel free to look through the closed issues with the `test` label, there are many examples of tests broken because of the quirks of the old API.

> What's inside TestSubject.resetScope() ?

Whatever you want, it represents an arbitrary de-mocking operation. Basically, you can use `TestScope` in almost the same way as you used `TestCoroutineScope` before.

**Comment by NinoDLC** [comment]
> On the contrary, if someone didn't like the earlier behavior of advanceTimeBy, there was no way to get the current one.

You just said people did `advanceTimeBy(n-1); assert; advanceTimeBy(1); assert`. What prevented them to write an extension for it ? We actually did something similar for Turbine and we're fine with it ? 

```
suspend fun FlowTurbine<*>.delayAndExpectNoEventsFor(timeMillis: Long) {
    if (timeMillis < 2L) {
        throw IllegalStateException("timeMillis of $timeMillis makes no sense")
    }

    delay(timeMillis - 1)
    expectNoEvents()
    delay(1)
}
```

> Ok. Throwing exceptions where nothing can catch them (e.g., GlobalScope.launch) is an anti-pattern in the source code as well.

Always has been. Releases after releases they make this usage less and less desirable, with more and more warnings. Testing 1.6 seems to do the opposite with the CoroutineContext over CoroutineDispatcher injection. 

> How would that approach generalize to the arbitrary coroutine code, not specifically to testing flows?

I would expect a similar API than Turbine : `myCoroutine().launchTest {}` or whatever and inside this `launchTestScope`, I could `expectNoEvents()`, `delay()`, `awaitItem()` and `awaitComplete()`. But I don't see the point with the "offset delay" change. 

> Yes, plenty of them. If you're interested in the history of the testing framework, feel free to look through the closed issues with the test label, there are many examples of tests broken because of the quirks of the old API.

Well, I look at the new ones (in particular testing conflated values or relying on a custom implementation of a TestDispatcher because the other 2 won't work) and it doesn't seem any better. There will always be edge usecases. 

The fact that there is not (to my knowledge) a single article / tutorial explaining how to unit test coroutines with LiveData with coroutines test 1.6 after 4 months tells a lot.

**Comment by dkhalanskyjb** [comment]
> What prevented them to write an extension for it ?

Some did, but there are small technical details that it impossible to get the *exact* behavior of the current `advanceTimeBy`. The new version is more orthogonal and semantically clear. Just compare the extension function you're showing with the one I've shown, and you'll see which one is simpler.

> Testing 1.6 seems to do the opposite with the CoroutineContext over CoroutineDispatcher injection.

You shouldn't have to do `CoroutineContext` injection. Typically `TestScope` should be injected, this will do the trick as well. Injecting `CoroutineDispatcher` will also work, but only when structured concurrency is used. So, in practice, injecting `CoroutineContext` should only be needed for the edge cases.

> Well, I look at the new ones (...) and it doesn't seem any better

In fact, these issues are not so much *issues* as discussions of how to recreate the default behavior of the old testing API (also, if you read carefully, there are clear and idiomatic solutions proposed in these discussions), so I'd argue that, no, it *is* much better.

> The fact that there is not (to my knowledge) a single article / tutorial explaining how to unit test coroutines with LiveData with coroutines test 1.6 after 4 months tells a lot.

Maybe it tells something, but not to me. I've seen people testing LiveData just fine with the new API. Maybe there are no articles because people don't have trouble with it once they gain some familiarity with the new API.

---

In any case, I don't even understand the point you're making. It looks like you're frustrated about not being able to follow the guide and vaguely critical about the new API. It's a pity that you have issues, but I don't see any specific steps that would we could make to lessen your frustrations. Read the docs, consult on StackOverflow or Slack if you find something unclear, and if you have specific suggestions for improvement, it would be great to discuss them. For, I'm closing the issues you opened, since it doesn't look like we arrived at anything actionable.

**Comment by dkhalanskyjb** [comment]
BTW, I checked again the examples you've shown and noticed that they are different from what you're initially submitted.

So I looked more closely and arrived at how to port `BeforeDot6` to the new API and ended up with this (which is almost the same as the `BeforeDot6` implementation):
```kotlin
@ExperimentalCoroutinesApi
class AfterDot6_2 {

    private val testCoroutineDispatcher = StandardTestDispatcher()
    private val testCoroutineScope = TestScope(testCoroutineDispatcher)

    @get:Rule
    val instantTaskExecutorRule = InstantTaskExecutorRule()

    @Before
    fun setUp() {
        Dispatchers.setMain(testCoroutineDispatcher)
    }

    @After
    fun teardown() {
        Dispatchers.resetMain()
    }

    @Test
    fun testDelayRegression() = testCoroutineScope.runTest {
        liveDataToFlow(testCoroutineDispatcher).observeForTesting {
            advanceTimeBy(301)

            println("new value observed : ${it.value}")
            assertEquals("foo", it.value)
        }
        advanceUntilIdle()
    }

    private fun liveDataToFlow(coroutineDispatcher: CoroutineDispatcher) = flow {
        delay(300)
        emit("bar")
    }.asLiveData(coroutineDispatcher)

    fun <T> LiveData<T>.observeForTesting(block: (LiveData<T>) -> Unit) {
        val observer = Observer<T> { }
        try {
            observeForever(observer)
            block(this)
        } finally {
            removeObserver(observer)
        }
    }
}
```

**Comment by NinoDLC** [comment]
The new `advanceUntilIdle()` needed by the new API is just so uncomprehensible. The flow reached its end, why would the new API need the `advanceUntilIdle()` ? I worked extensively for 2 years with Coroutines but nothing makes sense with this new API.

**Comment by dkhalanskyjb** [comment]
Ah, yes, sorry, forgot to remove it when playing around. Of course, it's not needed.
