### ISSUE TITLE
Add a "GoodOldCoroutineDispatcher" (name TBD) that automatically runs tasks scheduled at n time

### ISSUE THREAD

**Issue by NinoDLC** [Kotlin/kotlinx.coroutines#3246]
With 1.6 migration done, there's `runCurrent()` basically everywhere on the test codebase. This extra complexity (tbh, I just spammed `runCurrent()` on every 2'000 UT failing after the 1.5 -> 1.6 migration) and extra verbosity isn't great. 

Why not bring the "good old" coroutine dispatcher (that was semantically good) back and avoid the use (spam) of `runCurrent()` ? There's already a choice to be made between 2 different TestDispatcher, why not 3 ?

It would behave like [StandardTestDispatcher](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-standard-test-dispatcher.html) but with the extra quirck of automatically running tasks scheduled at current virtual coroutine time (like the TestCoroutineDispatcher was doing in 1.5 or lower). 

Pros : 
* 1.5 to 1.6 migration would finally be easy (the only issue in the end with all my failing tests was because they were **too precise**, I was 1 ms off because of the new `advanceTimeBy` / `runCurrent` behavior)
* Behavior is the same as the previous one, avoiding extreme confusion with the +1ms offset
* It's only a new TestDispatcher so this change won't affect others (like it did with the 1.6 version)

Cons : 
* For some reason the old dispatcher was deprecated / not updated / not re-coded so there's maybe a technical issue there ?

**Comment by dkhalanskyjb** [comment]
If you find the need to spam `runCurrent` after `advanceTimeBy`, create a function
```kotlin
fun TestScope.advanceTimeAndRun(delayTimeMillis: Long) {
  advanceTimeBy(timeDelta)
  runCurrent()
}
```
Then, perform a search-and-replace of `advanceTimeBy` by `advanceTimeAndRun`. This will do the trick.

As for adding a new dispatcher, the listed pros are not sufficient to add one. Some of the reasons:
* The main reason: this would add a difficult and confusing choice: should one use `StandardTestDispatcher` or `GoodOldCoroutineDispatcher`? Why? Adding a whole new dispatcher when a small function wrapping `advanceTimeBy` and `runCurrent` would suffice is an overkill.
* One would need to know the currently used test dispatcher to predict what `advanceTimeBy` does, so the behavior of the test would become brittle.
* It was (and would be) inconsistent for `advanceTimeBy(n)` to also run the tasks scheduled at `currentTime + n`.
* The old dispatcher didn't *consistently* run the tasks scheduled at `currentTime`. Most of the time it did, sometimes it did not, adding to the confusion.
* What you're proposing is technically difficult.

So, adding a new dispatcher would add a difficult choice, bloat the API, there's no actual need for this except when migrating from the old API (and that need could just as easily be served by a simple function), and it would be difficult. So, this is a hard "no".

**Comment by NinoDLC** [comment]
You fail to understand how the previous API was more desirable and I can't see why. 

Before, I could simply `pause()` the test, assert my "initial stuff" in the rare case I'd need it, and then `resume` it. If I didn't have to assert initial stuff (the most "common" kind of test), I didn't have to write any extra line. 

Before, an extra line on a test would mean "uncommon stuff done" (IE, initial state to be asserted).  
Now, an extra line is mandatory everytime for "common stuff". Or worse, 2 test classes targeting the same source class because I have to use 2 different CoroutineTestRule (with different TestDispatcher

**Comment by Mugurell** [comment]
I can give an example of how the `StandardTestCoroutineDispatcher` is (more than) a bit cumbersome to use and a mix of the two available now - a dispatcher than eagerly starts all child coroutines but confining everything on one thread would be great.
Our app uses MVI stores with [`middlewares`](https://redux.js.org/understanding/history-and-design/middleware) that may launch new coroutines that may emit new actions launching then new coroutines and so on.

In extreme cases we have to now use 
```
store.dispatch(
    EngineAction.LoadUrlAction(
        "test-tab",
        "https://www.firefox.com"
    )
).join()

dispatcher.scheduler.advanceUntilIdle()
store.waitUntilIdle() // Wait for CreateEngineSessionMiddleware to create the new session

dispatcher.scheduler.advanceUntilIdle()
store.waitUntilIdle() // Wait for the LinkingMiddleware to load url
dispatcher.scheduler.advanceUntilIdle()
```

**Comment by dkhalanskyjb** [comment]
Hi @Mugurell! This issue is about getting back the old, deprecated dispatcher, but what you're describing is not how the old dispatcher worked: it either started coroutines eagerly, or confined the execution to the thread calling `advanceUntilIdle`. The two modes needed to be controlled with calls to `pauseDispatcher` and `resumeDispatcher`. Is this the behavior you want?

**Comment by Mugurell** [comment]
> Hi @Mugurell! This issue is about getting back the old, deprecated dispatcher, but what you're describing is not how the old dispatcher worked: it either started coroutines eagerly, or confined the execution to the thread calling `advanceUntilIdle`. The two modes needed to be controlled with calls to `pauseDispatcher` and `resumeDispatcher`. Is this the behavior you want?

`StandardTestDispatcher` is indeed great and allows the granularity to control and validate each step in the execution.
But sometimes there may be many such steps and we're only interested in the result of all / a bunch of them.
`UnconfinedTestDispatcher` is nice because of eagerly starting coroutines execution. But if some code below uses another thread things may become brittle in testing.
Eagerly starting coroutines but always resuming on one thread that we control would be great to have. 
From a test execution standpoint: "run everything in SUT (confined to one thread) before the next statement in test".

**Comment by dkhalanskyjb** [comment]
So, you're proposing some new dispatcher, not to return the old one, correct? Then this is not the right issue to discuss this under. Feel free to open a new issue and describe your use case, as it's still not clear to me.

> run everything in SUT (confined to one thread) before the next statement in test

It's not realistic to implement it the way you're describing, because "statements" are a fuzzy concept. Kotlin doesn't provide a way to say something like "run this code after each statement".
