### ISSUE TITLE
Data race in EventLoop

### ISSUE THREAD

**Issue by shmuelr** [Kotlin/kotlinx.coroutines#3251]
Hey there,

Similar to https://github.com/Kotlin/kotlinx.coroutines/issues/2660, our internal Java TSAN tests in Google picked up a race in EventLoop.common.kt

```
Write of size 4 at
kotlinx.coroutines.EventLoopImplBase$DelayedTask.setHeap(Lkotlinx/coroutines/internal/ThreadSafeHeap;)V EventLoop.common.kt:419
versus read of size 4 at
kotlinx.coroutines.EventLoopImplBase$DelayedTask.dispose()V EventLoop.common.kt:480
```

The race in EventLoop seems to be here
https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/EventLoop.common.kt#L417-L420
that write is not thread safe, but the `dispose` function is marked as synchronized
https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/EventLoop.common.kt#L479-L485
leading to the race in `_heap` reading & writing.

Is this race safe?

Thanks!

**Comment by qwwdfsad** [comment]
Could you please provide more detailed stacktraces?

**Comment by qwwdfsad** [comment]
Oh, I see, both `dispose` and `setHeap` are synchronized, but they actually use **different** monitors.

This is definitely a bug, I already can see an interleaving that leads to an error, working on the fix.
I must admit that TSAN testing is amazingly valuable as such bugs are _really_ hard to catch with non-targeting stress test or code-review

**Comment by shmuelr** [comment]
Nice! Thanks for working on a fix, I'm happy we were able to help here :D

**Comment by LifeIsStrange** [comment]
@shmuelr Hi :) What is this Java/kotlin TSAN you're talking about??
I have seen the openjdk TSAN JEP here: 
https://bugs.openjdk.java.net/browse/JDK-8208520
https://openjdk.java.net/projects/tsan/

However the implementation still seems to be a work in  progress and has not received updates since 2019? :/
How to use it, does the flag work on default openjdk or do I need a special OpenJDK build? Is there kotlin support out of the box?
Or do you have a custom solution at google?
I'm looking forward to your answer as the OpenJDK ecosystem would strongly benefit from a TSAN tool.
