### ISSUE TITLE
Provide ability to customize isDispatchNeeded for ExecutorService#asCoroutineDispatcher

### ISSUE THREAD

**Issue by kojilin** [Kotlin/kotlinx.coroutines#3261]
Currently for backend development using evenloop based framework like netty/[Armeria](https://armeria.dev/), we usually use CoroutineScope with `eventLoop().asCoroutineDispatcher()` like

```
fun hello(){
  // Usually this method is in the EventLoop already
  CoroutineScope(SupervisorJob() + eventLoop().asCoroutineDispatcher()){
    //some suspend DAO, service methods
    val result = service.bar()  // suspend function
    return service.foo(result) // suspend function
  }
}
```

And currently it's not possible to overwrite `isDispatchNeeded` for asCoroutineDispatcher, even it's already run in the same evenloop with context, it always submit for triggering. If possible maybe good to have ability to pass the function like `eventLoop().asCoroutineDispatcher({ eventloop.inEventLoop() })` or other better way.

I checked the source of `ExecutorService#asCoroutineDispatcher`, due to `ExecutorCoroutineDispatcherImpl` and `Delay` are internal, it's not easy to provide delegation maybe.

**Comment by qwwdfsad** [comment]
It doesn't look like we can easily provide such a solution: for 90%+ of the users the trailing lambda will rather be a potential source of bugs, especially taking into account the fact that default executors rarely expose the way to check whether the current thread is part of the thread pool. Apart from that, if the dispatcher is multithreaded, such unconditional my degrade an application into a single-threaded one.

>Delay are internal, it's not easy to provide delegation maybe.

It is okay to provide your own implementation of `CoroutineDispatcher` without `Delay`. 
`Delay` is only responsible for dispatching `delay`/`withTimeout` to the backing `ScheduledExecutorService` instead of the default source, so it probably will suit you.
