### ISSUE TITLE
How to test an empty Flow?

### ISSUE THREAD

**Issue by idomo1** [Kotlin/kotlinx.coroutines#3272]
Hello, I'm struggling to be able to test a specific scenario with regards to flows.
In short, I'm looking to test an empty flow is empty.

Here's my minimal reproduction. Imagine that the channel and flow are within the class which is being tested.

```
class TestClass {
    private val channel = Channel<String>()
    private val flow = channel.receiveAsFlow()

    @OptIn(ExperimentalCoroutinesApi::class)
    private val dispatcher = UnconfinedTestDispatcher()

    @OptIn(ExperimentalCoroutinesApi::class)
    @Before
    fun initialise() {
        Dispatchers.setMain(dispatcher)
    }

    @OptIn(ExperimentalCoroutinesApi::class)
    @Test
    fun testFoo() = runTest {
// When this code is uncommented, the flow will cancel as expected.
//        launch {
//            channel.send("test")
//        }
        val first = flow.firstOrNull()
        assertEquals<String?>(null, first)
    }

    @OptIn(ExperimentalCoroutinesApi::class)
    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }
}
```

When an element has been sent to the channel (see commented out code), calling `firstOrNull` will cancel the flow as expected. However if nothing has been sent to the channel the test will just hang.

Any suggestions on how I can test this would be really appreciated 🙂

**Comment by psteiger** [comment]
Hi @idomo1 , what you're testing in your code is not really an empty flow. An empty flow is a flow that **completes** without emitting anything, and your `Flow` never completes because the backing `Channel` never closes. If you use `firstOrNull()` on a `Flow` that never completes and never emits anything, it will hang indefinitely, waiting for either the first emission or the flow completion.

If you replace your commented code with `channel.close()` you'll see the test passes even without any emission.

**Comment by idomo1** [comment]
This seems to be working

```
@Test
    fun testFoo() = runTest {
        // launch(dispatcher) { channel.send("Test") }
        val first = flow.produceIn(this).tryReceive().getOrNull()
        assertEquals<String?>(null, first)
    }
```

**Comment by dkhalanskyjb** [comment]
Unfortunately, what you're asking for is completely impossible in the general case, because there's no way to know if a channel will ever emit something. Consider this pseudocode:
```kotlin
while (true) {
  if (the year is not 2031)
    delay(1000)
}
channel.send("Test")
```
Until the year is 2031, the channel will be empty and the test will pass, but then, on June 1st, 2031, the test suddenly fails. The example may look unrealistic, but the point is, one simply can't know if the channel will eventually contain something.
