### ISSUE TITLE
`dispatch` can't be cancellable

### ISSUE THREAD

**Issue by way-zer** [Kotlin/kotlinx.coroutines#3405]
## Demo code
```kotlin
import kotlinx.coroutines.*
import java.util.concurrent.Executors

fun main() {
    val tasks = Executors.newSingleThreadExecutor()

    //simple demo
    @Suppress("OPT_IN_USAGE")
    val job = GlobalScope.launch(tasks.asCoroutineDispatcher()) {
        println("START")
        delay(1000)
        println("END")
    }

    //Outer limit, this must be `tasks.execute`
    tasks.execute {
        runBlocking {
            println("Cancel")
            job.cancelAndJoin() //dispatch won't callback, so cancel will not complete.
            println("Cancel End")
        }
    }

}
```

## OUTPUT
```
START
Cancel
//no more, the program block
```

## Probleam
`delay` call `Dispatcher.dispatch`, then it can't be cancel.
Make some cancellable function become not cancellable (block when cancel).

## Possible Resolution
Assert `dispatch` cancallable. and ignore when `block` invoke.

**Comment by qwwdfsad** [comment]
The problem is not in the dispatcher implementation but in its usage pattern.

You have a **single-threaded** executor that you block with `runBlocking` in order to avoid some job. But in order for that job to complete, it has to be executed on the very same single-threaded dispatcher that is indefinitely blocked, leading to a deadlock.

Either one should avoid `runBlocking` in single-threaded dispatchers or provide backing executor with more than one thread
