### ISSUE TITLE
Interrupt the Flow builder early

### ISSUE THREAD

**Issue by CLOVIS-AI** [Kotlin/kotlinx.coroutines#3463]
I'd like to terminate the `flow {}` builder early.

Currently, this is possible:
```kotlin
flow {
  if (someComplexCheck())
    return@flow

  emit("Whatever")
}
```

I have many checks that look like the first `if`, and I'd like to put them in sub-functions:
```kotlin
fun <T> FlowCollector<T>.complexCheck() {
  if (someComplexCheck())
    // what here?
}
```

- `return` can't be used because it returns from `complexCheck`, not the flow builder.
- `currentCoroutineContext().cancel(…)` throws a `CancellationException` which bubbles up to `flow {}`'s caller (and forces them to `catch` on error collection).

What is the proper way to stop the `flow {}` builder early?

**Comment by dkhalanskyjb** [comment]
This is really a question about the Kotlin language, not about `Flow`. The question: "if I call function `g` from function `f`, what should I write in `g` so that `f` terminates early?"
```kotlin
fun f() {
  g()
  throw RuntimeException("we shouldn't be able to reach this line")
}

fun g() {
  // what to write here?
}
```

This type of execution is not supported in Kotlin, because, when reading `f`, you certainly don't expect some function call to affect how `f` is executed. At worst, you expect an exception to be thrown.

However, with `inline` functions, it's possible to explicitly pass the permission to terminate `f`: https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS43LjEwIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiZnVuIGYoKSB7XG4gIHByaW50bG4oXCJpbnNpZGUgZlwiKVxuICBnIHsgcmV0dXJuQGYgfVxuICBwcmludGxuKFwid29uJ3QgYmUgZXhlY3V0ZWRcIilcbn1cblxuaW5saW5lIGZ1biBnKHRlcm1pbmF0ZTogKCkgLT4gVW5pdCkge1xuICBwcmludGxuKFwiaW5zaWRlIGdcIilcbiAgdGVybWluYXRlKClcbiAgcHJpbnRsbihcIndvbid0IGJlIGV4ZWN1dGVkXCIpXG59XG5cbmZ1biBtYWluKCkge1xuICAgIGYoKVxufSJ9
```kotlin
fun f() {
  println("inside f")
  g { return@f }
  println("won't be executed")
}

inline fun g(terminate: () -> Unit) {
  println("inside g")
  terminate()
  println("won't be executed")
}
```
