### ISSUE TITLE
Why is `fun <T> (suspend () -> T).asFlow(): Flow<T>` still marked as `@FlowPreview`?

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#3542]
Hello,

I just noticed the suspend function to Flow extension (`fun <T> (suspend () -> T).asFlow(): Flow<T>`) is still marked as `@FlowPreview`.
Is there a reason why?

My use case today was creating a combined flow where one of the inputs is a suspend function:
```kotlin
fun watchAppInstallationStatusFlow(
    capabilityClient: CapabilityClient,
    nodeClient: NodeClient,
): Flow<WatchAppInstallationStatus> {
    return combine(
        capabilityClient.watches(),
        suspend { nodeClient.connectedNodes.await() }.asFlow()
    ) { watchNodesWithApp, connectedNodes ->
        TODO()
    }
}
```

**Comment by LouisCAD** [comment]
BTW, I can see the more primitive way is actually shorter, so that might be part of the answer?

- `flow { emit(nodeClient.connectedNodes.await()) }`
- `suspend { nodeClient.connectedNodes.await() }.asFlow()`

**Comment by hoc081098** [comment]
I have created #3079

**Comment by JakeWharton** [comment]
`nodeClient::connectedNodes.asFlow()` beats your `flow` variant in code golf, not that pinching pennies in character count is a particularly interesting factor in determining final API surface.

**Comment by murligit** [comment]
override fun observeIsTyping(): Flow<Boolean> =
        currentChatDocument?.collection("isTyping") // use collection instead of document
            ?.document(currentUser?.uid ?: "") // use currentUser?.uid as the document ID
            ?.asFlow()
            ?.map { snapshot: DocumentSnapshot ->
                snapshot.getBoolean("isTyping") ?: false // use "isTyping" as the field name
            }
            ?: emptyFlow()
<html>Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:<br/>public fun &lt;T&gt; (() -&gt; TypeVariable(T)).asFlow(): Flow&lt;TypeVariable(T)&gt; defined in kotlinx.coroutines.flow<br/>public fun &lt;T&gt; Array&lt;TypeVariable(T)&gt;.asFlow(): Flow&lt;TypeVariable(T)&gt; defined in kotlinx.coroutines.flow<br/>public fun IntArray.asFlow(): Flow&lt;Int&gt; defined in kotlinx.coroutines.flow<br/>public fun LongArray.asFlow(): Flow&lt;Long&gt; defined in kotlinx.coroutines.flow<br/>public fun &lt;T&gt; Iterable&lt;TypeVariable(T)&gt;.asFlow(): Flow&lt;TypeVariable(T)&gt; defined in kotlinx.coroutines.flow<br/>public fun &lt;T&gt; Iterator&lt;TypeVariable(T)&gt;.asFlow(): Flow&lt;TypeVariable(T)&gt; defined in kotlinx.coroutines.flow<br/>public fun IntRange.asFlow(): Flow&lt;Int&gt; defined in kotlinx.coroutines.flow<br/>public fun LongRange.asFlow(): Flow&lt;Long&gt; defined in kotlinx.coroutines.flow<br/>public fun &lt;T&gt; Sequence&lt;TypeVariable(T)&gt;.asFlow(): Flow&lt;TypeVariable(T)&gt; defined in kotlinx.coroutines.flow<br/>public fun &lt;T&gt; BroadcastChannel&lt;TypeVariable(T)&gt;.asFlow(): Flow&lt;TypeVariable(T)&gt; defined in kotlinx.coroutines.flow<br/>public fun &lt;T&gt; (suspend () -&gt; TypeVariable(T)).asFlow(): Flow&lt;TypeVariable(T)&gt; defined in kotlinx.coroutines.flow this is my issue solve it please
