### ISSUE TITLE
`asStateFlow()` and `.asSharedFlow()` should be applied on `StateFlow` and `SharedFlow` respectively

### ISSUE THREAD

**Issue by danielesegato** [Kotlin/kotlinx.coroutines#3552]
Hi,

I've wrote a custom `SharedFlow`: https://gist.github.com/danielesegato/160fabdcba5f563f1a171012377ea041

I was looking into how to add the `asSharedFlow()` extension function and I noticed coroutine do so with some private / internal class and functions.

The [source code](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/operators/Share.kt#L358):
```kotlin
public fun <T> MutableSharedFlow<T>.asSharedFlow(): SharedFlow<T> =
    ReadonlySharedFlow(this, null)


private class ReadonlySharedFlow<T>(
    flow: SharedFlow<T>,
    @Suppress("unused")
    private val job: Job? // keeps a strong reference to the job (if present)
) : SharedFlow<T> by flow, CancellableFlow<T>, FusibleFlow<T> {
    override fun fuse(context: CoroutineContext, capacity: Int, onBufferOverflow: BufferOverflow) =
        fuseSharedFlow(context, capacity, onBufferOverflow)
}
```

These are internal API:
- `CancellableFlow<T>`
- `fuseSharedFlow()`

To reproduce this `ReadonlySharedFlow` an user would have to copy a lot of your internal code.

Is there a reason why `.asSharedFlow()` is applied to `MutableSharedFlow` instead of `SharedFlow` or why there isn't a `asReadOnlySharedFlow()` to give this API to users?

Thanks

**Comment by dkhalanskyjb** [comment]
Why not give the users just `Flow`?

**Comment by dkhalanskyjb** [comment]
The reason is that this particular implementation of `asSharedFlow` API only makes sense for `MutableSharedFlow`. For example, there's no guarantee that an arbitrary implementation of `SharedFlow` will be cancellable. Flow fusing is a performance optimization for when we know some properties about the flows being chained and want to simplify the internal structure of their combination, and we can't know that an arbitrary `SharedFlow` implementation in the wild obeys the assumptions we make about `MutableSharedFlow`. For example, your `SharedFlow` permits arbitrary buffering strategies, which we know is not possible in a `MutableSharedFlow`, so fusing with your `SharedFlow` may not work in general. Fusing with an arbitrary channel is much more challenging: see the `fuse` in `ChannelFlow.kt`.

**Comment by danielesegato** [comment]
Thanks, it makes sense.
