### ISSUE TITLE
runTest {} on JS does not finish its context

### ISSUE THREAD

**Issue by Burtan** [Kotlin/kotlinx.coroutines#3717]
**Describe the bug**
runTest {} on JS does not finish its context, while it does on Android.

**Provide a Reproducer**
```
    @Test
    fun testUpload() = runTest {
       doTestWithBackgroundJob()
    }

    @Test
    fun testUploadFix() = runTest {
        launch(SupervisorJob()) {
           doTestWithBackgroundJob()
           cancel()
        }
    }
```

If you run a test that creates a background job, e.g. a loop that makes http requests, this job is cancelled when the runTest scope has finished on Android, but it is not on JS. This is not a problem on running single tests because the whole run is cancelled after the single test. But when running multiple tests at the same time, the test scope never finished until the whole suite finishes.
testUploadFix shows my workaround currently and is the behaviour I would expect on JS by default as well.

**Comment by Burtan** [comment]
This might as well be a bug in the kotlin.test framework? Maybe it's not runTest that finishes the scope, but the android test framework and the js testframework does not finish it?

**Comment by dkhalanskyjb** [comment]
https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-test.html and especially https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-test-result/ answer your question: it's not allowed to nest `runTest` calls, precisely because it can't be supported on JS.
