### ISSUE TITLE
Using Long variant of the select.onTimeout() is difficult

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx.coroutines#3777]
**Describe the bug**

When Long variant of the `select.onTimeout` is used, compiler will generate a following error:

```
Using 'onTimeout(Long, suspend () -> R): Unit' is an error. Replaced with the same extension function
```

IDE does not show any errors in code, nor does it offer any imports (because `onTimeout` extension method conflicts with the actual method on the interface).

Fix for it seeems to be manually adding `import kotlinx.coroutines.selects.onTimeout` import, however IDE marks this import as unused and will thus remove it on optimize imports, resulting in error coming back.

This has started with Coroutines 1.7.0. Kotlin IDE plugin is `223-1.8.0-release-345-AS8836.35.2231.10190587`.

**Provide a Reproducer**

```
suspend fun demo() {
   select {
      onTimeout(1L) {

      }
   }
}
```

**Comment by qwwdfsad** [comment]
It is, unfortunately, a bug in the `ReplaceWith` implementation in the IDE along with bugs in 223 IDEA itself that we cannot workaround except for hiding the member with `Deprecated(level = HIDDEN)`, which makes an initial migration worse.

>because onTimeout extension method conflicts with the actual method on the interface

For that reason, the member has `@LowPriorityInOverloadResolution` annotation applied, so the extension wins during both direct and wildcard imports

I've double-checked that on 231, and everything seems to work, so I recommend updating and seeing if the problem is gone:

<img width="389"  alt="image" src="https://github.com/Kotlin/kotlinx.coroutines/assets/2780116/a047667e-fcf3-47c9-891c-a9fb806e310e"> <img width="457" alt="image" src="https://github.com/Kotlin/kotlinx.coroutines/assets/2780116/fd74efbb-5d17-4bcd-8b01-9ce9ac23efbe">
