### ISSUE TITLE
Coroutine unit tests failing after upgrading kotlin to 1.8.10

### ISSUE THREAD

**Issue by ankitrapido** [Kotlin/kotlinx.coroutines#3821]
**Describe the bug**

On Kotlin-1.6.10 everything was working fine
but after I upgraded to Kotlin-1.8.10 tests started failing randomly with below exception
ut version - `org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.2`

```kotlinx.coroutines.test.UncaughtExceptionsBeforeTest```

**Provide a Reproducer**

Create a project with kotlin 1.6.10 and test version 1.6.4
upgrade to kotlin 1.8.10 
tests started failing

**Comment by dkhalanskyjb** [comment]
It means that your tests throw exceptions after they finish, in forked-off coroutines. We used not to catch such exceptions, but now we do, so that the tests are more robust. See the discussion under https://github.com/Kotlin/kotlinx.coroutines/issues/1205 This functionality can be disabled with https://github.com/Kotlin/kotlinx.coroutines/pull/3736#issuecomment-1542274701, but it's recommended to fix the tests instead.
