### ISSUE TITLE
runBlocking for JS platform

### ISSUE THREAD

**Issue by dQqAn** [Kotlin/kotlinx.coroutines#3859]
I checked the [youtrack](https://youtrack.jetbrains.com/issue/KT-22228/Support-suspend-test-functions#focus=Comments-27-3964713.0-0) and [github ](https://github.com/Kotlin/kotlinx.coroutines/issues/1996#issuecomment-728562784) commits. Are these enough to use runBlocking function with "`.promise`"?  Will there be runBlocking support on the JS platform?

**Comment by qwwdfsad** [comment]
See https://github.com/Kotlin/kotlinx.coroutines/issues/195

`runBlocking` cannot be reasonably implemented on JS with all the constraints `runBlocking` has.

The only reason `runTest` works is that it immediately returns promise to the calling framework.
E.g.
```
runTest {
    delay(100)
    println(1)
}

runTest {
    println(2)
}
```

will print `2 1` even though the opposite is expected from `runBlocking`-like API.
For `runTest` specifically it's not an issue because we explicitly prohibit it: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-test-result/
