### ISSUE TITLE
Using withContext to switch to a ExecutorCoroutineDispatcher doesn't support cancelation 

### ISSUE THREAD

**Issue by CharlesG-Branch** [Kotlin/kotlinx.coroutines#3894]
**What do we have now?**

Consider the following:
```
import java.io.*
import kotlin.coroutines.*
import kotlinx.coroutines.*
import kotlin.time.measureTime


fun main() = runBlocking {
    val pool = newFixedThreadPoolContext(8, "pool")
    measureTime {
        withTimeoutOrNull(200) {
            withContext(pool) {
                Thread.sleep(1000)
                println("Finished 1")
            }
        }
    }.also {
        println("Case1 took $it")
    }

    measureTime {
        withTimeoutOrNull(200) {
            suspendCancellableCoroutine<Int> { cont ->
                pool.asExecutor().execute {
                    Thread.sleep(1000)
                    println("Finished 2")
                    cont.resume(2)
                }
            }
        }
    }.also {
        println("Case2 took $it")
    }
    
    delay(2000)
}
```

This produces:
```
Finished 1
Case1 took 1.04s
Case2 took 202ms
Finished 2
```

Here we have a case where we use `newFixedThreadPoolContext` (or `newSingleThreadContext`) to create a thread where we can put CPU bound blocking work while adapting it to work with coroutines. In case1 the `withTimeout` isn't actually canceling the work and it case2 it does actually cancel the work.

**What should be instead?**

Two points:
(A) Why doesn't `withContext(pool)` behave like case2? I'd assume that by setting the context like this it'd have to dispatch to the thread pool in a similar manner to case2. Personally I find this to be extremely confusing. Why add the ability to create a `ExecutorCoroutineDispatcher` if it can't drop the work? Why does doing it the "right" way (aka using the structured concurrency helper methods) not work as well as doing it by hand?

I'm not sure the logic should change here, but I'd like to understand why it behaves the way it does.

(B) When reading through the official documentation I've found that it doesn't help much with these real-world problems. I've also consistently seen people (myself included) underestimate the difficulty of doing things correctly with coroutines & I believe this is in large part due to the documentation. https://kotlinlang.org/docs/coroutines-guide.html

For example, when dealing with blocking work the docs (rightly) point out how much of an issue & careful that you need to be with it. However sometimes you just need to deal with it & need to adapt blocking code into coroutines. I think that case1 is the reasonable thing people will try first.

The other hole is that the docs don't cover `suspendCancellableCoroutine` or `suspendCoroutine` at all. In my opinion this should be one of the first things covered in the docs. It's extremely important to know them for dealing with real-world use cases & they help teach the reader more deeply what a coroutine really is by showing how they relate to callbacks.

**Comment by dkhalanskyjb** [comment]
Please use Stack Overflow or Kotlin Slack first to check if what you found is truly a problem. This issue tracker is for actual issues in the coroutines library, not for questions.

The difference between the two examples is that the first one launches `Thread.sleep` *inside* `withContext`, whereas the second example just instructs another thread via `execute` to do the same. As you can see, "Finished 2" gets printed anyway, so `Thread.sleep` doesn't actually get cancelled. So, the second example cancels just `suspendCancellableCoroutine`, which is not doing any work at the moment and gets cancelled, whereas in the first example, the thread *is* blocked on `Thread.sleep`.

`Thread.sleep` does not support cancellation. See https://kotlinlang.org/docs/cancellation-and-timeouts.html#cancellation-is-cooperative. The way to make it support cancellation is to use `runInterruptible`: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-interruptible.html

**Comment by CharlesG-Branch** [comment]
@dkhalanskyjb So then where do I file issues in the documentation?

The documentation never covers how to make un-interruptible blocking work compatible with coroutines (so `runInterruptible` was never a solution here). If I was doing work that I knew *was* cancellable then I'd just use one of the Dispatchers that was built in. People create threadpools so that blocking work can be put on them. The library provides methods to adapt threadpools to work with coroutines, but they work in a way that that's incongruent with why people create threadpools in the first place. 

`withTimeout` has the same kind of issue. People use timeouts so that they can stop waiting for some work and move on — that work being cancelled too is a bonus. Having a timeout that depends on the successful cancellation of the work is incongruent with why people use timeouts.

Case1 is the *wrong* but *intuitive* way to solve the problem. The docs should be acknowledging this.

**Comment by dkhalanskyjb** [comment]
If there is a problem with documentation, this should be filed here, yes, but you haven't shown a problem yet. If you can point out specific places that could be improved, please do.

> The documentation never covers how to make un-interruptible blocking work compatible with coroutines (so `runInterruptible` was never a solution here).

`runInterruptible` documentation does. Also, searching for "interrupt blocking work coroutines", I get this as the first link: https://stackoverflow.com/questions/58402107/how-to-cancel-the-blocking-code-in-the-coroutines The second and the third link also contain the correct solution.

> The library provides methods to adapt threadpools to work with coroutines

If you're talking about `newFixedThreadPoolContext`, it is marked as delicate API, so you should get a warning when using it. It's not recommended to use it unless you know precisely how to do it and why you even need it. Calling `limitedParallelism` on an existing dispatcher serves most needs just as well.

> If I was doing work that I knew was cancellable then I'd just use one of the Dispatchers that was built in.

You probably should use the built-in dispatchers, explicitly creating thread pools should be very rarely needed with coroutines.

> People create threadpools so that blocking work can be put on them.

Not necessarily. People also create thread pools for long-running computations, for example.

> but they work in a way that that's incongruent with why people create threadpools in the first place.

In what way do you see this incongruence? Using thread pools so that blocking code gets interrupted is certainly incorrect. If something in our documentation gave you the impression that this is the way to cancel blocking code, please show it to us, and we will fix this.

> People use timeouts so that they can stop waiting for some work and move on — that work being cancelled too is a bonus. Having a timeout that depends on the successful cancellation of the work is incongruent with why people use timeouts.

Consider this code. The premise is that only one subscription can exist at the same time.

```kotlin
withTimeout(1.seconds) {
    try {
        subscribe();
        Thread.sleep(20000);
    } finally {
        unsubscribe();
    }
}
subscribe();
```

Currently, such code is safe: `unsubscribe` is guaranteed to finish before calling `subscribe` again. Would you expect that the `finally` block may not finish by the time the second `subscribe` happens? I wouldn't.

> Case1 is the wrong but intuitive way to solve the problem.

It's not intuitive once you understand that cancellation is cooperative. `Thread.sleep` does not cooperate with cancellation, so it does not get cancelled.

> The docs should be acknowledging this.

Which docs?
