### ISSUE TITLE
Nested exceptions are incorrectly recovered

### ISSUE THREAD

**Issue by vadimsemenov** [Kotlin/kotlinx.coroutines#3912]
See https://github.com/Kotlin/kotlinx.coroutines/issues/3714#issuecomment-1547911309

[This test](https://github.com/Kotlin/kotlinx.coroutines/blob/2a580dfda516dff197c400669cceebc78bfb647a/kotlinx-coroutines-core/jvm/test/exceptions/StackTraceRecoveryCustomExceptionsTest.kt#L91) asserts wrong behaviour. 

Correct test: 

```
        val result = runCatching {
            coroutineScope<Unit> {
                throw RuntimeException("outer", IllegalStateException("inner"))
            }
        }
        val ex = result.exceptionOrNull() ?: error("Expected to fail")
        assertIs<RuntimeException>(ex)
        assertEquals("outer", ex.message)
        val originalCause = ex?.cause
        assertIs<IllegalStateException>(originalCause)
        assertEquals("inner", originalCause.message)
```

**Comment by dkhalanskyjb** [comment]
`RuntimeException` does not implement [CopyableThrowable](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-copyable-throwable/), so it's not copied, but instead wrapped into a new `RuntimeException`. The original and the copy have different stack traces and object identities, and accessing the original is occasionally useful. This behavior is documented and intentional: <https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/topics/debugging.md#stacktrace-recovery-machinery>

> stacktrace recovery machinery tries to create a copy of the original exception (**with the original exception as the cause**)

**Comment by dkhalanskyjb** [comment]
By the way, if you need to access the original exception regardless of whether stacktrace recovery was enabled, please describe your use cases in a reply to https://github.com/Kotlin/kotlinx.coroutines/issues/2551#issuecomment-822555218
