### ISSUE TITLE
Cannot find module 'atomicfu'

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/kotlinx.coroutines#396]
See https://github.com/Kotlin/kotlinx.coroutines/issues/370#issuecomment-396252102

**Comment by elizarov** [comment]
Indeed, this is a problem. AtomicFU was published to NPM under the name of `kotlinx-atomicfu`, yet the main .js file was named `atomicfu.js`, thus Kotlin/JS compiler emitted require for `atomicfu` module. Depressingly, all the tests works (since they take artifacts with maven dependencies), yet it would not work in the target project when resolving dependencies via NPM.

**Comment by SUPERCILEX** [comment]
Awesome! I think you should ship a `.3` patch since JS has been broken for the past few releases.
