### ISSUE TITLE
CoroutineDispatcher isActive after cancel() since 1.7.0

### ISSUE THREAD

**Issue by Doctoror** [Kotlin/kotlinx.coroutines#3967]
**Describe the bug**
Since 1.7.0, CoroutineDispatcher `isActive` is still `true` after `cancel()`

**Provide a Reproducer**
```
@Test
fun dispatcherIsNotActiveAfterCancellation() = runTest {
    val dispatcher = Dispatchers.Default // same for UnconfinedTestDispatcher or any other
    dispatcher.cancel()
    assertFalse(dispatcher.isActive)
}
```

`org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4` - test passes
`org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.0` - AssertionError (same for v1.7.3, which is currently the latest stable)

**Comment by psteiger** [comment]
`CoroutineDispather.cancel()` is a call that does not make sense here: it resolves to `CoroutineContext.cancel()` (because every `CoroutineContext.Element` is a `CoroutineContext` itself). 

The call checks for a `Job` in the context and cancels it if it's present. A dispatcher never has a `Job` (at least not the dispatchers shipped with the library, not sure if they even _can_ have a `Job`).

The behavior change stems from #3300: `isActive` now returns `true` when a job is *not* present in context.

**Comment by dkhalanskyjb** [comment]
Yep, not a bug, just some very weird code.

**Comment by Doctoror** [comment]
Thank you, @psteiger. This pretty much explains the behaviour well. Please close as not valid.
