### ISSUE TITLE
1.8.0-RC Could not find "org.jetbrains.kotlinx:atomicfu-cinterop-interop"

### ISSUE THREAD

**Issue by martinbonnin** [Kotlin/kotlinx.coroutines#3968]
Trying to build an `iosArm64` target with version `1.8.0-RC`, I get hit by this error:

```
> Task :compileKotlinIosArm64 FAILED
e: Could not find "org.jetbrains.kotlinx:atomicfu-cinterop-interop" in [/Users/mbonnin/git/test-coroutines, /Users/mbonnin/.konan/klib, /Users/mbonnin/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/common, /Users/mbonnin/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/platform/ios_arm64]
```

Reproducer [here](https://github.com/martinbonnin/test-coroutines). Am I missing something?

**Comment by martinbonnin** [comment]
[Explicitely adding `atomicfu` to the dependencies](https://github.com/martinbonnin/test-coroutines/compare/main...fix?body=&expand=1&title=explicitely+import+atomicfu) fixes the problem but sounds like it might not be needed?

PS: also tried disabling konan caches like in [KT-44884](https://youtrack.jetbrains.com/issue/KT-44884/) but didn't seem to help much

**Comment by hoangchungk53qx1** [comment]
try this
https://github.com/Kotlin/kotlinx.coroutines/issues/3305

**Comment by dkhalanskyjb** [comment]
Citing @mvicsokolova's words:

---

The problem is on kotlinx.atomicfu side: the new version of atomicfu-gradle-plugin does not provide coroutines with a transitive dependency to atomicfu anymore. Though it's required because coroutines use inline declarations from kotlinx-atomicfu.The WA for now is adding atomicfu implementation dependency for the native sourceSets:

```kotlin
val nativeMain by creating {
  dependencies {
    implementation("org.jetbrains.kotlinx:atomicfu:0.23.1")
  }
}
```

And I'll prepare the new release of atomicfu where this dependency is provided by atomicfu-gradle-plugin.
