### ISSUE TITLE
MutableStateFlow assignment operator overload

### ISSUE THREAD

**Issue by rickclephas** [Kotlin/kotlinx.coroutines#3975]
**Use case**

A `MutableStateFlow` is often a mutable property with `Flow` capabilities.
Updating such a `Flow` can be done in various ways (`value`, `compareAndSet`, `getAndUpdate`, `update`, `updateAndGet`),
the most straight forward way being the `value` property.
However updating a `MutableStateFlow` property becomes a lot more verbose than updating a regular property:
```kotlin
var regularProperty: String = "a"
regularProperty = "b"

val stateFlowProperty = MutableStateFlow("a")
stateFlowProperty.value = "b"
```

Code would be more concise if we could directly assign a value to such properties, similar to Gradle's [property assignment](https://blog.gradle.org/simpler-kotlin-dsl-property-assignment).

**The Shape of the API**

```kotlin
val myState = MutableStateFlow("initial state")

// Assignment through the value property
myState.value = "verbose updated state"

// Direct assignment through assignment overloading
myState = "concise updated state"
```

**Comment by dkhalanskyjb** [comment]
Kotlin doesn't allow overloading assignments: https://kotlinlang.org/docs/operator-overloading.html#augmented-assignments `a = b` always means that `a` is a `var` and will be replaced with `b`.

**Comment by rickclephas** [comment]
This could be achieved with the [`assign-plugin`](https://github.com/JetBrains/kotlin/tree/0898dd1e7fcffde934343a508e2323c96e666982/plugins/assign-plugin) compiler plugin (can't seem to find any documentation about it though).
It allows for assignment overloading on `val` properties, which `MutableStateFlow`s typically are.

**Comment by dkhalanskyjb** [comment]
Sure, but virtually no one uses this plugin: https://github.com/search?q=KotlinAssignmentOverloadTarget&type=code Adding this behavior to this library would mean relying on some syntax that doesn't work almost anywhere else, breaking all expectations. We're not introducing any new syntax on the library level just for convenience.

Maybe you could file a feature request for the `assign-plugin` so that it allows you to define custom assignment operators for third-party classes (`MutableStateFlow` in this case) and use the assignment plugin in your own code.
