### ISSUE TITLE
ClosableCoroutineDispatcher behaves differently on Native vs. JVM when it is closed 

### ISSUE THREAD

**Issue by cmelchior** [Kotlin/kotlinx.coroutines#3993]
After investigating some dispatcher crashes in our tests, it looks like the root cause is that `ClosableCoroutineDispatcher` behaves differently on Native vs. JVM.

This is a test capturing the behavior:

```
public expect fun singleThreadDispatcher(id: String): CloseableCoroutineDispatcher

// JVM implementation
public actual fun singleThreadDispatcher(id: String): CloseableCoroutineDispatcher {
    return Executors.newSingleThreadExecutor { action: Runnable ->
        Thread(action).apply {
            name = id
            priority = Thread.NORM_PRIORITY
        }
    }.asCoroutineDispatcher()
}

// Native 
public actual fun singleThreadDispatcher(id: String): CloseableCoroutineDispatcher {
    return MultiWorkerDispatcher(id, 1)
}

// ------

    @Test
    fun dispatcherTest() = runBlocking<Unit> {
        val dispatcher = singleThreadDispatcher("test")
        val scope = CoroutineScope(dispatcher)
        dispatcher.close()
        scope.launch {
            println("Hello")
        }
    }
```

On JVM, the test seems to run, but not print "Hello"

On Native, it crashes with an IllegalStateException.

Looking at the code:

**On JVM, when using an ExecutorService:** https://github.com/Kotlin/kotlinx.coroutines/blob/84bad926f0c6bfba8f391d89a1ccea56b2542d09/kotlinx-coroutines-core/jvm/src/Executors.kt#L133

It seems to be a race condition whether or not the task will just be ignored or a  `CancellationException` is thrown (depending on the state of the Executor). Also, it is unclear why the task is also potentially sent to the IO dispatcher.

**On Native:**
https://github.com/Kotlin/kotlinx.coroutines/blob/84bad926f0c6bfba8f391d89a1ccea56b2542d09/kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt#L129

It just throws an `IllegalStateException` outright and does nothing else.

**Solution wanted:**
It is problematic that platform-specific race conditions define the behavior of the API. Ideally, the behavior should be the same across platforms, but I guess what that behavior is is up for debate. I see 3 ways, but more options might exist that are more suitable.

1. Both platforms always throw CancellationException when the dispatcher is closed
2. Both platforms always throw IllegalStateException when the dispatcher is closed.
3. Both platforms make it optional whether a task is ignored or one of the above exceptions is thrown.

**Comment by dkhalanskyjb** [comment]
You're right: this behavior is not sufficiently documented. We specify this for `newSingleThreadContext` (https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/new-single-thread-context.html) and `asCoroutineDispatcher` (https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/as-coroutine-dispatcher.html), but not for `newFixedThreadPoolContext`.

As for fixing this, it's currently impossible because
* on Native, the machinery behind threads is entirely different, and until we get a proper `Thread` API, we can't work around this,
* and on the JVM, there is a lot of existing code that deals with this.
