### ISSUE TITLE
Parametrized flow builder

### ISSUE THREAD

**Issue by esial** [Kotlin/kotlinx.coroutines#4003]
Let's say I have some operation `suspend (P)->R`.  I would like to use flow api to handle it. Everything is fine when parameter P is known at the moment of defining flow, but if parameter came from some kind of event flow creation needs to be delayed till this event occurs.

```
fun setup(){
    val operation: suspend (String)->Int = { ... }
    onEvent<SomeEvent>{ event->
        flow{ emit(operation(event.param)) }
           // flow operators
          .collect()
    }
}
```
Everything is fine till this flow is used only in this place. If there is few events using such flow I could extract it to the function and live with it, but in more complicated use case it would be nice to have a possibility to build and collect flow with parameter like below
```
fun setup(){
    val operation: suspend (String)->Int = { ... }
    val flow = flow { param -> emit(operation(param)). // flow operators
    onEvent<SomeEvent>{ event->
        flow.collect(event.param)
    }
}
```
FlowCollector could offer a possibility to pass a single generic argument to Flow or maybe some other way - I leave it to discuss.

**Comment by dkhalanskyjb** [comment]
`flow { emit(operation(event.param)) }.collect()` can be replaced with simply `operation(event.param)`. If there are intermediate flow operators before `collect`, they can just be expressed as regular Kotlin code.

In any case, the theoretical `flow { param -> emit(operation(param)) }` can be replaced with `{ param -> flow { emit(operation(param)) } }`. You can store a function that returns a `Flow` instead of the `Flow`.

The API you are proposing, on the other hand, won't work: for example, the type `Flow<Int>` doesn't communicate that it needs a `String` to work. Of course, we could introduce a new type like `FlowWithParam<String, Int>`, but it would be exactly the same as `(String) -> Flow<Int>`. You can even introduce an extension function like `((T) -> Flow<U>).collect(param: T, action: suspend (U) -> Unit)` if you want.
