### ISSUE TITLE
Make `withTimeout` inline, or make an inline variant of it.

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx.coroutines#4287]
`withTimeout` looks like it maybe can be inline, and this would allow callers to benefit from the recent preview feature of non-local break and continue from inline functions introduced in 2.1.0.

**Comment by dkhalanskyjb** [comment]
> `withTimeout` looks like it maybe can be inline

Unfortunately, it can't.

The code passed to `withTimeout` can not be executed inline, because the timeout needs to cancel not the coroutine that's calling `withTimeout` but only the code running in the `withTimeout` block. This means that the code passed to `withTimeout` must have a different coroutine context, which is impossible for inline functions.

```kotlin
import kotlinx.coroutines.*

fun main() {
    runBlocking {
        withTimeoutOrNull(100) {
            Thread.sleep(200)
            try {
                yield()
            } catch (e: Exception) {
                println("This suspension throws $e")
                throw e
            }
        }
        yield()
        println("This suspension doesn't throw")
    }
}
```
