### ISSUE TITLE
Netty backpressure

### ISSUE THREAD

**Issue by luengnat** [Kotlin/kotlinx.coroutines#447]
So far, I haven't seen any kotlin integration with netty leverages the backpressure mechanism in netty to disable auto-read when the write is much slower than read. Is there a pattern in kotlinx to achieve something like that?

https://github.com/dimitarg/backpressure_test/blob/master/src/main/java/com/novarto/test/ServerHandler.java

**Comment by elizarov** [comment]
Take a look at [ktor](http://ktor.io). It uses netty engine by default and properly integrates with the corresponding backpressure mechanics wihtout you having to write this kind of boilerplate yourself. The coroutine that is sending the data is simply suspended on backpressure.

**Comment by luengnat** [comment]
@elizarov I believe that ktor does not handle backpressure by calling `setAutoRead(false)` to stop Channel to feed more data downstream. That's why I asked about this.

**Comment by elizarov** [comment]
@luengnat You are welcome to open the corresponding issue in ktor.

**Comment by luengnat** [comment]
@elizarov That's not the reason I asked. I just would like to know whether there is a recommended approach to handle something like this. I guess we need to setAutoRead(false) when the channel is full and turn setAutoRead(true) back when channel is drained.

**Comment by elizarov** [comment]
@luengnat Yes. If you implement integration with a separate "transfer" coroutine that reads from your engine (from Netty, for example) and puts data into a channel (for some other coroutine to consume), then you can use limited-size channel and when the "transfer" coroutine suspends that is your "backpressure". It is somewhat clumsy with Netty since you have all those tons of callback and it actually much more natural if you write your engine directly on top of NIO or Posix epoll, since there a suspended "transfer" coroutine suspends and stops "polling" the socket, automagically responding to backpressure.

**Comment by luengnat** [comment]
@elizarov best example I can find is https://github.com/vert-x3/vertx-lang-kotlin/blob/master/vertx-lang-kotlin-coroutines/src/main/java/io/vertx/kotlin/coroutines/VertxCoroutine.kt 

It overrides offerInternal to pause the stream when the channel is full and pollInternal to resume the stream when the channel is drained. Do you think that is the reasonable approach?

**Comment by elizarov** [comment]
@luengnat This approach seems reasonable.
