### ISSUE TITLE
Simpler currentScope for a single launch/async

### ISSUE THREAD

**Issue by ebrowne72** [Kotlin/kotlinx.coroutines#581]
To launch a coroutine inside a suspend function using the current scope, it needs to be wrapped in `currentScope`:
```
suspend fun doSomething() {
    // do some stuff
    currentScope {
        launch { ... }
    }
    // do some more stuff
}
```
It would be nice to have a property (similar to `coroutineContext`) that could be used to call a single `launch` or `async` on without the extra brackets and indentation:
```
suspend fun doSomething() {
    // do some stuff
    currentScope.launch { ... }
    // do some more stuff
}
```

**Comment by qwwdfsad** [comment]
But why do you need it?

We didn't want to provide even `currentScope` because it allows to thoughtlessly use it here and there. `currentScope` with careless use is equal to `GlobalScope` which using we're discouraging.

If you have a lot of suspending declared in some class, then this class shoould probably implement `CoroutineScope` as described in [guide](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md#structured-concurrency-lifecycle-and-coroutine-parent-child-hierarchy)

**Comment by ebrowne72** [comment]
Perhaps you should make it clear in the guide that using `currentScope` is discouraged.

**Comment by qwwdfsad** [comment]
Sure, sill do

**Comment by elizarov** [comment]
`currentScope` is now deprecated and will be removed from 1.0 release.
