### ISSUE TITLE
Make dispatchers' naming uniform to have Dispatchers.newSingleThreadContext

### ISSUE THREAD

**Issue by voddan** [Kotlin/kotlinx.coroutines#637]
The last update moved all standard dispatchers into `Dispatchers` to improve discoverability except for factory functions like `newSingleThreadContext`. 

I argue that the same argument about discoverability applies to factory functions as well. 

Indeed, when I, the user, want to use a dispatcher, I immediately type 

    val myDispatcher = Dispatchers.<ctrl+space>

and start looking for a dispatcher that suits me. But creating a new single-threaded dispatcher is NOT on the list! How am I supposed to find it except for looking into the documentation on the web site?

To fix that and make the naming uniform I propose introducing `Dispatchers.newSingleThreadContext()`, etc.

P.S. While we are at it, how about renaming all `new*` functions into `create*` or something? I have never seen the `new*` naming convention anywhere.

**Comment by qwwdfsad** [comment]
>Wait, what? What a surprise. I did not honestly know I was supposed to close them.

It is written in both factories KDoc and `ExecutorCoroutineDispatcher` class KDoc.

>Why are they not in the GlobalScope then?

They are not in the global scope because they have nothing to do with it. 

>If those functions are not recommended to use, how am I supposed to create thread pools for groups of coroutines?

These functions are not "not recommended". They are rather "not recommended by default", and should be used with care, e.g. only when you are sure you **should** have different thread pools for different types of coroutines. 

Let me clarify:
For newcomers, there are default dispatchers, `Default` and `IO`  different flavors of UI dispatchers. They are just given to you as singletones, you can use them without thinking "but should I close them? Can I share them?" etc. They follow the principle of least surprise and cover 90%+ of use cases. You are focusing on the structure of your program, on the business logic, not on coroutines machinery, you don't even have to read documentation beyond basic builders.

But executor-based factories are different. You should use them **consciously**, you should be aware that any threadpool should be closed in the end, you should know that you can't just write 
```
fun foo() {
  val thread = newSingleThreadContext(...)
   launch(thread) { ... }
}

```

and thus they shouldn't be "easily" discovered from the same "basic" coroutine building blocks.
But there is nothing "unsafe" in them and as a library we should provide such factories because they are generally useful.
