### ISSUE TITLE
404 for NonCancellable documentation

### ISSUE THREAD

**Issue by kazemihabib** [Kotlin/kotlinx.coroutines#640]
Link in https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#run-non-cancellable-block

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental/-non-cancellable/index.html

**Comment by qwwdfsad** [comment]
https://github.com/Kotlin/kotlinx.coroutines/blob/cbeef1039d7402939bac8ec4674e1a7b1adf993a/docs/cancellation-and-timeouts.md#run-non-cancellable-block 

refers to https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental/-non-cancellable.html which is a valid documentation URL.

The document you are pointing out (https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md) has no content since last release
