### ISSUE TITLE
runBlocking() in Kotlin Native projects

### ISSUE THREAD

**Issue by yuriry** [Kotlin/kotlinx.coroutines#672]
I'm using ktor in a Kotlin Native project.  The common sub-project of my project depends on ```io.ktor:ktor-client:0.9.5-rc13```, which transitevly adds dependency on ```kotlinx-coroutines-core-common:0.26.1-eap13```.  ```launch()``` and ```async()``` are available for my project, but ```runBlocking()``` is not.  Do I need to add dependency on any other library to the common sub-project to access ```runBlocking()```, or is it not available by desing?

Thank you in advance!

**Comment by SeekDaSky** [comment]
If I'm not mistaken `kotlinx-coroutines-core-common` does not include runBlocking because of the Kotlin/JS platform on which such method is nonsense. If you want runBlocking you need to add `kotlinx-coroutines-core-native` to your dependencies

**Comment by elizarov** [comment]
Confirm. @yuriry does it solve your problem?

**Comment by yuriry** [comment]
@SeekDaSky @elizarov My understanding is ```kotlinx-coroutines-core-native``` can only be included into a project that uses Kotlin Native compiler.  In my case it is **iOS project**.  It cannot be included into a **common** project.

```runBlocking()``` is defined in ```kotlinx-coroutines-core```.  I get it transitively when I add dependency on ```kotlinx-coroutines-jdk8``` to my Java test project.  The question is can ```kotlinx-coroutines-core``` be included into a **common** project instead of ```kotlinx-coroutines-core-common``` to get access to ```runBlocking()``` from common code?


Thank you for your help!

**Comment by SeekDaSky** [comment]
@yuriry `kotlinx.coroutines-core-native` is not for Multiplatform projects only, you can use it on a basic Kotlin/Native project or in the Native code of a multiplatform project. `kotlinx.coroutines-core-common` is used in the common code of multiplatform projects only, and because it must define an interface common to all platform, and that Kotlin/JS does not support runBlocking, it just cannot expose runBlocking in any way.

`kotlinx.coroutines.core` is the JVM only implementation you cannot include it in the common code of a common project, but you can use it in the JVM code of a multiplatform project. But I get your confusion about the naming here

hope that helps

**Comment by yuriry** [comment]
@SeekDaSky ```kotlinx-coroutines-core-native``` can only be used with Kotlin Native compiler, which includes basic Kotlin Native project or the Native part of an MPP, this part was clear to me.  What was not fully clear is if ```kotlinx-coroutines-core``` could be used in a common subproject of an MPP.  Now it is fully clear that it can't be used, so the lack of ```runBlocking()``` in ```kotlinx-coroutines-core-common``` is by design.  Thank you, this helps.
