### ISSUE TITLE
Exception handling with structured concurrency (rx & async)

### ISSUE THREAD

**Issue by viorgu** [Kotlin/kotlinx.coroutines#691]
Hi, I've been playing around with the new structured concurrency model and I noticed some unexpected behavior in how exceptions are handled for some coroutine builders.

1. rx2 builders
```kotlin
@Test
fun rxError() = runBlocking {
    val completable = rxCompletable {
        error("error in rx builder")
    }
    completable.onErrorComplete().await()
}
```
In this case I would expect the exception that occurred in the `rxCompletable` to be passed to rx's `onError` and be handled by `onErrorComplete()` but at the moment the exception is thrown and the current scope is canceled

---

2. async builder
```kotlin
@Test
fun asyncError() = runBlocking {
    val deferred = async {
        error("error in async")
    }

    try {
        deferred.await()
    } catch (e: Throwable) {
        println("Exception: ${e.message}")
    }
    println("Complete")
}
```
Here I would have expected the exception thrown in the async block to be handled by the try-catch, and while that does seem to happen, the exception is still thrown after the scope completes it's execution, so I'm seeing something like: 
```
Exception: error in async
Complete

java.lang.IllegalStateException: error in async
...
```

Both of these issues are solved if I execute the builder on the `GlobalScope` or if I wrap them in a `supervisorScope` but the default behavior feels a bit strange and I'm not sure if it's intended

Kotlin version: 1.3.0-rc-131
kotlinx-coroutines version: 0.30.2-eap13

**Comment by elizarov** [comment]
This is does so by design. The basic idea is that _by default_ exceptions should always be thrown into the outer scope to immediately cancel all the other activities that might have been going on in this scope. 

> The slightly different behavior with `async/await` is a due to a special code that makes sure that if you were invoking `await` from the parent you still can catch the right exception so that you can use `await { ... }.await()` somewhat similarly to `withContext { ... }`.

This is the _default_ behavior.  You can override this behavior in one of two ways: 

* Use `rxCompletable(NonCancellable) { .. }` -- this creates a Completable instance that is not bound to the parent context at all (just like it is usual in Rx world), so cancelling parent does not affect it neither its failure affects parent)
* Use `supervisorJob { rxCompletable { ... } }` -- this create a Completable under a supervisor that is still cancelled when parent is cancelled, but its failure does not affect the parent.

Does it help?

**Comment by viorgu** [comment]
I can see how the default behavior would make sense for something like `launch` or `withContext` but the current behavior of `async` is quite strange and difficult to understand. 

In my example the execution of the code inside `runBlocking` completed successfully but I still get an exception afterwards and it's the same exception that I already "handled" in the try-catch block. 
This can lead to some really head-scratching moments when debugging issues where the same exception seems both handled and unhandled at the same time.


Regarding the Rx example, I can't see a situation where I'd actually prefer the default behavior over the `supervisorScope` case. Since Rx already provides an exception handling mechanism I would intuitively imagine that I can handle any exception that occured in the `rxCompletable` block using the builtin methods. 
With the default scope behavior, all of Rx's error handling operators become virtually useless as there's no way to pass an error down the subscriber chain. 

The main purpose of a Rx Completable is to signal if an operation has completed successfully or not, and I feel this should happen regardless of the scope the builder was executed on.

My main concern at the moment is that people that are not very familiar with the way scopes work will just start adding `GlobalScope.` whenever something doesn't work the way they expect

**Comment by elizarov** [comment]
@viorgu `asyc` is used _if and only if_ you run multiple things _concurrenty_. Consider the following code:
```
runBlocking {
    val d1 = async { foo1() }
    val d2 = async { foo2() }
    val r1 = d1.await()  // waiting here
    val r2 = d2.await()    
    combine(r1, r2)
}
```
d
Now consider a case when `foo1` works for a long time, while `foo2` quickly throws an exception. The failure of `foo2` must immediate cancel `runBlocking` and cancel `foo1` so that this error can be processed. There is simply no other way to it.

If you don't need to do multiple concurrent things, then you should not be using `async`.

**Comment by kmansoft** [comment]
Related: #753 I think...

**Comment by kmansoft** [comment]
This makes sense, but maybe...

Now consider a case when foo1 works for a long time, while foo2 quickly throws an exception (while the code is still waiting for foo1. The failure of foo2 must immediately cancel runBlocking and cancel foo1 so that this error can be processed. There is simply no other way to it.

... should require some explicit syntax on the developer's part?

If you look at #753 this kind of automatic "bubble up / cancel / kill everything" is very unexpected - and is also wrong (I think) when there is a coroutine (somewhere in the work tree) that does a catch / ignore / retry / workaround for an exception from one of its children?

The way things are now - if a coroutine launches some children that it knows can fail, and has code to catch and handle the exception (if any is thrown), it will still get killed / cancelled, even though the developer has *explicitly and intentionally* added code (try / catch) in his/her coroutine to catch and do whatever is appropriate.

And yet, the current design assumes that it knows better - that any exception anywhere in the tree is fatal and everything needs to be cancelled / ignored. Isn't this too "arrogant"? :)

Second, the problem is made worse by Kotlin's decision to not have checked exceptions (I'm not trying to discuss *that*, just pointing it out as a fact) - which means that any catastrophic failure scenarios like this could lurk in the code for a long time / not caught by testing / during beta releases etc.

**Comment by jcornaz** [comment]
@kmansoft,

> this kind of automatic "bubble up / cancel / kill everything" is very unexpected

I love it personally. I'm always sure to not leak coroutines/resources without the need to add any boilerplate code. If something goes wrong everything will be cancelled and I can still catch errors to do something relevant like reporting and/or retry.

>the current design assumes that it knows better - that any exception anywhere in the tree is fatal and everything needs to be cancelled / killed

Not at all. The developer may choose to use a `SupervisorScope` or `SupervisorJob` in order to say "any exception in a child is not fatal for this scope/job".

**Comment by ExpensiveBelly** [comment]
Sorry for posting on a Closed issue, but this code snippet does not work in version 1.5.1 or 1.5.2-native-mt

```
runBlocking {
    // the exception will be passed to the coroutine builder and handled by onErrorComplete()
    rxCompletable(SupervisorJob()) { error("error") }.onErrorComplete().await()
}
```

That will throw an Exception:
```
Completable context cannot contain job in it.Its lifecycle should be managed via Disposable handle. Had SupervisorJobImpl{Active}@5a259a3e
java.lang.IllegalArgumentException: Completable context cannot contain job in it.Its lifecycle should be managed via Disposable handle. Had SupervisorJobImpl{Active}@5a259a3e
	at kotlinx.coroutines.rx3.RxCompletableKt.rxCompletable(RxCompletable.kt:23)
```

Any advise as to how to circumvent this issue? Thanks
