### ISSUE TITLE
Coroutine retry function

### ISSUE THREAD

**Issue by BoxResin** [Kotlin/kotlinx.coroutines#759]
I hope there would be `retry` function like `rx`.

## My draft
```kotlin
/**
 * @param times Number of attempts. `0` means infinite.
 * @return `null` if failed all attempts.
 */
suspend fun <T> retry(times: Int = 0, onFail: suspend (Throwable) -> Unit = {}, action: suspend () -> T): T? {
    var count = 0
    
    while (times == 0 || count++ < times) {
        try {
            return action()
        }
        catch (throwable: Throwable) {
            onFail(throwable)
        }
    }
    return null
}
```

## Use case
```kotlin
launch {
    val result = retry(times = 3, onFail = { delay(3000) /* retry after 3 seconds */ }) {
        // Something to do
    }
    println(result)
}
```

**Comment by qwwdfsad** [comment]
Sorry, but I don't see any value in such function. In `rx` it makes sense because it is not trivial to implement proper reactive retries and it is composable.

But this function is trivial and can be implemented and customized by any user of the library.
Moreover, it is not composable, e.g. one may want to have exponential backoff, metrics between iterations and this is not what we want to see in the library.
And supporting this stuff is not the goal of this library
