### ISSUE TITLE
kotlinx.coroutines.channels.LazyBroadcastCoroutine cannot be cast to kotlinx.coroutines.channels.ConflatedBroadcastChannel

### ISSUE THREAD

**Issue by nbransby** [Kotlin/kotlinx.coroutines#815]
I would expect this to be a ConflatedBroadcastChannel, in fact I would like an api where I would not have to cast

```kotlin
/** use this to show that at least one other team mate is currently online (or not) */
val indicateOnlne = users.openSubscription()
            .map { it.count { user -> user.online } }
            .map { it > 1 }
            .broadcast(capacity = Channel.CONFLATED) as ConflatedBroadcastChannel
```

Also in the meantime is there a workaround for creating a ConflatedBroadcastChannel from an existing ReceiveChannel?

**Comment by qwwdfsad** [comment]
`broadcast(capacity = Channel.CONFLATED)` behaves like a `ConflatedBroadcastChannel` but is not an instance of `ConflatedBroadcastChannel` (and documentation does not guarantee so).
Under the hood, it creates a more efficient version of "launched coroutine + channel" and it implements only `BroadcastChannel`. It is not easy to make it `ConflatedBroadcastChannel` as well, because it is a class, not an interface.

>Also in the meantime is there a workaround for creating a ConflatedBroadcastChannel from an existing ReceiveChannel?

By manually implementing it with `launch` coroutine. While it is possible to provide a new API, could you please elaborate why do you need exactly `ConflatedBroadcastChannel`?

**Comment by nbransby** [comment]
My use case is to remove the member variable and change this line...

https://github.com/TeamHubApp/intellij-plugin/blob/master/src/main/kotlin/app/teamhub/UserNode.kt#L75

...to `presentation.presentableText = model.title..value`:

> and documentation does not guarantee so

I suggest you make that clearer in the documentation 
https://github.com/Kotlin/kotlinx.coroutines/blob/d6a5a399d1724ff56bbb285b25df071dbc98b715/common/kotlinx-coroutines-core-common/src/channels/Broadcast.kt#L49

**Comment by qwwdfsad** [comment]
As a temporary workaround you can use `model.title.poll ?: error("...")`

**Comment by nbransby** [comment]
Thanks for the workaround I added:

`val <E> BroadcastChannel<E>.value get() = openSubscription().poll()!!`

in anticipation of a being able to use a real ConflatedBroadcastChannel sometime in the future!

**Comment by qwwdfsad** [comment]
Broadcast channels are obsolete and will be superseded by the corresponding Flow primitives, so closing as "won't fix"
