### ISSUE TITLE
DeferredCompletionSource ?

### ISSUE THREAD

**Issue by rogeralsing** [Kotlin/kotlinx.coroutines#82]
In .NET we have the `TaskCompletionSource<T>` which contains a `Task` that can be awaited.
The TCS can then be used to trigger completion of this task, making it possible to let clients await the TCS task, and then on whatever signal/event, the task is set to completed.

Is there anything like this for `Deferred<T>` ?

I _suppose_ I could use a channel, and let someone await a message on the channel and send to the channel when the event/signal occurs.

But: IMO, it would have been cleaner with this support for Deferred as they communicate that there is a single value to be awaited, while a channel doesnt.

**Comment by elizarov** [comment]
I'm closing this as a duplicate for issue #70

**Comment by mr5z** [comment]
Hi

Any docs regarding how to use this? Excuse my searching skills cause I've been searching for hours already and I still can't see any example.

**Comment by pacher** [comment]
And while we are on it... What would be the reason to use `CompletableDeferred` instead of `CompletableFuture`?
Both can be completed, cancelled, `await`ed, etc. I don't see much difference in API and had a hard time deciding which one to use.
Could not find any info about this and always wanted to ask.
