### ISSUE TITLE
Testing without 'runBlocking'

### ISSUE THREAD

**Issue by sellmair** [Kotlin/kotlinx.coroutines#885]
Hi guys, coroutines are awesome 👍 
I just started a new multiplatform library project which is based on coroutines, but I have trouble figuring out how I am supposed to write tests using coroutines. 
Since most code is in the 'commonMain' sourceSet I would like to write tests for my suspending functions there. Because Kotlin's ```@Test``` annotation does not support suspending tests and 'runBlocking' is not available in the common module of coroutines, I do not see how I could test those suspending functions in the commonTest module. Did I miss something here?

Thanks in advance ☺️

**Comment by SeekDaSky** [comment]
runBlocking is not present in the common package because JS platform does not support it.

In my experience, I had to make a common function `runTest` that calls `runBlocking` on JVM and Native and that use `Promise` on Node.js (as most Node.js test libraries handle correctly test cases that return a `Promise` it works just fine)

Here are the links to my implementations
- [Common](https://github.com/SeekDaSky/Sok/blob/master/common/sok-common/src/Sok/Internal/RunTest.kt)
- [JS](https://github.com/SeekDaSky/Sok/blob/master/js/sok-js/src/Sok/Internal/RunTest.kt)
- [JVM](https://github.com/SeekDaSky/Sok/blob/master/jvm/sok-jvm/src/Sok/Internal/RunTest.kt)

Hope this helps

**Comment by qwwdfsad** [comment]
>In my experience, I had to make a common function runTest that calls runBlocking on JVM and Native and that use Promise on Node.js

This is more or less the thing we do in our tests

**Comment by 4face-studi0** [comment]
What about Native implementation? :/

**Comment by SeekDaSky** [comment]
I intentionally omit [native implementation](https://github.com/SeekDaSky/Sok/blob/master/native/sok-native-linux/src/Sok/Internal/RunTest.kt) because it contains library specific functions but it works exactly like JVM as it implements `runBlocking`
