### ISSUE TITLE
Can I confine coroutines in exactly one uncertain thread?

### ISSUE THREAD

**Issue by kobe2000** [Kotlin/kotlinx.coroutines#899]
Hi,

I have some bloking code to handle with, so I need to integrate kotlin/coroutine into my old blocking code, especially with `java.util.concurrent.locks.ReentrantReadWriteLock`. I need to lock/unlock it in just one thread. 

I know that I creating a coroutine context with dispatcher using 1 thread will solve the problem, I wonder whether there's other way to do it better. For example:

```
withContext(coroutineContext + SingleThread) {
  rwlock.write {
    ...
  }
}
```
Thanks

**Comment by Tolriq** [comment]
Jumping into this as face the same need for Database transactions that require all writes occurring in same thread.

As long as all suspend call with be simple coroutines with all using withContext(IO) there's no switching.
But as soon as we use actors / workerpool, even if those as also using withContext(IO) the coroutine will be continued in a different thread.

**Comment by fvasco** [comment]
You can consider something like this

```kotlin
private val singleThreadDispather = newSingleThreadContext("Single thread")
val Dispatchers.SingleThread get() = singleThreadDispather
```

**Comment by qwwdfsad** [comment]
@kobe2000 no, we don't have special API that satisfies your requirement (that physical thread is always the same, so `j.u.c.Lock` or thread-locals can be used).

>I wonder whether there's other way to do it better

Providing one single-thread dispatcher for all users of the library is dangerous because another dependency in your classpath can occupy such dispatcher exclusively for more or less the same purpose. 


If you have direct control over your old code, I'd recommend replacing `j.u.c.Lock` with `Mutex` from kotlinx.coroutines, in that case, you no longer need "same thread" requirement (though note that `Mutex ` does not support read locks yet)
