### ISSUE TITLE
no joinChildren extension in coroutines 1.0.1

### ISSUE THREAD

**Issue by filipkowicz** [Kotlin/kotlinx.coroutines#908]
do you have replacement for `joinChildren` extension on Job class (which was present in experimental coroutines and now after 1.0 release I can find direct replacement

**Comment by elizarov** [comment]
No. It was removed, because it is racy and had to use correctly if you are already starting additional children. You can use `job.children().forEach { it.join() }`. Does it help?

**Comment by filipkowicz** [comment]
yes, I'm currently doing it quite similar way, still racy (I had to do it even with `joinChildren` because of reason you mentioned
```
public suspend fun Job.joinAllChildren() {
    while (children.any { !it.isCompleted }) {
        children.toList().joinAll()
    }
}
```

closing it now but it would be great to have race free method to wait untill all children jobs are done (those added after `joinChildren` call but before all finishes too)

I'm using it as a marker/semaphor that all tasks from some group are completed (all tasks as parent takes certain job object) - in enviroment where diferent tasks from diferent "gropus" can be executed concurently in unknown order.
Is there other more suited tool for it?

//side note - would be great to see such api changes in release notes

thanks for answer and sugestion, coroutines are great 👍

**Comment by elizarov** [comment]
There is no race-free way to implement it. Your implementation is no conceptually different from `job.children().forEach { it.join() }`. You don't need all this extra code with `isActive` check, because `job.children().forEach { it.join() }` does exactly that. If are sure that you are not starting any more children after you've waited for them (and it is your responsibility to be sure), then you can use this simple code.
