### ISSUE TITLE
Dispatcher/CoroutineStart affects behavior of actor.offer

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#954]
### 0 Capacity Actor Use Case - Avoiding duplicate network calls

I wanted to avoid duplicate network calls, so I am currently using an `actor(capacity = 0)` + `.offer(..)` to avoid making a duplicate network call. My assumption is that `.offer(..)` will only return `false` when there is a network call in progress. It turns out this assumption isn't always true.

The following test behaves differently depending on the dispatcher and `CoroutineStart` parameter.

```kotlin

import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.CoroutineStart
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.channels.actor
import kotlinx.coroutines.delay
import org.assertj.core.api.Assertions.assertThat
import org.junit.After
import org.junit.Before
import org.junit.Test

class ActorTest {

    private lateinit var scope: CoroutineScope

    private lateinit var dispatcher: CoroutineDispatcher
    private lateinit var coroutineStart: CoroutineStart

    @Before
    fun setUp() {
        // modifying these two params affects whether the test passes
        dispatcher = Dispatchers.Default
        coroutineStart = CoroutineStart.DEFAULT

        scope = CoroutineScope(dispatcher + Job())
    }

    @Test
    fun actorTest() {
        val actor = scope.actor<Int>(start = coroutineStart) {
            log("actor coroutine initialized")

            for (item in channel) {
                log("received `$item` in channel. Will delay for $item seconds")

                delay(item.toLong() * 1000)
                log("delay complete for $item")
            }
        }

        assertThat(actor.isFull)
            .describedAs("Actor should not be full before received first element")
            .isEqualTo(false)

        actor.offer(1)

        assertThat(actor.isFull)
            .describedAs("Actor should be full while processing first element")
            .isEqualTo(true)

    }

    private fun log(message: String) {
        println("(${ActorTest::class.java.simpleName}) - $message")
    }

    @After
    fun tearDown() {
        scope.coroutineContext[Job]!!.cancel()
    }
}
```

Test passes only with `Dispatchers.Unconfined` and `CoroutineStart.DEFAULT`. If either `Dispatchers.Default` or `CoroutineStart.LAZY` is used, then the test fails because `actor.isFull == true` before an item is ever sent to the channel.

If I add `runBlocking { delay(1000L) }` immediately after the `scope.actor { .. }` is constructed, then the test will pass even if `Dispatchers.Default` is used. The test will always fail when `CoroutineStart.LAZY` is used.

Is this intended behavior? It seems to me that a zero capacity actor would be very useful for avoiding duplicate processes, but it turns out that this isn't reliable due to an initialization phase that actors seem to go through.

EDIT: just discovered that `CoroutineStart.UNDISPATCHED` will make this test always pass

**Comment by qwwdfsad** [comment]
>My assumption is that .offer(..) will only return false when there is a network call in progress. 

This assumption is wrong (and all consecutive conclusions use this fact).
`offer` will return `false` when an unprocessed message exists **in a channel**.

You can reason about the semantics of the actor as if it is `launch` that consumes the channel (plus the share cancellation lifecycle, but we can ignore it here):
```
val channel = Channel(...)

val actor = launch {
   for (element in channel) { ... }
}
```

Now consider the following chain of actions:
1) First `offer(msg)` is invoked and returned `true`. 
2) Second `offer(msg)` will return `false`, because there is a message in the channel and the actor is not yet received it.
3) actor receives `msg` from the channel and starts to process it. Note that its channel is now empty and the message is **in progress**.
4) Third `offer` now will return `true` because the actor's channel is empty, though actor is still processing the first message .

`start` parameter just changes the order of these actions (and thus the output of `offer`), not the semantics

**Comment by qwwdfsad** [comment]
If you want to filter duplicates, you probably should implement this logic in the actor itself, moreover, this logic is usually domain-specific.
