### ISSUE TITLE
ClosedSendChannelException still confusing

### ISSUE THREAD

**Issue by trathschlag** [Kotlin/kotlinx.coroutines#957]
#422 solved the issue for actors, but when using `launch`, the exception is still swallowed:
```kotlin
fun main(args: Array<String>) {
  runBlocking {
        val channel = Channel<Int>().apply { close() }

        launch {
            channel.send(1)
        }.join()

        println("Scope still alive")
    }
}
```
output:
```
Scope still alive
```

**Comment by qwwdfsad** [comment]
It is because the channel is closed with `ClosedSendChannelException` by default, which is `CancellationException` and cancellations are not reported.

But you are right, such behaviour is misleading and may lead to subtle bugs, I will investigate possibilities to change this

**Comment by trathschlag** [comment]
Thanks in advance! I assume there is a reason why `ClosedSendChannelException` extends `CancellationException`?

**Comment by qwwdfsad** [comment]
It took a while to return to this issue.
The reason was e.g. (user-code) data race between `send` and user cancellation.

We came up with the following decisions:
- If a channel was closed (`close`), `NoSuchElementException` and `IllegalStateException` will be thrown on `receive` and `send` respectively: attempt to read/write to closed channel is clearly an exceptional situation that should be reported
- If a channel was cancelled (`cancel`), `CancellationException` will be thrown
