### ISSUE TITLE
Promote `Dispatchers.Unconfined` and `MainCoroutineDispatcher.immediate` to stable API

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#972]
...and update documentation properly

**Comment by sdeleuze** [comment]
I was about to create this issue since I am about merging the first part of Couroutines support in Spring Framework `master` branch, and I would need that since it seems to good fit for Reactive interop where running on Reactor Netty threads seems fine. I would need it before June 5th 2019 (date of release of Spring Framework 5.2 RC1).

**Comment by qwwdfsad** [comment]
Fixed in 1.2.0-alpha
